UPDATE companies
SET agent_ids_notes = CASE id
    WHEN 506 THEN 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'
    WHEN 510 THEN 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '
    WHEN 511 THEN 'Heads up note 2026-01-23T16:35:00.000+05:30: Hi team, Sharing the heads-up note for our investment in [VoiceBit](https://www.voicebit.ai/) This is an AI voice agent for restaurant phone ordering automation that handles end-to-end operations including payments, loyalty, web ordering, and delivery - building towards becoming the new age system of record for direct ordering ("Zoca for Restaurants") DeVC is investing $200K as part of a ~$2M round @ $10M post money valuation led by 1984 VC We were introduced to the founders by [Samit Kalra](https://www.linkedin.com/in/samit-kalra-a6179365) (Partner at 1984 VC) This is a Core Cheque & our 2nd investment with 1984 VC (our first deal with them was Orange Slice - YC S25) **Founders** 1. [**Hitesh Kenjale**](https://www.linkedin.com/in/hiteshkenjale)** - CEO** 1. Berkeley MBA 1. 2x venture-backed founder (DesiHangover - grassroot footwear maker in India) 1. Reference check with [Abha Agrawal](https://www.linkedin.com/in/abha-agrawal-72439654) (ex-CoFo @ Desi Hangover): 1. *++ Used to be entrepreneurial always. Trying lot of side hustles. * 1. *++ Stand out superpower: dependable holistically to solve problems. * 1. *++ Passionate about numbers and moves fast. ++ Process oriented and focused. * 1. *?? Weakness: Should disconnect himself from people problem solving that aren''t critical. Tries to solve for too much for everyone. * 1. *?? When span of work expands, prioritization he needs to mature more than where he is. * 1. *Would you ba...'
    WHEN 513 THEN 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'
    WHEN 514 THEN 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
READ ME: 
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '
    WHEN 515 THEN 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '
    WHEN 518 THEN 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'
    WHEN 519 THEN '**TK Meeting ****2026-03-03**** (Met through common friend at Scapia)**: - **TK View: Maybe ** - Spikey: 0.5 ish on product (Anil also mentioned) - Spikey Needed: Consumer, and product - ++ Decent IQ - ++ right brain and growth archetype – maybe able to create intial virality – Built on her way community of 25k females, part-time DJ - ++ chip on the shoulder – spent 1st yr of college prepping for BITS/IIT, seek validation and thinks was one of the biggest lose - ++ outside in - ++ Like the idea of AI companion and Dating - ?? Didn’t hear deep consumer insights - ?? No unique moat from tech side – why bumble/hinge can’t eventually launch this feature? - ?? Raised 25k from grad capital but didn’t clock in revenue - ?? okayish BRCs **Founder Background** - **Priyansha (Co-founder & CEO)** - Ex-Microsoft (~3 years); moved from partner strategy to Product / AI initiatives - Built Microsoft India Instagram as side project - Worked on AI adoption / skilling programs for CXOs (2019–20) - Worked on large security incident response + 0→1 initiatives - Founded *On Her Way* (women travel); ran ~1.5 yrs; shut down - Joined Klook; launched hotels category 0→1; later growth + AI initiatives - Quit Nov (last year) to start Wingy - **Srishti (Co-founder & CTO)** - ~7 years at Microsoft - Lead engineer on consumer AI app (Seeing AI) - Azure AI Foundry team; worked closely with OpenAI on frontier model deployments + guardrails - Sisters; CEO (product/GTM) + CTO (AI/infra) **Previous Startup – O...'
    WHEN 520 THEN 'Product Vision & Strategy: - Building AI-powered knowledge sharing platform focusing on: - Marketing and GTM expertise initially - Internal knowledge transfer within enterprises - AI twin capability for expert knowledge sharing - Collections feature for knowledge organization - Target Market: Growth companies ($20-100M revenue) - Differentiation from competitors: - More automated than GLG/Guidepoint - Focus on GTM/marketing vs AlphaSense’s buy-side focus - Built-in AI capabilities and knowledge management
Notes:: Overall: Maybe+ EF ish profile Past outomes haven’t be large, but deep background of buidling in enterprise. Both product and GTM front well rounded need to run deep refs before getting to an answer
Background & Journey: - Built and sold multiple ventures including: - First venture (sold 2011) - Gaming company (sold 2013) - Mobicon - F&B tech company with 27M diner profiles - Raised $20M total funding - Present in Southeast Asia markets - Exited during COVID when 40% of restaurant customers were impacted
Current Fundraise: - Raising $4M for acquisition - Previous round at $12M SAFE note - Current round targeting $18-20M valuation - Gokul committing additional $1.5M
Current Venture - Wisely: - Platform connecting enterprises with experts for knowledge sharing - Current status: - Raised $2M to date - Gokul invested ~$1M personally - Generated $400-500K in revenue - Currently has 750 experts on platform - Planning acquisition to add 3,000 more experts and 700K minutes o...'
    WHEN 525 THEN 'AI notes: ### Action Items ### Founders'' Backgrounds - **Gurashish** is from Chandigarh studying at IIT Madras, developed passion for aerospace through NCC Air Force training where they first piloted a plane in 10th class - **Zaid** is from Hyderabad, runs a cooking YouTube channel with 200k subscribers that started during lockdown ### Zenova''s Product & Technology ### Competitive Landscape & Differentiation ### Go-to-Market Strategy Shift ### Current Customer Engagements - **Delhi Airport**: In discussions through GMI Group''s startup program to understand current detection gaps and explore pilot deployment - **Saudi Arabia**: In talks for pilot program, positioning as cost-effective alternative to $2-5M US/European systems ### Fundraising ### Investor Concerns Raised - **Procurement challenges**: 12-18 month sales cycles per customer, painful systems integration work - **Pricing risk**: Concern founders will accept low-ball offers (e.g. $60k/year) without understanding value-based pricing, limiting to 20-30 airport customers - **Product vs services**: Risk of becoming services shop doing custom integration rather than building scalable product platform, which eliminates enterprise value - **Market positioning**: Most large venture investors have already backed competing systems integrators, making fundraising difficult - **Defense quality**: Even if successful in defense, it''s a poor business with 270-day net working capital cycles, buyer concentration risk, and limited expo...'
    ELSE agent_ids_notes
END
WHERE id IN (506, 510, 511, 513, 514, 515, 518, 519, 520, 525)
  AND (agent_ids_notes IS NULL OR agent_ids_notes = '');