UPDATE companies
SET agent_ids_notes = CASE id
    WHEN 436 THEN 'RM notes: 1. “Altdevin” was initial name 1. 2 months ago 1. Devin web UI was very bad 1. Dev only operated as a Slack bot 1. Started coding at age 13 1. Codeforces etc - learnt C++ himself | competitive programming 1. 9th to 12th - studied for JEE | did CP 1. gave Olympiads - national bronze for CP 1. Sarvam intern 1. June 2024 - internship 1. LinkedIn post 1. Standard application process 1. Worked on AI Agents team 1. Operated like a quasi consulting business 1. AI X Coding - crowded but problems exist 1. Shiro is a shameless clone of OpenAI’s Codex 1. Iterate like mad - learn from users 1. At Sarvam - used ChatGPT & VSCode together | then used Cursor 1. User 1. Being leveraged for side or personal projects 1. Enterprise ask 1. Want a way to preview / browser attached to sandbox to see the UI before PR being raised 1. Wanted terminal ask 1. Value: 1. Code maintenance > Code Gen 1. Wants to pull in data from other sources to suggest changes to the product
**Background & Experience**: - Started coding with C++ at age 13 (competitive programming) - Won bronze medal at national level for competitive programming - Previously interned at Sarvam AI (2.5 months) - Worked on AI agents team - First startup office experience
**Current Product (Shiro)**: - Started building 2 months ago - Initially aimed to be better version of Devin with web interface - Current features: - GitHub integration - Kanban board functionality - Pay-per-task pricing model (no rate limiting or token caps) - Use...'
    WHEN 439 THEN 'BRC on Anu Engineer (main CoFo) from [Ajay Agarwal](https://www.linkedin.com/in/ajay-agrawal-aa79b12/?originalSubdomain=in) (Sirion Labs) done by @Aakash 2025-05-25: On email to @Rajat Agarwal 1. happy to speak and share me experiences w/ Anu. 1. BTW, I’m investing 500k in the SAFE round as well. Anu''s Key Strengths - Technical excellence and clear communication - Strong ability to simplify complex problems into simple language - Skilled at breaking down complex problems for both executives and production teams - Distributed team management capabilities - Successfully led 100% distributed edge team pre-COVID - Managed team of 24 (6 in Seattle, 18 globally) at Sirion - Strong at maintaining tight cadence with distributed teams - Personal qualities - Very humble and grounded approach - Direct but not confrontational in disagreements - Highly transparent in communications - Strong customer empathy and friendly demeanor Technical Leadership Experience - At Sirion: - Managed parallel engineering team of 20-25 people - Focused on AI-native stack for auto-extraction - Led implementation of BERT/Roberta models - Currently 1,200 different models deployed at Sirion - Strong technical followership - Demonstrated ability to quickly build technical teams - Successfully recruited past team members across multiple companies - Highly adaptable to new technologies - Stays current with latest developments - Research-oriented mindset - Quick to implement new approaches Areas for Support/Watch-o...'
    WHEN 443 THEN 'Analysis by dev - 2026-02-04: ### Company Snapshot Problem & solution Soulside Al offers an Integrated AI platform for High-Acuity Behavioral Healthcare to automate compliance and documentation, addressing workforce strain (clinician turnover, documentation time) and rising claim denials/regulatory pressure. Key product claims include automated documentation and audit workflows, a FineTuning Engine for rapid payer requirement updates, and a voiceprint-based Group AI. Outcomes cited: reduce documentation time by ~80%, lower claim denials by up to 25%, faster claim submission (4 days vs 22), and avoidance of clawbacks. Ideal customer profile and pricing Target market: Moderate‑high acuity Behavioral Health (including mental health, substance use, eating disorders), with multi-location facilities. Immediate market sizing highlights in the deck point to ~35K facilities as the addressable base. Pricing signals include: ACV pricing ranges around $85–$250 per license per month; additional pricing cues show per-intervention pricing and multi‑product potential (documentation and compliance). Immediate SAM ~ $27B; SOM in the 10–15% range within the near term (3–4B) per the provided sizing slides; TAM cited as $240B with a longer‑term SAM ~ $150B. Status of product & traction highlight Live revenue as of Jan 2026 with ongoing pilots; notable milestones include: - Feb 2025: first revenue; Jul 2025: second customer; Oct–Nov 2025: one customer per week; Dec 2025: >$500K ARR; Jan 2026: live...'
    WHEN 444 THEN 'Conversation notes with @Rahul Mathur from 09.07.2024: 1. Founders: 1. [Apurwa Masook](https://www.linkedin.com/in/apurwamasook/?originalSubdomain=in) — ISRO (internship) 1. [Sudarshan Samal](https://www.linkedin.com/in/sudarshan-samal-0267686b/?originalSubdomain=in) – L&T & ISRO (internship) 1. About Co-Fos 1. All from Orissa 1. Went to the same college - VSS Univ of Tech in Burla 1. 2nd year of college is when they began building rockets (2016) 1. None have aerospace background / family background in Govt services 1. Apurwa had a brief internship stint with ISRO in 2018 1. Discovery of rockets happened during alumni day event 1. College had got a ₹50L Grant from ISRO → hence had facilities 1. Worked on a project for local dam → to figure out where sedimentation & silting was taking place 1. Business 1. Order book (includes 2 POs and 1x iDEX order) ~ ₹35 crore at MOQ 1. Since they are building solid propellant→ this comes under export control 1. So while market is global; it requires G2G tie-ups to enable EXIM 1. Will need to invest ₹20 crore into CAPEX for facility 1. Facility needs to be on land which they BUY or LEASE for 99 years since license to do explosives is tied to the location of use 1. Will explore getting land from a defense corridor 1. Fundraising 1. Raised ~7 months ago ₹52 crore pre-money → ₹7 crore raise 1. From Angels only 1. HVB Angels invested $300K 1. Current round will be ₹30 crore on ~ ₹120 crore pre-money 1. In IC with Mounttech (Former Def Secretary’...'
    WHEN 449 THEN 'Scoring: **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious | ? | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | 8 | **10** | | Product Chops | 2 | 2 | | S&M Chops | 1 | 2 | | Domain knowledge & skills | 2 | 3 | | Breadth of exposure | 1 | 1 | | Familiarity/repeat work | 1 | 1 | | Advantage | 1 | 1 | |  |  |  | | **EO** | 7 | **10** | | 1-10 strength or some 0 to 10 | 4 | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership | 1 | 1 | | Network leverage | 1 | 1 | | Compounders |  | 1 | | Wealth top decile | 1 | 1 | |  |  |  | | **Thesis** | 6 | **10** | | Good thesis, sizable TAM | 5 | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline | 1 | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |'
    WHEN 451 THEN 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'
    WHEN 456 THEN 'AI notes: ### Fund Backgrounds and Structure ### Investment Strategy ### Portfolio Companies ### Future Plans ### Action Items
RM notes: 1. Groww founders invested through Stargazer LLP since 2020 1. 60 investments to date 1. Small cheques 1. Mehta Family was the first investor in Groww 1. This is a CAT 2 AIF - Mehta Equities was the investment manager 1. Got license in 2023 1. ₹70 crore Fund I 1. 39 companies invested to date 1. Early cheques were ₹15L 1. Now doing ₹5 crore cheques 1. Thesis 1. Not tied down to BFSI - sector agnostic 1. Consumer (FirstClub, Zepto, Swiggy, Handpickd, Gaming, Caava, Bold Care) 1. FinTech (excluding Wealth, Lending) - keen on Infra & compliance - PowerEdge, Decentro  etc 1. AI - OnFinance, Snowmountain AI, Maxim AI 1. Have done some Pre-IPO as well 1. Lots of investments in common with DeVC Fund I 1. Cybrilla 1. Finsire 1. Riverline 1. PowerEdge 1. Snowmountain AI 1. Co’s he wants us to check out: 1. [https://www.revway.io/](https://www.revway.io/) 1. [https://babblebots.ai/](https://babblebots.ai/) 1. Fund II 1. TBD 1. Has been proposed 1. ₹120 crore CAT I AIF 1. Want to do more early stage (Seed to Series A) 1. Avoiding pre-IPO 1.
Action items: 1. Modus Secure - [https://www.modussecure.com/](https://www.modussecure.com/) 1. [https://portfolio.devc.com/](https://portfolio.devc.com/) 1. Someone to share a rough evaluation work?
Conversation 2025-10-17T11:44:00.000+05:30: '
    WHEN 460 THEN 'Heads up note 2025-10-18T12:00:00.000+05:30 from @Rahul Mathur: Hi team, Sharing the heads-up note for our investment in [Stellon Labs](https://stellonlabs.com/) - an AI research lab that is building tiny frontier AI models that can run on edge devices like smartphones, wearables and embedded system DeVC is investing $250K as part of a post YC $5.2M round at $45M post money led by Felicis Ventures (early investors in Canva, Mercor, Notion etc) *Note: Cash was able to generate pull with the founders given his questions regarding the LPIPS approach and 1 bit quantization; founders appreciated the team’s depth in edge models & therefore created room in this round for DeVC * **Founders** 1. [Rohan Joshi](https://www.linkedin.com/in/rohan-m-joshi/) - CEO 1. MS @ CMU in Robotics (2019-2021) 1. 4 YOE @ Meta 1. [Divam Gupta](https://www.linkedin.com/in/divamgupta/) - CTO 1. MS @ CMU in AI (2019-2021) 1. 4 YOE @ Meta 1. 1.5 YOE @ MSFT Research **Investing Process** 1. **We sourced Stellon Labs as part of the YC S25 structured mining process** 1. Their Kitten TTS model accumulated over 8,000 GitHub stars and 60,000 model downloads on Hugging Face within two weeks of release prior to us interacting with the founders 1. **Cash & Krish did the 1PE** 1. Cash - Maybe 1. *Net: Sharp guys and might just build something specialized, but unlikely going to be something that catches fire. Can see a Mistral like journey* 1. *++ Technical spike is 1 and has the right BG with CMU and Meta (both CoFo...'
    WHEN 461 THEN 'Attendees:: | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): '
    WHEN 463 THEN 'Scoring (can be copied for multiple people): | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 | |  |  |  | | **Spikey** | `Calculate out of 10` | **10** | | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '
    ELSE agent_ids_notes
END
WHERE id IN (436, 439, 443, 444, 449, 451, 456, 460, 461, 463)
  AND (agent_ids_notes IS NULL OR agent_ids_notes = '');