UPDATE companies
SET agent_ids_notes = CASE id
    WHEN 154 THEN '1PE meeting w/ @Dhairen Tohliani 2026-02-19: Surfacing Finlead AI, they are building a commission management solution for insurers. Essentially bringing in dynamic commission structures to help insurers manage EOM better. Founders are spikey FFs and this is a clear pain point basis our insurance infra work in the past. Looking to raise $300-400k now and would recommend a 2PE from DeVC considering the founders, trendline and early momentum. Have pinged someone from PhonePe insurance for a BRC on the founder, will add the deck here as well. Views Dhairen – Maybe+, if refs check out and there is real substance behind what they’re conveying then clear SM ++ Entrepreneurial and hacky guys with early track record of achievement ++ H&H - was advising startups, got in touch with IRDAI for pushing current product ++ Sales motion - GoDigit (signed), Royal Sundaram (POC), Care - not easy to get insurers on board, so early especially ++ Insights and maturity for the age was surprising - in touch with regulators, ONDC, have foresight - deferred insurance implications ++ Thesis - EOM pressure is real - managing commissions better is addressing a clear pain point ?? Product is a thin wedge; they will need to keep iterating to expand ACVs - could get capped quickly on this current one if insurers try to move in-house ?? Positioning v/s reality – need to do refs here Meeting Notes Company Overview & Problem Statement - FinLead AI building B2B insurance commission management solutions - Founde...'
    WHEN 157 THEN 'Deck 2026-03-20T05:42:00.000+05:30: --- [File: attachment](https://prod-files-secure.s3.us-west-2.amazonaws.com/b21975bb-aebf-48e3-8c44-1573c4404129/388099bb-2c83-4cd4-b004-d67ee5130d0a/Firi.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAZI2LB466UA77UFQM%2F20260320%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20260320T103111Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGgaCXVzLXdlc3QtMiJGMEQCIAjR1%2FmOn94RxOu80GGrr8o161UpwC5DLvufUXyZ1E9QAiAgon%2Fcwopz%2BBQXS%2F8p95tqvyBpjToki0i7SiqvDHBOASr%2FAwgxEAAaDDYzNzQyMzE4MzgwNSIMo7zSX7qyUUCIgwTaKtwDZ7o3rhjnk%2BBfsK9bVab0hcIc3xEHV0Nk6TIpgxf22VkirHjhmCEngZOJxLcPK2K8rgdfV8dmj1FGpkfUJVgGJ6ovf6xWzfiS8j44MT5QrV09LtKGyPJDSVvGXwVtKediVJfQbtuoBSjQjOBzLail%2BtX%2BBzp4uQQ1K9N5Y%2Bap2r0%2FBWHWJqSoJ6JLV6TX7L7U3M5Q81xdT%2BE8s5%2FgKPYg%2BFFkXChHGlQSvy8m9c%2F2NcNrrDnBi87SBvLRRTFaG3ZL4slKFxd0rxLLWiaQA8nvMl2ytrxbihSHUXgukc1P1eFwtD%2B8Aohe%2FN1iWcmE4eN32zP4hXAac7%2BO5Bm17Jlr2CfamrvzVmJWDeiGKPXZXF4akfklutSCTtn4m0xDPjtE7q7uQVNldloKYhCOTbav%2FUk7uM9Mt8z%2FaFPD%2BWoazA3LivchZQyBb7cCyfsTd9nrrxdGOAxCUSMAC9rtg0kvq3Bj0n%2BKWT5tH%2FhsVj8xR4TeA2OIrK3dFl11BsBwo0DnCYfNmg8wa7Zv5rjsneyaqVX%2FqTT7qJs4QF1WJMblpnkTsoyLpyXaM8Meeb%2BSSBEDHl3TaVAjgsaSU8u8nFHgO0kCJXj3%2BfbCJtWsCeR2R3xntdrZlPEq60%2FvH9wwyvzzzQY6pgHMq4qzj0t3WVLhnEuLigoYScn0FjIjhKDhgfm5o1ANAgt1IPS%2FM01Mo0GyxrqttfTnYCs%2FM0Bqw0kQk542nxr6tra7QPBS8DqjFCkHtKA%2B%2Bb585NSGRb0jwTTPuJI%2B0DwEpVeq2VLqLXwkL3SSGy7LfNDdJm6ZrK5LCUlxT7N0LAXFA3sq9PKxNrw1GVZJJQ358%2...'
    WHEN 159 THEN 'Financial Update — Mar 2026 (Audit): - 2025 Revenue: ~$30,000 - Current Monthly Revenue: ~$5,000 - Jan 2026 Cash Balance: $90,000 - Monthly Burn (current): $20,000 - Burn expected to reduce further — targeting near-zero in 2-3 months'
    WHEN 160 THEN 'From @Anonymous: Agreed with views below – spoke to her today. Spikey – 0 (just hasn’t operated before and surprising lack of ambition for what she has done so far) EO 5| FMF 5| Thesis 5| Price 8 - Speaks well – has a good consultant background and work - Is going deep on product, consumer insights and brands ? Isn’t aiming for a big outcome ? Wants only patient capital ? Is building a team very luxury – will potentially build a new age Kama with a small TG ? Didn’t hear enough depth on what the market is, what consumers are saying, GTM Next – Pass and track for next [Table] [Table]
Convo 2024-09-17T17:59:00.000+05:30 with @Anonymous and @Anonymous: Rachna Bahadur: - Was at Bain and could only work with companies in small capacities - Looking to move deeper into value chain and couldnt find much - Byjus chased me for 6+ months and made an offer to head the international business that I couldnt refuse - Had an opportunity to co-found 82East - couldnt get over the line on the set-up they were offering (good decision in hindside) -  Was one of the most exciting things I refused from all the offers that were coming to me Building a beauty brand focused on women in menopause and menopause segment. Product - Part of the identification was personal and rest research - Delhi & Bombay pincodes - women aged 40-45 and 50-55 to understand whats changing - We speak to women between these age groups. Its more homogenous across different geos - Care is no longer a luxury. Its customer backw...'
    WHEN 161 THEN 'Rm notes — Reflections - FF | Concept | Spiky = 0.5 - should validate from BRCs |: ++ Clarity of thought, good articulation around problem space ++ Hard fought learnings from 1st stint - NOT chasing VC or Twitter hype, wants to validate ++ Taking on hard technical problems e.g. OEMs blocking deep links etc ++ Outside in; has studied other players in the market ++ Self taught software engineer ?? Slightly worried this is a missionary profile and NOT a business builder profile ?? Space has been DOA for a long time
Rm notes: 1. Was thinking about doing Master’s 1. Bain 1. Got back into coding after Bain - YouTube video learnings 1. Browser extension 1. Thoughts on device 1. platform agnostic or OEM agnostic | on device layer 1. Wants to challenge → https://www.opal.so/ 1. Building a second brain → Agent on phone 1. Wants to do a Reddit or offline launch to build convection before going to SPC et
Ref from Aniket (Bain) via Ashwin 2025-09-25T15:15:00.000+05:30: 1. Quirky 1. Thinks differently from others 1. Don’t have solid POV on whether he is great at building or a good product guy 1. Generally positive on him, smart guy
prep notes 2025-09-24T21:57:00.000+05:30: 1. Introduced via AeroDome founders who are from IIT Madras ecosystem 1. About Rohith 1. Prev. company was called Flowstate - https://www.flowstate.cc/ 1. New company 1. My notes
Meeting 2025-09-25T12:07:00.000+05:30: 
Ai notes: '
    WHEN 164 THEN 'Evaluation Plan + Key Questions to answer: 1. What does the company do? 1. Do we (DeVC/Z47) have a thesis on this space? 1. What are the top 3 questions to diligence? 1. Who has piped this company to us? What are their views? 1. What do refs say about the founder? 1. What''s the DeVC team views? 1. What are the Collective signals? 1. Why is this company likely to be special? 1. Who can help? Experts / Venture Partners? 1. Deal dynamics? Potential deal to do? ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: '
    WHEN 165 THEN 'Dhairen - 2026-02-02: Cash/AP had interacted last time around - view was that founders were opportunistic (original plan was fashion, then jumped to stablecoin trendline). Spoke to Saloni this morning - quite positive on the founders compounding. White has invested. Company has pivoted to stablecoin cards with early traction through a reseller model. General interest in spending time given traction in Kast, Aspora etc. Company has moved to global GTM now - unclear what''s the RTW/RTP. Founders in Bangalore Feb 4-6 to meet people. Dhairen wants to join if we''re meeting, or can set up separately.'
    WHEN 166 THEN 'Rajat reflections - SM for $100K: ?? Key Q: GTM chops || PDF conversion ++ Clear Why Now because of Tech improvements & AI FOMO ++ Very Spiky || walked in negative - very intelligent folks ++ Product seemed interesting ++ Potential to go viral like Quizziz ++ Superior to the OpenNote team; much better product ++ Clear why now - given this is a P0 problem for every teacher ?? Very raw on GTM || going to be a crowded market ?? Roadblocks from a product adoption lens - if they can integrate into LMS and automate the PDF creation - it could be a game changer ?? Product does get commoditized - but no one will build at their pace
Product & Market Strategy: - Current focus: Math grading with instant feedback and error identification - Processing: Parallel agents handle hundreds of worksheets simultaneously - Vision: “Agile learning” - zero-cost grading/lesson planning enabling personalized learning journeys - Go-to-market approach: - Key market timing advantages:
Heads Up Note 2025-08-26: Hi team, Sharing the heads-up note for our investment in Frizzle Frizzle is an AI-powered solution for grading handwritten math worksheets. The platform helps teachers save 10-15 hours per week on grading while creating a faster feedback loop for students. The founders position their solution as enabling "agile learning" compared to the current "waterfall" approach in education where students wait weeks for feedback. DeVC is investing $100K as part of a YC SAFE round (more details) below Note: deck...'
    WHEN 167 THEN '(1) Founders and Key Team: Name – Shrey Doshi – Title - Career snapshot (one-line): BBA in Marketing;Entrepreneurship background; family business in pharmaceutical exports; roles in media sales, digital marketing, and FMCG sales. - Functional responsibility in current venture: Sales, marketing, and related GTM activities (as indicated by roles such as Head of Sales - FMCG and related marketing leadership). - Equity % (if stated) and commitment: Not disclosed. - Relevance of prior experience: Strong in marketing, sales, and distribution channels, which are relevant for consumer wellness product GTM in India; explicit domain experience in FMCG and pharmaceutical exports may aid distribution and partnerships.
Company Snapshot: Problem & solution - Problem: Nutrition does not equal absorption; a large portion of the population has impaired nutrient processing (BCMO1 variant, MTHFR variant), with 48% unable to convert plant carotene to Vitamin A and up to 70% of people needing more supplements/higher dosages without seeing a difference. This aligns with India’s nutrition paradox and demand for more effective, bioavailable solutions. - Solution: A Spirulina-based super algae formulation marketed as having high bioavailability and broad health benefits (anti-aging, anti-inflammatory, immunity, liver and gut health, etc.). Core ingredients cited include Spirulina, chlorophyll, phycocyanin, and carotenoids. Claims include improved nutrient bioavailability and multiple health outcomes ...'
    WHEN 168 THEN 'Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---'
    ELSE agent_ids_notes
END
WHERE id IN (154, 157, 159, 160, 161, 164, 165, 166, 167, 168)
  AND (agent_ids_notes IS NULL OR agent_ids_notes = '');