UPDATE companies
SET agent_ids_notes = CASE id
    WHEN 325 THEN 'Meeting Prep — 2026-03-02: **Source: **DocSend deck + email pre-read from raj@withorbi.com (Mar 2, 2026) **Deck: **[https://docsend.com/view/y3wrtejc6wv8kem4](https://docsend.com/view/y3wrtejc6wv8kem4) ### Traction - 1,110+ invite-only beta users - 30% WoW growth (Nov-Jan) - 60% M1 retention (best cohorts: 80%) - 26 min avg session (2.5x Roblox), max 6 hrs/week - 50% referral rate ### Market - US 5-12: 30M kids × $123 ARPU = $3.7B/yr - Global: 1.2B+ digital-native kids × $60 = $70B+/yr - AI companions: $37B (2025) → $552B (2035), 31% CAGR ### GTM - Homeschooling networks (VELA, Primer, National Microschooling Center) - App Store waitlist: 3K+ | Parent influencers: 10K+ | Gaming creators: 50K+ - Monetization: microtransactions + subscriptions ### Raise $2M seed. Roadmap: Phase 1 digital worlds → Phase 2 cross-app (Minecraft, YouTube) → Phase 3 offline (toys, wearables) ### Key Questions 1. Safety & regulatory: COPPA, Character.AI lawsuits, content moderation framework? 1. Valuation & DeVC fit: $2M raise at what val? Where does $30-150K cheque fit? 1. FrontRow post-mortem: same team, what failed, what''s different? 1. Retention depth: M3/M6 curves? Novelty decay risk in kids products? 1. Unit economics: inference cost per session? Can microtx + subs cover it? 1. Roblox defense: what if Roblox adds AI companions? ---
AI notes: ### Founder Backgrounds - **Raj** leads growth at Hobby; previously taught sports, arts, and math to kids in a government school in India starting at age 1...'
    WHEN 327 THEN 'Rajat - Follow-up Call Request - 2026-02-26: Rajat requesting follow-up call with Aakash and Rahul after initial call with Raj Singh (CEO). Sneha to set up - Raj is based in the US. --- PRE-READ FROM RAJ (24 Feb 2026): PRODUCT DEMO & SESSION RECORDINGS SHARED: 1. Product demo video - Video link provided 2. Session recordings to show core user behaviors: SESSION #1 - Emma, 10 yo | 45 mins session | 2 days ago TLDR Insights: - Treats her pet "Whiskers" like a living being with needs, engaging in care-taking activities like making soup and visiting the vet when her cat is sick - Invents mini-games and activities to do together (playing fetch, painting, learning to spell) - KEY QUOTES: "You are my favourite part of the day." "I can do this all day and night." SESSION #2 - Freddy, 9 yo | 1 Hour 31 mins | Today | M2 cohort TLDR Insights: - Even in month 2, Freddy is still highly engaged, his storylines are richly detailed, unusually specific about the world, characters, and micro-details - Brings all his favourite characters like Sonic to life, creates adventure storyline with them and his pet --- ORIGINAL PRE-READ (23 Feb 2026): COMPANY OVERVIEW: Orbi is building AI companions for kids designed for play, learning, and social connection. Kids are skipping Roblox to create social worlds with their companions, spending up to 4 hours per day. TRACTION: - Beta with 1000+ kids - Growing 30% WoW - 60% M1 retention TEAM: 1. Raj (CEO) - Led growth for India''s first alt-tech university from...'
    WHEN 329 THEN 'Key Metrics & Product: - YC W26 batch | 4 employees | HQ: 311 California St, San Francisco - Axis outperforms Google DeepMind''s AlphaGenome by 6.7% on regulatory element binding prediction - Building largest proprietary dataset of millions of experimentally validated regulatory DNA sequences - 72% sequence diversity — generated sequences explore genuinely novel design space - Wet lab + AI — currently testing sequences in lab to validate
RM notes: - Yash raised money from Contrary Capital - Started at end of 2024 - Dropped out of college - Released first model in October before YC - Encode data set - Scientific Advisor - Dr. Manolis Kellis — Professor of CS, MIT + Broad Institute (regulatory genomics) - Keen to connect Onco data in India - Mass of data available - Raised $3M funding to date - Signing LOIs from hospitals - Targeting 3-5 LOIs - BOM hospital is pending ethics committees - CloudNine
AI notes: ### Action Items & Next Steps ### Company Background & Founding Story ### Breakthrough Model & Technical Approach ### Data Strategy & Scaling Approach ### India Hospital Partnership Strategy ### Experimental Approach with Hospital Samples ### Business Model & Revenue Streams ### Funding Status & Plans ### Network & Connections Discussed
Scientific Advisory Board: - Dr. Manolis Kellis — Professor of CS, MIT + Broad Institute (regulatory genomics) - Dr. Nicole Paulk — Founder & CEO Siren Biotechnology, Asst Professor UCSF (AAV gene therapy expert) - Dr. Rashid Bashir — Dean, Gr...'
    WHEN 331 THEN 'Rajat reflections: ++ Hustler ++ Outside-in +? Reasonably thoughtful ++ High agency ?? Value in business lies in automation of invoice sending, 100% lead capture & follow-ups etc ?? Risk of Sales adoption; RA has seen it in his own family business ?? Thin product right now ?? Tough business to build Rajat Qs 1. Why pick Industrials & Manufacturing? 1. Why do India only? ### Action Items & Next Steps ### Product Overview & Problem Statement ### Solution Description ### Current Capabilities & Roadmap ### Business Model & Pricing ### Go-to-Market Strategy ### Traction & Metrics ### Team Composition ### Fundraising Details ### Growth Strategy & Market Opportunity ### Key Challenges & Discussion Points
Received from Rahul - 2026-03-07: [https://in.linkedin.com/in/rohitrajxd](https://in.linkedin.com/in/rohitrajxd) --- ### Action Items ### Z47/DeVC Investment Philosophy ### Founder''s Background and Journey ### Previous Company: Worker AI ### Current Company: Pactyl ### Team - **Ravi** (technical): IIT Monday computer science, Mars rover community, job offer from Turing by end of second year, previously built cloud gaming company - **Nishit Sharma** (business development): ### Fundraising Details ### Competitive Landscape & Market Context ### Next Steps with Z47
DE w/ Bhuvan (CTO @ OfBusiness) 2026-03-19T18:32:00.000+05:30: Context: OfB actually building something quite similar and an analytics copilot on Tally to give business insights; hasn’t seen a product demo - pending for their...'
    WHEN 335 THEN '2nd convo with @Aakash and @Rahul Mathur: 1. **Family background** 1. Sajial and Sailesh are blood siblings 1. Their uncle owns Hello Kids 1. All relatives are involved in the secondary steel business in Raipur 1. Right from Manfacturing to the retailer part of the value chain 1. Some relatives have CAPEX outlay of ~₹50 crore to ₹200 crore 1. Their father is the odd one out in the family i.e. owns a confectionary business 1. **Saijal background** 1. Rank #2 in IIT-B Metallurgy department; batch of 2023 1. Studied under: Prof Vishy, Manish Pandey and Sanjay (who is her mentor) 1. Thesis: Secondary steel manufacturing; published in ASM journal 1. Managed to get JSW to partner with IIT-B to finance a fest & research projects 1. Has done internships at Jupiter, Rocketium, BharatX 1. Decided to NOT pursue the funded PhD from IIT-B with Tata Steel since she felt India’s journey on green steel was very nascent & work was too elementary 1. Got a PPO from Kearney; worked in GGN office because of their energy projects 1. in 4 months, got placed in the project working with Ministry of Road Transport 1. It was a project to map out Indian highways for ~25 years with Nitin Gadkari 1. Left after this project because it then became project management 1. **Sailesh background** 1. Christ College 1. Dropped out 1. Did consulting biz for Ed in 2nd year to make money 1. Uncle convinced father to support him with this decision 1. Had lots of friends who were in IITs — saw their innovation 1. Saw R...'
    WHEN 336 THEN 'Meeting with founders at GFF sidelines 2024-08-29T18:28:00.000+05:30: Attendees: @Anonymous and @Rahul Mathur 1. Avi 1. Darbangha 1. IIT-D for college ; electrical engineering 1. Wanted to do PhD 1. Joined Booz out of college 1. 2013 → 1st company; e-comm boom 1. 2015 got acquired by CarDekho for PriceDekho 1. COS → 8 to 9 month stint 1. Built auto lending business at CarDekho → worked with a bunch of banks 1. Good understanding of FinOps 1. Credence → 2nd company 1. 2017 → 2023 1. Initially only domestic lending 1. Then COVID hit → so began lending to study abroad market 1. NBFC license got returned due to Mauritius money 1. 2nd buyout offer from Shriram Finance 1. Lending book was subsumed into Travel India 1. Top 3 learnings → asked by @Anonymous 1. Find problem statements which let you work on them for 10-15 years 1. Arbitrage opportunities exist for a reason; focus on fundamental problems 1. Other co-fo 1. From J&K → Studied there till 10th standard 1. BTech Delhi 1. Interest in cyber & data security 1. Joined IIIT Delhi as a Privacy Researcher 1. Masters in Data Security from France 1. Learned about GDPR 1. 1st company 1. Disecto 1. Got Govt grants 1. Homomorphic encryption for data sharing 1. Blume & Omidyar keen to invest 1. Spent 2 years 1. India’s top law firm 1. Built their privacy vertical 1. Didn’t enjoy doing consulting 1. How do Co-Fo’s know each other? 1. Met online on LinkedIn 1. Privacy focus was of interest to both 1. Why this? 1. Younger generation cares 1...'
    WHEN 337 THEN 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '
    WHEN 338 THEN 'Product review 2026-01-16T13:57:00.000+05:30: - Same space as the PPM from Khatabook - family finance manager - Decent build - but seems like FF building out of domain - lots of simple misses e.g. doesn’t have a PW flow for docs onboarding etc [Child Page: PeaceVault Product Review]
Quick ref from Ravish (COO @ Khatabook) 2026-01-16T13:30:00.000+05:30: 1. He''s pretty good 1. I think he''ll do great as a founder. Don''t really have specific points. He led a few initiatives at our end and did well.'
    WHEN 339 THEN 'De-brief (if any): From @Aakash Overall: Maybe for DeVC Spikey: 0.5 | EF/FF: 4-5 | Archetype: 7-8 | Thesis: 5 - + playing to large latent demand market and strong trendline; timing risk is real though and they are aware that they are playing to a market with maturing problem awareness but limited solution awareness as of today - + Continue to like Shashank and probably one of the most thoughtful product thinkers with a business bent; product sense is strong but not top 1%, makes up for it with learning and continuous iteration - + Real need gap for high intent and solution aware users. Eg: preventive first users who do not wish to go to a hospital for prevention or are underserved by standard clinical practioners - Will get their cold start and early single centre break even with non scalable GTM ; going to struggle in the scale up - They have good thoughts on testing based GTM wedge for scale, but that is going to be a risk one would have to take - Lack of FMF can be substituted somewhat by surrounding with folks like Rohit MA if he comes in via Peer (Shashank is super keen to have him lead) Would surely be a community cheque for us, already qualified given marshot plus other angels would step in. Hard to see this as a candidate to dial up our entry cheque given lack of FMF and no experience with consumer GTM. Getting to scalable GTM post early PMF is an additional challenge they’ll have to tackle post first centre success. Next steps: They are looking to raise $1.5 (lead) +...'
    WHEN 341 THEN 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'
    ELSE agent_ids_notes
END
WHERE id IN (325, 327, 329, 331, 335, 336, 337, 338, 339, 341)
  AND (agent_ids_notes IS NULL OR agent_ids_notes = '');