INSERT INTO util.enrichment_staging (company_id, content) VALUES
(494, 'AI notes: Skydo''s founder Movin shared insights about their experience as an early customer of TruFides, an AI startup in the compliance and fraud detection space. This conversation provided valuable feedback about TruFides'' product, founders, and market positioning for a potential investor. Background and Relationship: - Movin knew Devang (TruFides co-founder) from PhonePe where Movin hired the first batch of APMs - Skydo became TruFides'' first non-crypto customer about a year ago - Implementation occurred approximately 4-5 months ago - Skydo pays about ₹80K (1/10th the cost of a compliance team member at ₹8L CTC) Problem and Solution: - Cross-border payments face money laundering risks requiring negative media screening - Traditional process: Compliance team manually reviews negative media articles - TruFides solution: AI reads articles and extracts key information to: - Disambiguate identities (is it the same person?) - Assess crime seriousness and transaction relevance - Reduce review time from 10 minutes to 10 seconds per case Results and Impact: - Solution "works beautifully" as Skydo''s "first AI win" - Saves approximately one full-time compliance person - Compliance head is satisfied with the implementation - Became a precedent for other AI adoption within Skydo Competitive Assessment: - TruFides vs. Fravity (Elevation Capital investment): - TruFides was immediately focused on a specific use case - Fravity was "all over the place" initially with too many use cases - Fr...'),
(499, 'Investment note from @Anonymous 2025-05-14T12:23:00.000+05:30: Sharing the note for our $30K investment in UGX.AI as part of their angel round of $547K at $4.4M post-money. This should amount to ~0.69% ownership at conversion. Venture Partner: Ramakant Sharma DeVC Collective: Utsav Somani, Manish Agarwal Other angels include Asad (Lambdatest), Loveleen Bhatia (Edureka), Prateek Maheshwari (Physicswallah) and Mihir/Ravish from PointOne capital. Investing Process: - Cash got the lead from RK and did the 1PE - Ran a quick 2PE with the full DeVC team and also socialized the thesis/opportunity with members like Vasant (OfB) and PeerCapital. - We did BRCs on the key founder and realised that they are out of domain and strategic thinking could be a big gap hence only warrant a 30K community top-up basis the excitement from the collective (2+ collective member commit criteria) About the Company UGX.AI is building a full-stack Industrial DataOps platform to enable manufacturing companies to access and leverage real-time machine data for productivity, cost efficiency, and sustainability improvements. They provide an integrated hardware, middleware, and software platform including: 1. Universal Edge Gateway: Low-cost, industrial-grade device for machine connectivity. 1. Industrial Protocol Library: Supports 40+ machine models, converting complex machine protocols into software-friendly APIs. 1. Unified Industrial Data Platform: Transforms machine data into actionable insights. 1. Indust...'),
(500, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(502, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(503, 'Notes from Notion AI: Chanakya discussed his Up&Run electrolyte drink business with an investor/advisor Rahul, sharing details about the product, business metrics, and fundraising strategy.
Product & Background: - Sugar-free hydration product similar to US brand Element (99% identical formulation) - Created after 6 months of R&D using family''s medical network to find manufacturers - Working with same manufacturers as TWT, establishing a second manufacturing line - Patent filed for the formulation in India - Founder is a distance runner who was an Element consumer
Business Traction: - Live on Blinkit in Maharashtra since February 2025 - Also on Amazon, Flipkart, and soon on Clinically (PO being finalized) - Selling ~100 units/month on Blinkit, ~80 units/month on website - AOV: ₹400 on Blinkit, ₹600 on website - Current monthly revenue: ~₹1.5L (₹50K from website, ₹50K from Blinkit, ₹10-20K from other channels) - All growth has been organic so far (no paid marketing)
Fundraising Strategy: - Rahul advised reaching ₹10-15L monthly sales before approaching institutional investors - Recommended a friends & family round of ₹1-1.5 crore - Suggested valuation of ~₹10 crore (15% max dilution) - Recommended avoiding predatory offers (had received ₹1 crore for 50% equity offer) - Founder should retain ~25% after multiple funding rounds
Action Items: - [ ] Chanakya to send list of potential angel investors who are already customers - [ ] Chanakya to share a short business description for i...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(506, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(510, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '),
(511, 'Heads up note 2026-01-23T16:35:00.000+05:30: Hi team, Sharing the heads-up note for our investment in [VoiceBit](https://www.voicebit.ai/) This is an AI voice agent for restaurant phone ordering automation that handles end-to-end operations including payments, loyalty, web ordering, and delivery - building towards becoming the new age system of record for direct ordering ("Zoca for Restaurants") DeVC is investing $200K as part of a ~$2M round @ $10M post money valuation led by 1984 VC We were introduced to the founders by [Samit Kalra](https://www.linkedin.com/in/samit-kalra-a6179365) (Partner at 1984 VC) This is a Core Cheque & our 2nd investment with 1984 VC (our first deal with them was Orange Slice - YC S25) **Founders** 1. [**Hitesh Kenjale**](https://www.linkedin.com/in/hiteshkenjale)** - CEO** 1. Berkeley MBA 1. 2x venture-backed founder (DesiHangover - grassroot footwear maker in India) 1. Reference check with [Abha Agrawal](https://www.linkedin.com/in/abha-agrawal-72439654) (ex-CoFo @ Desi Hangover): 1. *++ Used to be entrepreneurial always. Trying lot of side hustles. * 1. *++ Stand out superpower: dependable holistically to solve problems. * 1. *++ Passionate about numbers and moves fast. ++ Process oriented and focused. * 1. *?? Weakness: Should disconnect himself from people problem solving that aren''t critical. Tries to solve for too much for everyone. * 1. *?? When span of work expands, prioritization he needs to mature more than where he is. * 1. *Would you ba...'),
(513, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(514, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
READ ME: 
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: ')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;

