INSERT INTO util.enrichment_staging (company_id, content) VALUES
(389, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(390, '**Broker SaaS**: We have been iterating hard on the core of Realiti’s SaaS foray, the Broker GTM. After lot of experiments we are ready to publish authoritative numbers on our first sales campaign in June 2024. **Total Leads - 600** **Leads in active follow up - 380** **User Self Signups - 90 ** **Realiti Microsite activation  - 35 ** **Paid customers - 10** Some key points to note here: - All of these are **Self Signups** originating purely from Google and FB campaigns and not by forced cold calling - The** Microsite activation** is a very important step. It is an industry first product which puts a ultra modern variant of a self branded ‘99 acres’ or ‘MagicBricks’ in the hands of each broker. And again these are fully user initiated activations - **> 50 % **of the unconverted leads from this campaign are fully warm and our conversions and word of mouth is only improving day by day Most importantly this is totally in addition to our existing **$200K ARR** from our builder line of business. Our immediate goal is to increase magnitude of these campaigns and hit predictable monthly revenues from the Broker SaaS line of business
Overall Marketing Efforts: - It is a massive effort to sell any SaaS to SMEs in India, especially to brokers in real estate - On top of that, achieving self signups, activations of microsites and paid conversion takes a lot of tireless efforts on content creation, experimentation and best-in-class marketing automation - There has been a radical overhaul ...'),
(394, 'Ishita from Westbridge on Credgenics & Collections 2026-01-15T19:29:00.000+05:30: *Context: Ishita Shah was the sole analyst on the Credgenics deal done by Westbridge in 2022. She continues to be the primary POC for Westbridge on the portfolio management for this company, spends significant amount of time with Chief of Staff and CEO, even spent three weeks embedded in a Credgenics customer called *[*SMFG India Capital*](https://www.smfgindiacredit.com/)* (investor in Yes Bank & owner of LendingKart) * Net: She is -ve on the Collections & wider FinTech Infra opportunity in India because BFSI co’s don’t want to pay for Tech and want a “cost plus” pricing model for services. Not possible to dominate the industry because BFSI wants vendor re-risking with 2-3 players for key services like Collections. However, reading between the lines - there is an opportunity to build the “2nd place” Tech enabled collections agency (potentially w/ some ARC partnerships) due to the nature of this industry - 2nd place Spocto has been acquired, 3rd place Credit Nirvana, Perfios acquired Credit Nirvana. But, given what has happened w/ Perfios et al in Fin Infra - one has to be careful about entry price & TAM ceiling. Notes from convo: 1. Credgenics 1. Started as pure-play Tech vendor 1. But, even when WestBridge was underwriting in 2022, it was apparent that Services will be important 1. Wasn’t underwritten as a SaaS company 1. SaaS TAM =$200M v/s Services TAM = $1bn 1. However, they underestimated ...'),
(395, 'Attendees from DeVC: @Anonymous: - Early employee in Urban Ladder. Get BRC from [Untitled](https://www.notion.so/8cc6d1e9f866433a80646661afb1a7c2) - Spent 5 years in Australia building a funded furtniture startup, that got acquired as they ran out of cash - Has done ops, inventory, product management, NPD etc at both companies - Wants to move back to India, be closer to family, settle in Bangalore - Explored home as well, but not excited by it - Thinks there is a space for a fabric innovation first brand starting with menswear - Tshirt priced at 3500 - Pants priced at 4000-5000 - Speaking to Shuchi at Fireside, Rajiv at Antler and a few others - Will come back and pick up early Jan with folks - Raising 500k - Told him to raise 1mn instead to manage inventory - Good top down story teller, but didn’t find consumer insights or RTW yet in this conversation **Founder Introduction:** Rushabh, previously involved in building businesses in the home and furniture sector, is now exploring opportunities in the fashion industry with a focus on functional apparel. **Business Idea:** He is considering launching a brand called PRBT, inspired by the concept of peak performance and ascension. The brand aims to create functional, stylish, and comfortable apparel using innovative materials that cater to the evolving lifestyle needs of consumers. - **Brand Concept:** - PRBT is inspired by the idea of peak performance and ascension, aiming to offer apparel that is both functional and stylish. - T...'),
(398, '**Detailed Notes**: **Background** - Started in 2011-12 with iCouchApp - Moved across India; dad was in a government job - Mostly lived in Calcutta and Delhi - Did college at BIT Meerut - Worked at Wipro, then left with Ashish - Initially funded by Morpheus **Early Inspiration** - Decision to start came from Rohit Marwade, a senior in college who was the inspiration - Another college friend worked at Indigo Star, Hotstar - Ashish was the CTO - Satvik and him were electronics majors - Senior was doing college stuff and went to IITB - Eureka was the first B-plan competition in India - He won a prize and we all spoke about it - "I got the keeda after that" - Worked at Wipro for experience and didn''t like it - Read about global startups being built - Used to go to all the B-plan competitions - Met Sameer at some of these events **First Venture - iCouchApp** - Got 5L funding - "That was a lot of money then" - Ashish left immediately; "I paid him half of my salary" - Indus Khaitan rejected their idea initially - They left their jobs and Morpheus didn''t invest at first - Took money from dad and started - Morpheus liked what they built later - After they invested, raised money from others - Then started building the company - Got to 5-6L revenue per month **iCouchApp Product Journey** - 2M subscribers - Partnered with KBC and others - "We saw things crash when we did KBC" - "We were just looking to solve our own problem back then" - No DTH or satellite available - Wanted to build a r...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(399, 'Heads up note from @Aakash 2025-04-04T19:22:00.000+05:30: Sharing a brief note for our $50K investment in [Revspot’s](https://www.revspot.ai/) pre-seed round, amounting to 0.75% ownership. This is round where paperwork is closing now, we had committed in Sept 2024. The co has since scaled to $300K ARR, even hitting $80K ACVs with Indian customers. This is a community cheque underwriting with RK, Chirag, Aakrit and Miten The co is raising $1.4 Mn at $6.6 M post money. Round is being co-led by Titan and Infoedge ventures This was brought to us by RK and product was strongly vouched for with a strong reference on Darshan. We are restricting this to a community cheque even with multiple folks from the collective giving a strong signal, given lack of FMF on SaaS GTM and very India first build out **About Co** - Revspot is building AI powered pre-sales agents and marketing intelligence tools for the non-SaaS world where MQL generation is key to growth (vis Financial services, Real Estate, O2O platforms) - They have early traction with Livspace, Dezerv, Meragi, Stabl Money and multiple other cos and are adding logos at a fast clip **Founding Team** 1. [Darshan Subhash](https://www.linkedin.com/in/darshansubash/?originalSubdomain=in) - Was leading customer success in 6Sense in his most recent stint. Got there via slintel acquisition (where he was the chief of stagff) - Was earlier leading sales strategy at Livspace and had a short stint at Unacademy - IIM Indore 2014 1. [Varun Garg](...'),
(400, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '),
(401, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '),
(404, 'Heads Up Note 2025-11-25T09:18:00.000+05:30: Hi team, Sharing the heads-up note for our investment in WorkAtoms which is a text to workflow builder for non-engineering knowledge work (e.g. content writing, social media monitoring, responding to inbound requests etc) - initial focus is on Marketing & GTM teams DeVC is investing $50K as part of a $2M SAFE round @ $10M post money valuation *Note: This is a founder-first investment (based on IIT-B signals) + Community Top Up to *[*Nikhil*](https://www.linkedin.com/in/nikhil-abraham)* from Cloud Chef (new DeVC Collective member in US). Hence, we have sized the cheque accordingly & will do more work in coming months as they tighten their GTM and sharpen their product (hopefully for a single vertical) * **Founders** 1. [Dhruv Jaglan](https://www.linkedin.com/in/dhruv-jaglan/) - CEO & Founder 1. IIT Bombay CS 2020 1. 2.5 YOE @ BabbleBots AI - was promoted from Founding Engineer to Co-Founder 1. 1.5 YOE @ LinkedIn India 1. From Cash:* ++ soft refs from IIT-B network on Dhruv : “Rockstar and would get anything done”, “Machau ladka hai.. keeps picking new things and building”* 1. [Georgi Boby](https://www.linkedin.com/in/georgi-boby-07b081161/) - COO & Co-Founder 1. 6.5 YOR @ Cloudchef as Founding Engineer 1. IIT Bombay 2019 1. From Cash: *++ Table thumping ref on Georgi from Nikhil @ Cloud Chef and Ashray @ Rephrase AI* **Investing Process** 1. We were introduced to Dhruv Jaglan (main founder) via Activate AI (Aakrit & Pratyush) 1. Act...'),
(405, 'Attendees:: | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;

