INSERT INTO util.enrichment_staging (company_id, content) VALUES
(406, 'Notes:: 1. **Ankit & other CoFo Jayant** 1. Pissed off that students couldn’t take CS programs unless they did pre-reqs 1. Made a simple web tool to map out pre-reqs & simulate the pathways in future semester 1. 1 year together selling software to corporate training academies 1. Both were Tech CoFos hence no Sales muscle 1. **Abhishek** 1. Feb 2024 → Jayant and Abhishek wanted to do something together 1. Put everything on the line to built a business 1. Ankit has student loan 1. Jayant has left PPO 1. Tried to sell personal transcribing tool to founders 1. His dad has taken an unsecured biz loan at 48% p.a. 1. **Problem → multi lingual conversations in Indian call center** 1. Spammed everyone on LinkedIn 1. Jazib Ali from Slice → collections team is 300 versus CX team is 30 1. Sometimes caller goes beyond boundaries to demand collections 1. Went to Poonawala Fincorp NBFC call center in Pune — “couldn’t imagine place in the world where 300 people are shouting” 1. Understood that QC executive (20 of them) will fill in forms 1. “Wanted to move from cost center to revenue generation” — started as QC tool but realized collections is better 1. **Learnings** 1. Being first to collections is critical 1. “Promise To Pay” disposition doesn’t capture the full context of the call 1. Collections call analysis is the wedge 1. Now migrated to making the collections call 1. **GTM** 1. Spammed on LinkedIn — tried different copy 1. Nira Money — cold email 1. Jupiter, Groww — cold email as well...'),
(408, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '),
(410, 'Scoring (can be copied for multiple people): DC: **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | 2 | **10** | | Product Chops | 1 | 2 | | S&M Chops | 0 | 2 | | Domain knowledge & skills | 1 | 3 | | Breadth of exposure | 0 | 1 | | Familiarity/repeat work | 0 | 1 | | Advantage | 0 | 1 | |  |  |  | | **EO** | 2 | **10** | | 1-10 strength or some 0 to 10 | 2 | 4 | | Commercial POC/history | 0 | 1 | | Thoughtful hustle and hunger | 0 | 1 | | Referenceability and followership | 0 | 1 | | Network leverage | 0 | 1 | | Compounders | 0 | 1 | | Wealth top decile | 0 | 1 | |  |  |  | | **Thesis** | 7 | **10** | | Good thesis, sizable TAM | 5 | 5 | | (++) small share of direct SAM = large rev $$ | 1 | 1 | | (++) Tailwinds + secular super strong trendline | 1 | 1 | | (++) Key is product IP only or Biz acumen only | 0 | 1 | | (++) Early Traction proof points | 0 | 1 | | (++) Table thumping expert/DEVC Founder validation | 0 | 1 | |  |  |  | | **Price (Post Money)** | 10 | **10** | | Sub 6M | 10 | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on 2024-09-30: 
Attendees from DeVC: @Anonymous and @Anonymous: 
Notes:: We are building routines - beauty & personal care quick commerce, and reaching out for our pre-se...'),
(411, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(415, 'AI notes: ### Business Background & Team ### Product Vision ### Target Market ### Strategic Considerations ### Current Status ### Action Items
RM reflections: ++ Love the fact that they want to bootstrap to MVP, test w/ customers and ONLY then consider raising a round ++ Clear Why Now for this AI credit companion type business; we have a thesis ++ in-domain with 10K+ hours, esp for Som who has done 8 YOE @ KreditBee ++ Som’s wife used to lead Perf Marketing @ KreditBee so she will help them with UA ?? I don’t see a clear spike in either of them ?? Couldn’t see Consumer Tech chops ?? Som does NOT have a breakout trajectory; he is 8 YOE @ KreditBee even after IIM Cal; only AVP level ?? Don’t see either founder as a good seller Key Qs for me - What are the refs on Som (given he doesn’t have family who worked at KreditBee; Shobhit’s elder brother roped him into KreditBee) - What is the quality of this team v/s Oolka & GoCredit? should get MPE when they are ready
Conversation 2025-10-03T15:29:00.000+05:30: ')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(416, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '),
(418, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(421, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '),
(422, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(423, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;

