INSERT INTO util.enrichment_staging (company_id, content) VALUES
(9, 'Team: - Co-founder from ISB, recently graduated - Hired VP of Ops from logistics background (Routevisor, Myntra) - 4-5 people in ops team - 4 people in tech team (2 frontend, 2 backend) - 2 dropouts from NIT Jabalpur - Each dark store has 13-14 people
Scoring (Mohit): - Commercial instinct, and highly analytical - IIT / Stanford select + knew all his numbers - Large ambition - to be the health services infrastructure for T2 - Very consumer focused and outside-in - Pivoted and built business model differently based on what consumers are saying **Spiky Score** | Identifiable Spike | 1 | 2 | | Bold & Ambitious | 1 | 1 | | Clear & Insightful Thinker | 1 | 2 | | Relentless & Grit | 1 | 1 | | High rate of growth | 1 | 1 | | Execution excellence | 2 | 2 | | High ownership | 1 | 1 | Analytical - 1 Consumer & product - 1 Strategic - ? Commercial - ? **EO/FMF/Thesis/Price Score: 34/40** - FMF: 7/10 - EO: 9/10 - Thesis: 8/10 - Price (Post Money): 10/10 (Sub 6M)
Founder Profile: - Grew up in Bhopal - Got 100% aid to Stanford - Took a gap year due to Covid - Got into IIT-Roorkee, JEE rank 1400 - Family in construction business - Ran an entity CommsConnect as an NGO - Set up to supply workers to construction companies - Sold for 1.5 million USD (approximately 11 crore INR) - Coding since 9th/10th class - Built first structure of the database with friends - Refused to sell his business to his father - Distributed all the 11 crore to labour workers - Sold to someone who would scale the busin...'),
(22, 'Notes:: **Founders** - [Utkarsh Apoorva](https://www.linkedin.com/in/utkarshapoorva/) - Reshamandi (Co-founder, 1.5 yrs), HandyTrain (Head - Product, 2 yr 9 mos), Autocus (co-founder, 3.5 yrs), Edulabs (co-founder, 2.5 yrs) - [Harshad Saykhedkar](https://www.linkedin.com/in/harshadss/) - PleDu Interactive (Founder, 1 yr), Slack & Astro Tech (Staff Software Egr - 3.5 yrs), OnlineSales.ai (Sr. Data Scientist, 1 yr), Sokrati (Sr. Data Scientist - 4.5 yrs), Vodafone (1 yr) - [Ashwini Prabhu](https://www.linkedin.com/in/ashwini-prabhu-61645283/) - Reshamandi (Sr. PM - 1 yr), HandyTrain (Mgr - C. Success & Product, 5 yrs), Tangentia (Associate - 2yrs) **Eval Views** **Dhairen - Maybe (-) to WM** + Early traction - went live 5 months ago, processing 150 crs a month currently; ~15 lakhs MRR + Outside in - catching the right trend line + Product - Took a quick demo - the process looks like a simple workflow tool, but the interesting part was the nudges based on real time processing. The voice tool ensures that no part of the PD process is missed and doesn''t let the FOS complete the file until then. Also, automatically generates the detailed CAM for further processing. ? Didn''t understand their RTW - no FS/credit background or deep insights on on-ground MSME lending ? FFs with early traction ? Reshamandi background - this makes me pause the most. Initial refs could signal high courage of conviction to leave at that point, but we will need to validate and do deeper refs ? Middling journ...'),
(25, 'Deck insights from Notion AI on 2025-05-07: Based on the attached presentation deck, AeroDome Technologies is developing India''s first Low Earth Orbit (LEO) Position Navigation and Timing (PNT) satellite constellation. **Founders:** - Three IIT Madras graduates: Vibhor Jain, Lokesh Kabdal, and Anurag Patil - former leaders of Avishkar Hyperloop project **Technology & Product:** - Building LEO-based satellite constellation for precise positioning and secure navigation - Developed RTK technology achieving 2-3cm accuracy vs standard GPS''s 3-5m - Created proprietary SDP (Standard Positioning Service Data Processing) algorithm reducing required satellites from 250 to 125 **Market Opportunity:** - Global PNT market potential of $580 billion with 9 billion GNSS devices by 2033 - Key applications: Defense, maritime, automotive, timing services, agriculture, and construction **Development Plan:** - Phase 0 (18 months): Space-borne payload demonstration - Rs 14.2 Cr - Phase 1 (12 months): City coverage with 4-6 satellites - $12M - Phase 2 (15 months): Asia Pacific coverage with 50 satellites - $40-45M - Phase 3 (15 months): Global coverage with 125 satellites - $70-80M **Current Round:** - Raising Rs 14.2 Cr for space-borne demonstration ---
RM notes: 1. Avishkaar Hyperloop > top 3 teams of world 2. Swarm drones - Light shows was the first use case (did 4 drone shows) 3. Both CoFos met at Avishkaar Hyperloop 4. Started working in June 2023 5. GPS has inaccuracy of 3 to 5 meters - Swarm...'),
(26, 'Company Snapshot: **Problem & solution** - Problem: Traditional financial infrastructure favors those with capital and access; knowledge alone does not translate into tradable profit. - Solution: AI-powered global prediction markets that unify fragmented markets, enable on-chain auditable event resolution, and provide liquidity via LMSR and CLOB across assets (sports, elections & macro, weather, etc.). **Ideal customer profile and pricing** - Target customers: Institutions already trading events and individuals who spot trends but lack trading access. - Pricing: Not disclosed. **Status of product & traction** - GTM plan outlined for next 6 months. No live product metrics or traction data provided.
Founders and Key Team: - Nikhil Ramesh -- Markets + Crypto native, Ex Poker Pro. AI Resident at Accel; scaled Paytm Poker to $10M; built DeFi strategies & AI evals. - Manasjoti Saloi -- Ex-VP Product @Gojek. Shipped mobile products for 100M+ users in SE Asia.
Product and Technology: - On-chain prediction markets integrating all assets with crypto rails - Auditable resolution; liquidity via LMSR and CLOB - Unifies fragmented markets; contextual, localized market coverage
Market: - TAM: Sports ~$500B; Elections & Macro ~$200B; Weather ~$25B - Annual volume of $15B for prediction markets - SOM target: capturing 10% of non-US sports market - Competitors: Polymarket, Kalshi, Limitless, Local Sports
Analysis by dev - 2025-11-22: '),
(29, 'De-brief -- Overall: Weak Maybe: - Out of depth on consumer tech growth playbook - No past track of building consumer backwards products - Good mid tier tech co ML leads. Delusional on tech problem depth and quality of builds they have done - Spike = 0 - FM: 2-3 | EO: 3-4 | Thesis: 5? | Price: ? - Next Steps: mark as pass last track for next
Founder Background & Experience: - Aakash (Technical Co-founder) - 14 years experience in machine learning and product companies - Led key ML initiatives at Dream11 during growth phase (2017-2018) - Led personalization at Glance - Most recently headed platform engineering and ML at Myntra - Started in ML in 2010
Past Notable Achievements: - At Dream11: - Built first successful contest generation engine (CGE) - Scaled from 200 to 20-30M personalized contests daily - Implemented solution running on just $1000/year infrastructure - Created what founders claim was "first generative product to make a billion dollars"
Current Startup Details: - Building new search/recommendation product - More visual experience incorporating video/images - Story-based approach to information presentation - Built initial perplexity.ai clone in one day as proof of concept - Early investors include: Victory Velo (Allied.ai exit), MIT ML Professor (Ikigai Labs)
Glance Experience & Learnings: - Led ML team development and culture change - Introduced metrics-focused approach - Developed "valuable sessions" as key metric - Built on-device AI capabilities')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(30, 'Notes:: 1. About him: 1. Father was involved in charter airline business which is how he has contacts 2. Final year at BITS today - 2nd year he built a company and pitched to Titan Capital which is how he got the Titan role - Doing Investment Analyst role at Titan Capital 3. YC W24 admit but CoFo didn''t want to participate 2. 1st company attempt - B2C product to let people access high performance gaming PCs like Mars Computing - $5M in LOI for B2B version of the product, not sure why they stopped - Friend who is doing ML thesis at Harvard 3. 2nd company attempt - E2E GPU rental requires full month booking - Found a gap in spot instances - sold by cloud providers at 85% discount - CoFo conflict again here - ByteSky had 3 TS - Intel Capital, First Round Capital (due to Abhiraj''s contacts) - Had $5M + $3M in order book from educational sector and HKU University 4. Current company - Target is E2E customer base -> AI heavy companies - Multi cloud like software which helps optimize your GPU bill - Using spot instances to bring cost down - Tech co-founder is friend from JEE, works at Fyle
RM reflections:: + Hustle -- got Titan Capital role while at BITS + Right network / ability to build network + Confidence ? Both times there has been co-founder conflict ? Not in domain for AI / not sure would need to speak to co-founder
Intro conversation with Founder 2024-09-17: 
Attendees from DeVC: RM: '),
(33, 'Views from Inuka VC - Gautam & Raj: - I still think he''s raw. I didn''t get the sense he will be able to hire and attract a strong team - I don''t think he''s proved that much on the product/technical stuff, but he will get there - I don''t think there is a clear commercial use case yet for the technology he''s developing - Between feb and now there has been zero movement on the commercial/customer side. For me that''s a major red flag - Comparing to khushi -- who was changing her roadmap weekly based on customer/potential customer input - "build something people want" - which people? and do they want it? - Our main blocker was he is very removed from the customer
Company Snapshot: - Problem: Offshore naval visibility is currently limited, expensive, and labor-intensive - Solution: Perpetual aerial surveillance using dynamic-soaring airplanes at under $1 per hour
Product and Technology: - Core concept: airplanes performing dynamic soaring to harvest energy from wind, enabling continuous flight - Specs: 6m wingspan, 15kg MTOW; propellers act as wind turbines - Target endurance: ~417 days of continuous flight - Target operating cost < $1/hr
Risks: - Technical: Robust DS autonomy across variable wind fields, reliability, adverse-weather ops - Operational: Airspace approvals, deconfliction, spectrum, C2, maintenance at scale - Economics and GTM: Several figures are placeholders; no concrete customers
Network views 2025-12-10: '),
(34, 'Use Cases & Differentiation: - Built specifically for regulated financial institutions - Handles both structured and unstructured data access - Dev-first approach rather than SaaS solution ---
Heads up note 2025-08-19: DeVC is investing $100K as part of a YC SAFE round - Community Top Up with Anand Lalwani (US Collective Member | CoFo of Cardinal Robotics) **Founders** 1. Srikar D - 4 YOE @ Goldman Sachs (Marcus), UT Austin CS 2018. Instrumental in developing infra to launch the Goldman Sachs Card w/ Apple 2. Kevan D - CMU CS 2019, Ex CoFo & CTO @ Compute AI (acquired by Terizza Inc). Built compute engine 5x faster than EMR Spark **Round details** - Uncapped YC SAFE note - Anand Lalwani angel: $20,000 - YC S25 fund: $375K - Standard YC terms (MFN clause, 0% discount, Uncapped) - Previous round: $125K for 7% from YC **Investment risks** 1. PLG approach may not work for sensitive RBAC use cases in enterprise 2. Crowded market with OSS players (Casbin, Oso, Permify) and incumbents (WorkOS, Okta) 3. Shipping velocity flagged ---
Product Overview: - Alter is building a security gateway for AI agents and knowledge bases - Recently accepted to YC (batch started 1.5 weeks ago) - Founded by ex-Goldman Sachs employee - Focus on regulated industries, particularly finance
Aakash (Maybe):: - Good pedigree and smart guy - Depth is there but limited. Has faced AI in enterprise problem at Goldman - Super early - Single interaction would place him in middle 50 of YC (intuition), could be top ...'),
(40, 'Notes:: Brief conversation with Arjun Juneja (ex Google Ad Sales | ex AVP @ BharatPe | total ~9 YOE) 1. **Left BharatPe ~2 months ago** - Thought it would be a one year stint - Deferred his UMich MBA twice; 3rd time decided to NOT pursue 2. **Exploring credit card rewards optimization space** - He has ~9 cards (HDFC Infinia, Axis, AMEX Plat etc) - Believes there is also an opportunity to work on debit cards rewards optimization since there are ~900M debit cards outstanding - Ideating some form of AI layer for transaction level spend optimization 3. **Competitive landscape** - Aware of SaveSage (DeVC evaluated / RM is an investor) and Magnify Club (RM is tracking) - Discussed Curve from the UK
Intro conversation with Founder on 2024-09-05: 
Attendees from DeVC: RM: '),
(42, 'RM notes: 1. About Arya - Dad was CS grad who worked at MSFT in USA - Fascination with Space and Robots - BITS Hyderabad - led Cubesat team 2. Pixxel - 2 year stint - Software he wrote runs 6 satellites - Left because felt pigeonholed into narrow Software work 3. What now? - Curious about Propulsion systems (Ion thrusters / fusion based thrusters) - Committed 12 months to work with BITS HYD CubeSat senior at Godela (YC X25)
From Rahul 2025-11-26: - Top talent at Pixxel - Had to be replaced by 3 people - Part of Pixxel''s Software team - one of the few who would know how the entire system works
Conversation with Arya 2025-11-30: Net: Nothing for DeVC/Z47 here - he has NOT started up; joined his BITS HYD senior Abhijit who is the CoFo @ Godela (YC X25). Was quite underwhelmed by the overall conversation in context of the glowing ref which Effy provided. However, he is definitely a thoughtful FF and made the right decision for himself to join another team versus startup by self.
RM reflections - IF this were FF x Concept, I would be WM from DeVC as well | NOT the best Pixxel alumni FF I''ve met | Too raw & inexperienced to startup: ++ Thoughtful & outside in; recognized that Space/Defense requires either network OR technical edge ++ H&H is clear: Landed up in Space Club; then Dhruva Space and into Pixxel ?? NOT at the same level as Pradyumna Bang and Effy ?? Underwhelming conversation given how glowing Effy''s ref is')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;

