INSERT INTO util.enrichment_staging (company_id, content) VALUES
(132, 'Notes from @Aakash: Overall: Maybe+ EO: 6-7 | FMF: 5-6 | Thesis: 6 | Price: ? Spikey: ~1 (need refs) - Thesis is a compelling one + have built early momentum - Can see a strong growth mindset and they are building in a deep familiarity space - Would likely have to be a services + product play ideally – for which they seem like an incomplete team - Not SaaS native Next Steps: Push them on GTM thinking with Kuldeep, Rohit and other SaaS folks. Notes Asad Abrar - Drizz.dev Born in Patna Raised by Mother , father used to work in Saudi (used to come once in 2 years) IT KGP 5 years | Order of merit in technology | graduated in 2014 After college got off campus placement @ Baker Hughes 1 year worked at Baker Hughes Then started a company similar to go mechanic Why did you start then ? Had nothing to lose. Was seeing value creation in startups from batch mates Manager at baker hughes was co-founder at the first venture | total 4 co-fos “ You seem like tech inclined how come an ops heavy biz?” That time tech enabled cos we’re all around. Tech to streamlines believer Ran for 1.5 years there | got to monhly 10L GMV Realised problem was two fold : - Old cars for repair used to turn up ..only post service centre cycle was done for the owner - Repair at doorstep was becoming a challenge in an asset light model - Logisitcs of getting parts to doorstep became a challenge - Pivoted to b2b | they were partners for Ola - Realised its a very linear scaling biz and momentum was low - There were a...'),
(134, 'Evaluation Plan + Key Questions to answer: 1. What does the company do? 1. Do we (DeVC/Z47) have a thesis on this space? 1. What are the top 3 questions to diligence? 1. Who has piped this company to us? What are their views? 1. What do refs say about the founder? 1. What''s the DeVC team views? 1. What are the Collective signals? 1. Why is this company likely to be special? 1. Who can help? Experts / Venture Partners? 1. Deal dynamics? Potential deal to do? ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: '),
(135, 'Notes:: Overall – Maybe + for DeVC Spikey = 0.5 (closer to 1) 30/40 - FMF 7 | EO 7 | Thesis 8 | Price 8 Overall, + Quite thoughtful on how to build (shows up in product formulation, pricing focus, investment in manufacturing) + Surrounding himself with people (2 food scientists in house / ITC factory folks are helping to scale up production / Devendra Chawla, Nature’s Basket head is working closely and has invested) + Clear articulation on what he wants to focus on and learning from other food brands + Thoughtful about fund raise (doesn’t want to raise too much as not needed, wants to get thoughtful partners on board) ? Didn’t speak to him about scale of ambition of journey over next few years Next Steps : Connect him to Revant (to discuss team building for brand business) and Chakri (on online and offline distribution / category building learnings). Also, get feedback and BRCs at the right time. DeVC’s edge here will be getting the right people to help him think through the larger questions. - - Fund Raise - Has closed 12cr at 75cr pre with Prath. Had a TS (?) from Fireside for 16cr but couldn’t get his angels out (he has ~25 through Mumbai angels + RUV on cap table). Stopped taking calls from other VCs for now – in Due D - Total raised before this 5.5cr in ’22 and 3cr in ’23 (Java doubling down) - 3 weeks since Due D started, thinks should be done with SHA as well by end October Business + Grown 0.5cr, 5, 15 last year and this year targeting 25-30 + L3M 1.6 (J), 1.8 (J), 3....'),
(138, '(1) Founders and Key Team: Abhinav Kankane – Title not disclosed [Inference] Career: INSEAD, IIT-Madras; ex-Zalando, P&G, UC Focus: Business, GTM, Partnerships Functional responsibility: GTM & Partnerships Equity & commitment: Not disclosed Relevance: Strong cross-border business and partnerships background relevant for scaling GTM. Siddharth Shrivastava – Title not disclosed [Inference] Career: IIT-Madras; ex-WinZO, Sprinklr Focus: Product, Content, Pedagogy Functional responsibility: Product, content, pedagogy Equity & commitment: Not disclosed Relevance: Deep product and pedagogy experience fits Eduro’s core learning app. Kavish Shah – Title not disclosed [Inference] Career: MS @ UPenn, IIT-Madras; ex-Vanguard Focus: Technology & Innovation Functional responsibility: Tech leadership Equity & commitment: Not disclosed Relevance: Technical rigor and innovation background supportive for AI-driven product. Adwait Sudersan – Title not disclosed [Inference] Career: IIT-Delhi; ex-WinZO; ex-founder Focus: Technology & Innovation Functional responsibility: Technology & Innovation Equity & commitment: Not disclosed Relevance: Founder-level technical background and prior startup experience.
(2) Product and Technology: Product stage: [Inference] Not disclosed Core functionality & tech stack: Interactive Learning Canvas with curriculum-aligned generative components; Central Memory Layer for pace, mastery, misconceptions; Motivational Loops for daily engagement; AI components (LLMs), TT...'),
(144, 'Inbound via Chandrika (Quivly) - 2026-02-28: Source: Chandrika Maheshwari (Quivly) forwarded to Cash on Feb 28, 2026. Chandrika says she''s been "super impressed with the product" - Quivly is a design partner. PITCH (from Shagun''s email Feb 27): "Engram is the brand brain for fast-scaling AI companies. As a company grows, brand and marketing context (how you position, how you respond to the market, what sounds like you) becomes impossible to transfer at scale. The faster you grow, the worse it gets. Engram makes brand intelligence institutional so it compounds as you scale instead of fragmenting. The system learns your taste, your context, and your decision-making, and turns it into something your whole team can use." STATUS: Live with design partners and a few early paying customers, all Seed-to-Series A AI companies. Planning to raise a pre-seed soon. FOUNDERS: 1. Shagun Ohri (CEO) - shagun@engramhq.com - 2x founder, 14+ years in brand and marketing - Most recently Director of Marketing at Together Fund working with Series A AI companies - Rahul''s concern: "background of hopping around quite a bit" - suggested checking with Subham at Together Fund 2. Siddhant Singh (CTO) - siddhant@engramhq.com - Previously built a generative media platform for enterprise (Volkswagen, J&J) - Scaled Flipkart Ads to $1B ARR - PRIOR Z47 HISTORY: Affinity shows email exchanges and meeting in Feb 2024 (last email: Feb 20, last event: Feb 8). Personal email: siddhant0204@gmail.com OPEN ITEMS: - Ca...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;