INSERT INTO util.enrichment_staging (company_id, content) VALUES
(267, 'Key Connections & Follow-ups: - Maven already in discussions with Razorpay Ventures for partnership and potential strategic investment - DeVC offered to help facilitate Razorpay connection given their close relationship as early investor - Portfolio companies identified for customer validation: Voicebit (restaurants) and Confilo (bank front office) Notion AI is transcribing this meeting. That''s the PII warning, I am gonna transcribe the meeting so I can share it with Akash. Awesome. I''ll give you a quick background about me, about the firm, and then would love to hear from your end. I was an entrepreneur like you, your YC Winter 26, I was YC Winter 21, different era, that was a Zepto batch, that was a COVID batch, that was 500 companies in one batch twice a year versus where you guys are now. And I sold my business, it was doing software for insurance brokers, very boring, pre-AI. I built a company in the era where you had to hire engineers to get code. Today you can burn through millions of tokens and get the same code built 10x faster and better. We''re three partners in the fund. Akash is an angel in Superbase, which is another super successful YC company. He also built and sold India''s largest real estate portal back when you and I were literally in our diapers. Second partner, Rajat, is the first investor in Razorpay, which is the stripe for India. Again, one of IC''s big hits in India as well. From the fund we''ve invested in several YC companies over the last couple of ba...'),
(268, 'Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---'),
(269, 'Financial Update — Mar 2026 (Audit): - Last Fiscal Revenue: $0 - Current Monthly Revenue: $0 - Jan 2026 Cash Balance: $760,000 - Jan 2026 Monthly Net Burn: $19,000'),
(270, 'Notes:: 1. Thesis 1. OYO for Pharma, software for pharma & clinics 1. Transition from local chemist to modern medicine affilate store 1. B2b pharma shop digitization 1. Won''t charge for the software -> SaaS doesn''t work in India, we are a service provider 1. Quick Comm using local chemist inventory 1. He believes that acute is the only demand source (?) 1. Also was getting stock up orders 1. Customer has high WTP for acute (₹200) 1. Chronic is subscription or bulk buying 1. His journey 1. 2018 -> clinic, private clinic, preference given by front office staff. Thought of solving via software 1. Cold DM to Subhash to get an internship at Dukaan 1. Felt Dukaan is the right place to build a business or product 1. Pawan from OnArrival offered a paid sabbatical to try building 1. Got 20 orders posting stories on IG 1. Thought demand was only in Tier 1 cities 1. Market learnings 1. Chief Of Staff at Blinkit said they are struggling 1. Blinkit will try to onboard a partner for pharma 1. PharmEasy and 1mg doing 80% prescription meds via channel 1. i.e. local chemists are anyways getting bulk of the acute use-case volume 1. Apollo 24x7 is also doing prescription meds delivery 1. Schedule X or Schedule N medicines have strict regulations 1. Swiggy only focused on OTC meds and not prescription meds 1. Story 1. Business 1. Supply side 1. Young owner < 50 yrs works, QR placed at the store, 1. Channi Hittmat in Jammu, 3 partner stores amongst 13 stores in the area 1. 5 weeks of pilot 1. ₹20...'),
(271, '**TK - Overall View: WM**: **Spikey: 1 (for Ajit); 0.5 (Akshay)** Spike Needed for the biz: consumer/product + High IQ + Both are good combo of right and left brain thinker + customer backward > citing example like building cities for people + Positive BRCs on both ?? Not up to date on numbers – rough calculating it; if running so many experiments numbers should be on top of mind to know which one is working ?? Slow on iteration and shipping – no increase in DAU/MAU over the last 3 months ?? Running too many experiments too early on small base ?? Lack of depth – Akshay asking random ques on AI hardware? <u>**Next Steps**</u> - Closely Track the team and metrics (DAU/MAU/engagement/retention) - No significant change as of now over the last three months. <u>**Detailed Meeting Notes (16.10.25)**</u> **Founder Background** - **Ajit Pol** - Grew up in an Air Force family in Pune; now married into a Marwari family. - Worked at Flipkart – across search and Insuretech biz (2018-21) - Moved to Leap, a full-stack edtech startup enabling students to study abroad - handling exam prep, university partnerships, visa, and financial assistance. - Was first PM at Leap, scaling the counselling business that contributed ~70 % of total revenue, with ARPU of ~$2,500 per student and company-level revenue of ₹300–400 Cr across India, the U.S., and the U.K. - Joined Buystar (founded by ex-manager Sriram) as Head of Product – Majority of rev from cricket but it’s highly seasonal so built Cricket Trum...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;