INSERT INTO util.enrichment_staging (company_id, content) VALUES
(65, 'Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---'),
(66, '(1) Founders and Key Team: Name – Title Noah Martins — CEO One-line career summary; track record: Growth @ GameRamp; previously cofounder/CEO @ Fijit; GM @ Loop AI; Producer @ Gajabuja Games Functional responsibility: overall leadership, growth, and product direction Equity % / commitment / location: not disclosed Relevance: prior startup and growth leadership; experience across gaming and AI-adjacent teams Kartik Karia — COO One-line career summary; track record: Prev: cofounder/CGO @ Fijit Functional responsibility: operations, go-to-market execution Equity % / commitment / location: not disclosed Relevance: previous founder/CGO experience relevant to GTM and operations Mohit Kumar — CTO One-line career summary; track record: Senior SDE at Fijit, Streak AI; Previously built 30+ games at Fijit and scaled to 100K+ users Functional responsibility: technology development and architecture; AI/ingestion pipeline Equity % / commitment / location: not disclosed Relevance: strong technical background with gaming/AI-scale experience
Company Snapshot: Problem & solution Reading lacks daily feedback; progress is invisible, hurting motivation. Existing tools track books or time, not the habit. Bookmarkk positions as the “Strava for books” with AI-driven quizzes, social features, and an identity/insights layer to turn reading into a measurable habit. Ideal customer profile and pricing Pricing tested: $5 per month (24 paid users in initial test). Target segments implied: high‑intent reade...'),
(67, 'Boost <> @Aakash / @Sudipto / @Naviya Singh 2025-07-09: Please find below the views and meeting notes from our chat with the Founders of Boost Robotics. Next steps here include making them meet key folks from the DeVC collective, forming a WhatsApp group for the same shortly. Vault links to the following: - Pitch Deck - Research Papers Views Dada (Strong Maybe): Spiky: 1 + Continue to like the founders - spiky, YC archetype. +/? Very early in the product and revenue journey and will have their learning curve on hiring and GTM. + However, spiky enough for us to do a small cheque through DeVC and continue to track Cash (Maybe+): Spiky: 0.5 + Like the guys, good pedigree + Smart GTM strategy: wedge into real-world need (data centers), expand from there. + Will surround them with DeVC collective folks. ? Not in the bay area, going to be hard for them to raise. ? Unsure of how to benchmark and calibrate. NS (Strong Maybe): Spiky: 1 EF/FF: FF Founder Archetype: 8 FMF: 9 Thesis: 8 + Articulate, pedigreed (both founders), clear FMF. + Aligns with internal thesis of robots (non AGVs and AMRs) for specialized use cases. + Already have LOIs and pilot partners. + In the DeVC alley, will help us enter the CMU network. + Met Hans for the first time- liked him, clear tech spike. + Clear articulation of problem and product roadmap. + Both founders are customer backwards- rarity in robotics founders building in the US. Meeting Notes'),
(68, 'Notes:: AS: NS (Strong Maybe) Spiky: 0.5 (Tech spike) EF/FF: FF Founder Archetype: 7 FMF: 8 Thesis: 7 + Strong pedigreed team with domain experience. + Already have ongoing paid pilots with Airbus, Safran, Ministry of Heavy Industries. ? Yash is scientist archetype, not articulate but possesses clear tech spike. ? How big of a market is this? Path to $100 M ARR is unclear. Meeting Notes Team - Abhishek Chopra (CEO and Co-Founder) - Rut Lineswala (Co-founder) - Team size: ~40 people Problem - Current simulation software extremely slow & computationally expensive - Engineers forced to choose between: - Example: Aircraft simulations take 6 months on 250,000 parallel computers - Algorithms haven’t changed since 1970s - GPUs underutilized (only 30-35% capability used in engine simulations) Product - BQFi: Backend engine for simulation software - Uses quantum-inspired algorithms on existing hardware - Key features: - Technical differentiator: Uses stochastic math & quantum-inspired gates - Can find global minima faster than genetic algorithms Go-to-market - Initial focus: Aerospace & Defense sector - GTM Strategy: Conference presentations, keynotes, booth setups - Position as backend engine for existing simulation software - Target customers: Airbus, Israel Aerospace, Air Force Research Lab - Future expansion planned into biotech, pharma, finance Traction - Major pilot with Airbus: - Pipeline includes: Funding - Currently raising seed round: - Series A metrics set:'),
(70, 'Meeting Notes — Feb 20, 2026: 1. Reco product has taken off 2. Do follow up meeting next week 3. Feedback from CD and ID - why are they using it 4. Payment orchestrator isn''t clicking')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;