INSERT INTO util.enrichment_staging (company_id, content) VALUES
(399, 'Heads up note from @Aakash 2025-04-04T19:22:00.000+05:30: Sharing a brief note for our $50K investment in [Revspot’s](https://www.revspot.ai/) pre-seed round, amounting to 0.75% ownership. This is round where paperwork is closing now, we had committed in Sept 2024. The co has since scaled to $300K ARR, even hitting $80K ACVs with Indian customers. This is a community cheque underwriting with RK, Chirag, Aakrit and Miten The co is raising $1.4 Mn at $6.6 M post money. Round is being co-led by Titan and Infoedge ventures This was brought to us by RK and product was strongly vouched for with a strong reference on Darshan. We are restricting this to a community cheque even with multiple folks from the collective giving a strong signal, given lack of FMF on SaaS GTM and very India first build out **About Co** - Revspot is building AI powered pre-sales agents and marketing intelligence tools for the non-SaaS world where MQL generation is key to growth (vis Financial services, Real Estate, O2O platforms) - They have early traction with Livspace, Dezerv, Meragi, Stabl Money and multiple other cos and are adding logos at a fast clip **Founding Team** 1. [Darshan Subhash](https://www.linkedin.com/in/darshansubash/?originalSubdomain=in) - Was leading customer success in 6Sense in his most recent stint. Got there via slintel acquisition (where he was the chief of stagff) - Was earlier leading sales strategy at Livspace and had a short stint at Unacademy - IIM Indore 2014 1. [Varun Garg](...'),
(400, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '),
(401, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '),
(404, 'Heads Up Note 2025-11-25T09:18:00.000+05:30: Hi team, Sharing the heads-up note for our investment in WorkAtoms which is a text to workflow builder for non-engineering knowledge work (e.g. content writing, social media monitoring, responding to inbound requests etc) - initial focus is on Marketing & GTM teams DeVC is investing $50K as part of a $2M SAFE round @ $10M post money valuation *Note: This is a founder-first investment (based on IIT-B signals) + Community Top Up to *[*Nikhil*](https://www.linkedin.com/in/nikhil-abraham)* from Cloud Chef (new DeVC Collective member in US). Hence, we have sized the cheque accordingly & will do more work in coming months as they tighten their GTM and sharpen their product (hopefully for a single vertical) * **Founders** 1. [Dhruv Jaglan](https://www.linkedin.com/in/dhruv-jaglan/) - CEO & Founder 1. IIT Bombay CS 2020 1. 2.5 YOE @ BabbleBots AI - was promoted from Founding Engineer to Co-Founder 1. 1.5 YOE @ LinkedIn India 1. From Cash:* ++ soft refs from IIT-B network on Dhruv : “Rockstar and would get anything done”, “Machau ladka hai.. keeps picking new things and building”* 1. [Georgi Boby](https://www.linkedin.com/in/georgi-boby-07b081161/) - COO & Co-Founder 1. 6.5 YOR @ Cloudchef as Founding Engineer 1. IIT Bombay 2019 1. From Cash: *++ Table thumping ref on Georgi from Nikhil @ Cloud Chef and Ashray @ Rephrase AI* **Investing Process** 1. We were introduced to Dhruv Jaglan (main founder) via Activate AI (Aakrit & Pratyush) 1. Act...'),
(405, 'Attendees:: | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;