INSERT INTO util.enrichment_staging (company_id, content) VALUES
(180, 'Heads up note written by @Rahul Mathur 2025-04-12T14:33:00.000+05:30: Hi team, Sharing the heads-up note for our investment in [Grexa](https://grexa.ai/). This is an AI marketing app for SMBs in India to automate their entire marketing effort — SEO, SEM, performance & social ads to drive hyperlocal footfall and Sales. DeVC is investing ₹43 Lakhs ($50K) as part of a wider ₹15 crore round led Utsam Somani’s iSeed This is a a Community Top Up w/ Utsav Somani | BRCs pending (ex Testbook CoFo’s) **Founders** 1. [Ashutosh Kumar](https://www.linkedin.com/in/ashutosh-kumar6/?originalSubdomain=in) (ex CoFo and CEO — Testbook) 1. IIT-B ‘07 to ‘12 1. [Arpit Oswal](https://in.linkedin.com/in/arpit-oswal) (ex CPO — Testbook) 1. IIT-B ‘07 to ‘12 1. [Ayush Varshney](https://www.linkedin.com/in/ayushvarshney/?originalSubdomain=in) (ex CTO — Testbook) 1. IIT Kanpur ‘10 to ‘14 1. [Narendra Agrawal](https://www.linkedin.com/in/narendraagrawal7?original_referer=https%3A%2F%2Fwww.google.com%2F&originalSubdomain=in) (ex CoFo & CMO — Testbook) 1. IIT-B ‘07 to ‘12 **Investing Process** 1. Rajat sourced this investment opportunity & shared with Aakash 1. Aakash: “Having known the founders for long, hard to go bigger at entry. Lots of risks that seem like will repeat. “ 1. Aakash did a 1PE with the founders followed by a full team meeting 1. Decision was: “Community cheque is no brainer - trendline strong | founders are known (ex Testbook) ” 1. Utsav committed to lead the round hence decision was to d...'),
(183, 'Key Metrics (as of March 2026): - **Total raised:** ~$12M (Pre-seed $1.4M + Seed $6M + Zuora strategic $5M) - **Cash in bank:** ~$3.5–3.8M - **ARR:** Not stated explicitly; ACV ~$60–120K per customer - **Pipeline:** $12M total; run rate $2.5M, adding ~$0.3M new pipe/month (grown from ~$0.5M to $2.5M in 9 months) - **Direct sales conversion:** ~18% - **Sales team:** 4 AEs (2 enterprise @ $1M quota, 2 mid-market @ $600–650K quota) - Partner
Founder: **Arvind Gopalan** — CEO & Co-founder. Also spoken with Pranay (likely co-founder or early team). Building a partner-led GTM through ERP/billing platform resellers.
Company Overview: Growfin is an AR (Accounts Receivable) automation platform focused on order-to-cash workflows — specifically cash application/reconciliation, collections management, and invoice presentment. Sits in the finance operations layer of the CFO stack, not core accounting/GL. Key integrations with NetSuite and Zuora (Zora), through which it also has a strategic investment.'),
(188, 'Founders Background (from Matrix internal notes) - 2026-02-10: HARSHIT MADAN: IIT KGP (''08-''12), BA at Opera Solutions (12-14), PM at Housing.com (14-15), Co-founder SME financing startup (15-17), Meesho (''17-''22) VP Product to VP & GM Supply Growth. Bob: "One of the sharpest and most structured problem solvers at Meesho. Very calm, composed. Built a very good team. Trusted hand for Vidit." Aakash (Housing days): "Great executor and operator, but not sure if he can do iterative 0-1 stuff in the dark." PRATEEK AGARWAL: IIT KGP (''08-''13), Field Engineer Schlumberger, PM Housing.com, Co-Founder Bite Club (''14-''16) raised ~$1M, Meesho (''16-''22) one of first employees when <10 people. Bob: "Very sharp and high IQ. Very iterative and great for 0-1." Aakash: "Cut out to be an entrepreneur from day 1. Loves to get his hands dirty." Dada ranking: "Prateek > UK > Harshit. Same category as Shobhit (Vegrow), Ankush (DSLR)."
**Nitin Views**: - Overall: The combination of Harshit and Prateek building in the consumer domain is very exciting. They’ve both seen Meesho’s 0-1, 1-10 & 10-100 journeys closely and were instrumental in it. They were always sharp, but their Meesho stints have made them more polished and also taught them team building. They also always wanted to start-up (both had started-up in the past) - Harshit - I’ve worked with Harshit on a couple of short 2-3 week pieces - One of the sharpest and most structured problem solvers at Meesho (was very problem-first) - Very calm, co...'),
(189, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): '),
(190, 'Prep 2025-09-03T09:06:00.000+05:30: [File: download](https://prod-files-secure.s3.us-west-2.amazonaws.com/b21975bb-aebf-48e3-8c44-1573c4404129/ac6d370f-0d1d-45ed-b9dc-8d1a76100cfb/Semel_Shah_Haystack_OnePager.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAZI2LB466Z4A6JIV6%2F20260320%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20260320T102927Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGgaCXVzLXdlc3QtMiJGMEQCIGftJyDy4JSgt75dFJdnDE%2F%2BeAC%2FO2wBJkvT%2FQ6cCswPAiBDR2INkZIi1iz744cF3nD7DySgkWgE7mUsaCiMikBjGyr%2FAwgxEAAaDDYzNzQyMzE4MzgwNSIMD9%2BhMHa8F%2Bm7b0L6KtwDb2I0V3HgxiKKwtxYU56TuH2%2BeMlW2Kx58Ull7z5FZom85fLEeVLHba121J0og2No0r3aKZ1MNc23Pyv5%2FGZjX3kBtUx1w9w9pQj6HfHNPvEnN6LmIdbM1fww0paURRv1X9jjVaMR6eW8yNwoamxY9kQ1Zmni3ML6HTZAllI5FAaY4Bz8oiNbd5uMAR8%2F17M1BMcFF2FYTlC3wZ%2Bq0pVESLs1pcq%2BxetJVMlP7IykymIVe3iF6q7m868%2BysLcn40C6o%2BQQZ3BlwWd18xKJ3vT2q%2B555OulXT%2Fh%2BH6ITFKqTNvxRFB4lAEhWJSDDsAHtsGlPFWC3x%2FD3JysKhgVjRQyYnjyVJrSN1QpRG1yOLNUgU01ZQYs3bwKOVSIjuOss2Wg1XbNblmf6GVqkKPA7oJJ2Klfw6GObroRMSOfMa0UPTsWTURcOHuCNWpFdhsuhpU76SooHMyMFfM1TkKoZj6TJiZGz4cAcFahYU9%2F0FH0VksJ%2BGtgA1WuxkQ7UDnUcfvJo5mttw5Vl8sdeM9lw264pIzyfg8O2%2Bavj7%2FxlF4s1RAq%2FpvMcJ0Hl1KckFPSI7SeC0f8kG05ngcXXBluO%2Fm80Xq9hyNuFJl5oK7DcyzAyR%2B8XVIL59dF3BjtoYwpvzzzQY6pgFQpTWUetuyme3z1Y9LOt2uc0swBhdh23zYo%2Bs%2BVbEroz0e7BPm87G500WtzgstmGe%2F6TOLe5BMK9hoVLabv%2FbgGMQLmbQgsGiTWZYYKyMRqEAHM%2Bvye6Z4ghTLXwSGptGogFletfTnEh8fhBTMn7fmvz00TO5UEGjpqRSwv0yx3GHaqW%2B9%...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;