INSERT INTO util.enrichment_staging (company_id, content) VALUES
(71, 'Ref from Priyans (CoFo): Context: Priyans was a CoFo of the Breethr founders in their prev company ActiveBuildings Notes: 1. Priyans is also involved in Breethr - more on back office 2. Priyans also runs an EV business - he is more focused there 3. Priyans and Abhinav met on BITS Goa campus in 2010 - filed patents together, research together and both decided to do something in hardware together 4. Pivoted to air quality in 2014 5. ActiveBuilding had a F&F round 6. Manav was hired around COVID (2020) when they were doing a Swiggy project - Manav had an inside sales background and was boots on ground in BLR 7. Abhinav and him are hands on founders 8. Peak was 30 employees in 3 cities 9. Peak revenue was ₹7 crore - ₹1 crore PAT 10. Sensor doesn''t make as much money as solutions 11. Abhinav was great at B2B deals eg Reliance NetMeds 12. NetMeds warehouse - temperature and humidity monitoring 13. Abhinav used to crack deal and then Priyans would do implementation 14. Still has positive relationship with Abhinav 15. Pandemic era - got $50L from DOD for Kavach grant 16. PAPR - Priyans and Abhinav built this solution, but by then PPE was in the vogue, army wanted something more sturdier 17. PAPR journey gave them an idea of how solutions are built 18. Started as distributors of air purifiers 19. Simple product is easy, sexy product needs capex investment 20. Closed a ₹2 crore order during pandemic for MI team (for ActiveBuilding) 21. Call center incident - Disprin stock was still wit...'),
(72, 'Evaluation Plan + Key Questions to answer: 1. What does the company do? 1. Do we (DeVC/Z47) have a thesis on this space? 1. What are the top 3 questions to diligence? 1. Who has piped this company to us? What are their views? 1. What do refs say about the founder? 1. What''s the DeVC team views? 1. What are the Collective signals? 1. Why is this company likely to be special? 1. Who can help? Experts / Venture Partners? 1. Deal dynamics? Potential deal to do? ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: '),
(73, 'Attendees: Full Z47 team: Briskpe Views RC -Weak Maybe Archetype 3/4 +Liked Indu a little more than Aloke and Sanjay, FMF- Below 5 + More than expected amount of work on regulatory piece and customers. + Ahead in terms of reg thinking and execution compared to others. ? Bold choice on the segment → Feels like they’ve underestimated the challenges of the segment they are going after though. Not sure they’re fully cognizant of digital strengths of the other players / are thinking along those lines. Avi – Very easy pass Low Archetype, IFs + Aloke has some conviction. ? FMF is 0, Not my archetype → Indu is just words not content - Struggling to give a clincher reason why to pass , “there’s a few things such as the teams background that makes you pause they say some of the right things but it never really ties together.” ?Complete IFs stumbling from one insight to another. ? Not sure if the refs on Sanjay are high quality. (Would not give any weight to Gaurav Chopra’s ref either) → Navin might have a positive view but he likes these kind of founding team. ? Sanjay is someone who has never compounded in life, and everything he has done post HDFC (Venture Studio) is scattered → This journey also seems scattered. VV-Weak maybe Insight / spike missing / edge missing. Depth in biz model / product etc Sanjay more thoughtful than I gave him credit for Team, Talent, Cost/frugality, pivot at the right time, bend at the right time 7 days digital journey vs offline; more digital thinking tha...'),
(75, 'RM notes: Next steps - BRC w/ DoWhile AI CoFo from RM + 2PE with Kinzy & Bunny with RA & Mohit Notes 1. Naman Jain - Elder brother 1. Nishchal Jain - Younger brother 1. Startup journey 1. DoWhile AI 1. Tinkering together post SPC and LossFunk 1. Buny 1. Why pendant? 1. Started to spend too much time on hardware - “juice is in AI” 1. How did walkie talkie come about? 1. Demo video 1. Cash Q: Why not go full fictional characters like EMoMee? 1. Cash Q: Hardware - why not make it a analogue kid mobile? 1. What are you hiring for? 1. Parent mobile 1. Initial market (?) 1. Comps: 1. Can offer personalized learning storybooks | learning activities → personalized 1. Customers 1. Learning from Osmo founder - keep founder healthy & high 1. $150 retail price for hardware 1. Technology
RM Notes: 1. Shubham knows Deepak 1. Knows Aniket Kamte from Nexus VP 1. Left Google because he wanted to take some risk 1. Joined DoWhile AI when it was called Collective AI 1. v/s othr companies 1. Mandalin is his current co 1. Convinction / motivation lacking at the firm - didn’t have as many wins 1. Going to meet them in SF 1. Come a long way - motivated now versus before 1. He feels choice of market isn’t something he would do 1. They need a CTO/ VPEng
Cash reflections -  Weak Maybe. Community cheque at best.: 1. Pure inside out FFs with no clear consumer spike 1. Have built and landed on a much better form factor (hardware and software) in the entire audio ai toy for kids than all other teams we hav...'),
(78, 'RM reflections - dead center Maybe | 0.5% cheque = $150K IFF we go ahead w/ this: ++ Pedigreed team given 4 YOE @ Loom - worked closely w/ founders on the Loom AI launch ++ Thesis (MUCH more than Cash & KB): For me, this it Limitless 1.0 i.e. agent running in the background learning everything about you ++ Design principle struck a deep chord with me: Voice to be used for editing the “first draft” created by the Caddy Agent ++ Good set of learnings captured by them - Enterprise plan beyond billing consolidation & SSO ++ Do sense they have GTM chops; not just Product builders - but yet to be proven out / demonstrated ?? Worried that they will repeat the same Loom mistakes i.e. build a horizontal OS level product which will struggle to capture Enterprise revenue ?? Worried that their landing wedge is dictation - didn’t hear anything about actions - therefore, Wispr Flow is the competition ?? Underestimating the amount of configuration & customization needed to make even dictation work Mid Feb ‘26 launch Key Qs - business 1. Why choose to go after this problem? 1. Why standalone app & not OS level solution? 1. What do “actions” require v/s Wispr which is transcribing today
RM’s suggestion = 0.5% ownership i.e. $150K cheque 2025-12-12T22:39:00.000+05:30: BRC w/ Joe (Loom CoFo) took me from Maybe to SM - sticking to the 0.5% ownership target i.e. $150K cheque size Why $150K? - Connor (founder we are underwriting) is Spiky = 1 - rapid career trajectory from intern to Eng to PM to G...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;