INSERT INTO util.enrichment_staging (company_id, content) VALUES
(154, '1PE meeting w/ @Dhairen Tohliani 2026-02-19: Surfacing Finlead AI, they are building a commission management solution for insurers. Essentially bringing in dynamic commission structures to help insurers manage EOM better. Founders are spikey FFs and this is a clear pain point basis our insurance infra work in the past. Looking to raise $300-400k now and would recommend a 2PE from DeVC considering the founders, trendline and early momentum. Have pinged someone from PhonePe insurance for a BRC on the founder, will add the deck here as well. Views Dhairen – Maybe+, if refs check out and there is real substance behind what they’re conveying then clear SM ++ Entrepreneurial and hacky guys with early track record of achievement ++ H&H - was advising startups, got in touch with IRDAI for pushing current product ++ Sales motion - GoDigit (signed), Royal Sundaram (POC), Care - not easy to get insurers on board, so early especially ++ Insights and maturity for the age was surprising - in touch with regulators, ONDC, have foresight - deferred insurance implications ++ Thesis - EOM pressure is real - managing commissions better is addressing a clear pain point ?? Product is a thin wedge; they will need to keep iterating to expand ACVs - could get capped quickly on this current one if insurers try to move in-house ?? Positioning v/s reality – need to do refs here Meeting Notes Company Overview & Problem Statement - FinLead AI building B2B insurance commission management solutions - Founde...'),
(157, 'Deck 2026-03-20T05:42:00.000+05:30: --- [File: attachment](https://prod-files-secure.s3.us-west-2.amazonaws.com/b21975bb-aebf-48e3-8c44-1573c4404129/388099bb-2c83-4cd4-b004-d67ee5130d0a/Firi.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAZI2LB466UA77UFQM%2F20260320%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20260320T103111Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGgaCXVzLXdlc3QtMiJGMEQCIAjR1%2FmOn94RxOu80GGrr8o161UpwC5DLvufUXyZ1E9QAiAgon%2Fcwopz%2BBQXS%2F8p95tqvyBpjToki0i7SiqvDHBOASr%2FAwgxEAAaDDYzNzQyMzE4MzgwNSIMo7zSX7qyUUCIgwTaKtwDZ7o3rhjnk%2BBfsK9bVab0hcIc3xEHV0Nk6TIpgxf22VkirHjhmCEngZOJxLcPK2K8rgdfV8dmj1FGpkfUJVgGJ6ovf6xWzfiS8j44MT5QrV09LtKGyPJDSVvGXwVtKediVJfQbtuoBSjQjOBzLail%2BtX%2BBzp4uQQ1K9N5Y%2Bap2r0%2FBWHWJqSoJ6JLV6TX7L7U3M5Q81xdT%2BE8s5%2FgKPYg%2BFFkXChHGlQSvy8m9c%2F2NcNrrDnBi87SBvLRRTFaG3ZL4slKFxd0rxLLWiaQA8nvMl2ytrxbihSHUXgukc1P1eFwtD%2B8Aohe%2FN1iWcmE4eN32zP4hXAac7%2BO5Bm17Jlr2CfamrvzVmJWDeiGKPXZXF4akfklutSCTtn4m0xDPjtE7q7uQVNldloKYhCOTbav%2FUk7uM9Mt8z%2FaFPD%2BWoazA3LivchZQyBb7cCyfsTd9nrrxdGOAxCUSMAC9rtg0kvq3Bj0n%2BKWT5tH%2FhsVj8xR4TeA2OIrK3dFl11BsBwo0DnCYfNmg8wa7Zv5rjsneyaqVX%2FqTT7qJs4QF1WJMblpnkTsoyLpyXaM8Meeb%2BSSBEDHl3TaVAjgsaSU8u8nFHgO0kCJXj3%2BfbCJtWsCeR2R3xntdrZlPEq60%2FvH9wwyvzzzQY6pgHMq4qzj0t3WVLhnEuLigoYScn0FjIjhKDhgfm5o1ANAgt1IPS%2FM01Mo0GyxrqttfTnYCs%2FM0Bqw0kQk542nxr6tra7QPBS8DqjFCkHtKA%2B%2Bb585NSGRb0jwTTPuJI%2B0DwEpVeq2VLqLXwkL3SSGy7LfNDdJm6ZrK5LCUlxT7N0LAXFA3sq9PKxNrw1GVZJJQ358%2...'),
(159, 'Financial Update — Mar 2026 (Audit): - 2025 Revenue: ~$30,000 - Current Monthly Revenue: ~$5,000 - Jan 2026 Cash Balance: $90,000 - Monthly Burn (current): $20,000 - Burn expected to reduce further — targeting near-zero in 2-3 months'),
(160, 'From @Anonymous: Agreed with views below – spoke to her today. Spikey – 0 (just hasn’t operated before and surprising lack of ambition for what she has done so far) EO 5| FMF 5| Thesis 5| Price 8 - Speaks well – has a good consultant background and work - Is going deep on product, consumer insights and brands ? Isn’t aiming for a big outcome ? Wants only patient capital ? Is building a team very luxury – will potentially build a new age Kama with a small TG ? Didn’t hear enough depth on what the market is, what consumers are saying, GTM Next – Pass and track for next [Table] [Table]
Convo 2024-09-17T17:59:00.000+05:30 with @Anonymous and @Anonymous: Rachna Bahadur: - Was at Bain and could only work with companies in small capacities - Looking to move deeper into value chain and couldnt find much - Byjus chased me for 6+ months and made an offer to head the international business that I couldnt refuse - Had an opportunity to co-found 82East - couldnt get over the line on the set-up they were offering (good decision in hindside) -  Was one of the most exciting things I refused from all the offers that were coming to me Building a beauty brand focused on women in menopause and menopause segment. Product - Part of the identification was personal and rest research - Delhi & Bombay pincodes - women aged 40-45 and 50-55 to understand whats changing - We speak to women between these age groups. Its more homogenous across different geos - Care is no longer a luxury. Its customer backw...'),
(161, 'Rm notes — Reflections - FF | Concept | Spiky = 0.5 - should validate from BRCs |: ++ Clarity of thought, good articulation around problem space ++ Hard fought learnings from 1st stint - NOT chasing VC or Twitter hype, wants to validate ++ Taking on hard technical problems e.g. OEMs blocking deep links etc ++ Outside in; has studied other players in the market ++ Self taught software engineer ?? Slightly worried this is a missionary profile and NOT a business builder profile ?? Space has been DOA for a long time
Rm notes: 1. Was thinking about doing Master’s 1. Bain 1. Got back into coding after Bain - YouTube video learnings 1. Browser extension 1. Thoughts on device 1. platform agnostic or OEM agnostic | on device layer 1. Wants to challenge → https://www.opal.so/ 1. Building a second brain → Agent on phone 1. Wants to do a Reddit or offline launch to build convection before going to SPC et
Ref from Aniket (Bain) via Ashwin 2025-09-25T15:15:00.000+05:30: 1. Quirky 1. Thinks differently from others 1. Don’t have solid POV on whether he is great at building or a good product guy 1. Generally positive on him, smart guy
prep notes 2025-09-24T21:57:00.000+05:30: 1. Introduced via AeroDome founders who are from IIT Madras ecosystem 1. About Rohith 1. Prev. company was called Flowstate - https://www.flowstate.cc/ 1. New company 1. My notes
Meeting 2025-09-25T12:07:00.000+05:30: 
Ai notes: ')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;