INSERT INTO util.enrichment_staging (company_id, content) VALUES
(506, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(510, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '),
(511, 'Heads up note 2026-01-23T16:35:00.000+05:30: Hi team, Sharing the heads-up note for our investment in [VoiceBit](https://www.voicebit.ai/) This is an AI voice agent for restaurant phone ordering automation that handles end-to-end operations including payments, loyalty, web ordering, and delivery - building towards becoming the new age system of record for direct ordering ("Zoca for Restaurants") DeVC is investing $200K as part of a ~$2M round @ $10M post money valuation led by 1984 VC We were introduced to the founders by [Samit Kalra](https://www.linkedin.com/in/samit-kalra-a6179365) (Partner at 1984 VC) This is a Core Cheque & our 2nd investment with 1984 VC (our first deal with them was Orange Slice - YC S25) **Founders** 1. [**Hitesh Kenjale**](https://www.linkedin.com/in/hiteshkenjale)** - CEO** 1. Berkeley MBA 1. 2x venture-backed founder (DesiHangover - grassroot footwear maker in India) 1. Reference check with [Abha Agrawal](https://www.linkedin.com/in/abha-agrawal-72439654) (ex-CoFo @ Desi Hangover): 1. *++ Used to be entrepreneurial always. Trying lot of side hustles. * 1. *++ Stand out superpower: dependable holistically to solve problems. * 1. *++ Passionate about numbers and moves fast. ++ Process oriented and focused. * 1. *?? Weakness: Should disconnect himself from people problem solving that aren''t critical. Tries to solve for too much for everyone. * 1. *?? When span of work expands, prioritization he needs to mature more than where he is. * 1. *Would you ba...'),
(513, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(514, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
READ ME: 
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: ')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;