INSERT INTO util.enrichment_staging (company_id, content) VALUES
(30, 'Notes:: 1. About him: 1. Father was involved in charter airline business which is how he has contacts 2. Final year at BITS today - 2nd year he built a company and pitched to Titan Capital which is how he got the Titan role - Doing Investment Analyst role at Titan Capital 3. YC W24 admit but CoFo didn''t want to participate 2. 1st company attempt - B2C product to let people access high performance gaming PCs like Mars Computing - $5M in LOI for B2B version of the product, not sure why they stopped - Friend who is doing ML thesis at Harvard 3. 2nd company attempt - E2E GPU rental requires full month booking - Found a gap in spot instances - sold by cloud providers at 85% discount - CoFo conflict again here - ByteSky had 3 TS - Intel Capital, First Round Capital (due to Abhiraj''s contacts) - Had $5M + $3M in order book from educational sector and HKU University 4. Current company - Target is E2E customer base -> AI heavy companies - Multi cloud like software which helps optimize your GPU bill - Using spot instances to bring cost down - Tech co-founder is friend from JEE, works at Fyle
RM reflections:: + Hustle -- got Titan Capital role while at BITS + Right network / ability to build network + Confidence ? Both times there has been co-founder conflict ? Not in domain for AI / not sure would need to speak to co-founder
Intro conversation with Founder 2024-09-17: 
Attendees from DeVC: RM: '),
(33, 'Views from Inuka VC - Gautam & Raj: - I still think he''s raw. I didn''t get the sense he will be able to hire and attract a strong team - I don''t think he''s proved that much on the product/technical stuff, but he will get there - I don''t think there is a clear commercial use case yet for the technology he''s developing - Between feb and now there has been zero movement on the commercial/customer side. For me that''s a major red flag - Comparing to khushi -- who was changing her roadmap weekly based on customer/potential customer input - "build something people want" - which people? and do they want it? - Our main blocker was he is very removed from the customer
Company Snapshot: - Problem: Offshore naval visibility is currently limited, expensive, and labor-intensive - Solution: Perpetual aerial surveillance using dynamic-soaring airplanes at under $1 per hour
Product and Technology: - Core concept: airplanes performing dynamic soaring to harvest energy from wind, enabling continuous flight - Specs: 6m wingspan, 15kg MTOW; propellers act as wind turbines - Target endurance: ~417 days of continuous flight - Target operating cost < $1/hr
Risks: - Technical: Robust DS autonomy across variable wind fields, reliability, adverse-weather ops - Operational: Airspace approvals, deconfliction, spectrum, C2, maintenance at scale - Economics and GTM: Several figures are placeholders; no concrete customers
Network views 2025-12-10: '),
(34, 'Use Cases & Differentiation: - Built specifically for regulated financial institutions - Handles both structured and unstructured data access - Dev-first approach rather than SaaS solution ---
Heads up note 2025-08-19: DeVC is investing $100K as part of a YC SAFE round - Community Top Up with Anand Lalwani (US Collective Member | CoFo of Cardinal Robotics) **Founders** 1. Srikar D - 4 YOE @ Goldman Sachs (Marcus), UT Austin CS 2018. Instrumental in developing infra to launch the Goldman Sachs Card w/ Apple 2. Kevan D - CMU CS 2019, Ex CoFo & CTO @ Compute AI (acquired by Terizza Inc). Built compute engine 5x faster than EMR Spark **Round details** - Uncapped YC SAFE note - Anand Lalwani angel: $20,000 - YC S25 fund: $375K - Standard YC terms (MFN clause, 0% discount, Uncapped) - Previous round: $125K for 7% from YC **Investment risks** 1. PLG approach may not work for sensitive RBAC use cases in enterprise 2. Crowded market with OSS players (Casbin, Oso, Permify) and incumbents (WorkOS, Okta) 3. Shipping velocity flagged ---
Product Overview: - Alter is building a security gateway for AI agents and knowledge bases - Recently accepted to YC (batch started 1.5 weeks ago) - Founded by ex-Goldman Sachs employee - Focus on regulated industries, particularly finance
Aakash (Maybe):: - Good pedigree and smart guy - Depth is there but limited. Has faced AI in enterprise problem at Goldman - Super early - Single interaction would place him in middle 50 of YC (intuition), could be top ...'),
(40, 'Notes:: Brief conversation with Arjun Juneja (ex Google Ad Sales | ex AVP @ BharatPe | total ~9 YOE) 1. **Left BharatPe ~2 months ago** - Thought it would be a one year stint - Deferred his UMich MBA twice; 3rd time decided to NOT pursue 2. **Exploring credit card rewards optimization space** - He has ~9 cards (HDFC Infinia, Axis, AMEX Plat etc) - Believes there is also an opportunity to work on debit cards rewards optimization since there are ~900M debit cards outstanding - Ideating some form of AI layer for transaction level spend optimization 3. **Competitive landscape** - Aware of SaveSage (DeVC evaluated / RM is an investor) and Magnify Club (RM is tracking) - Discussed Curve from the UK
Intro conversation with Founder on 2024-09-05: 
Attendees from DeVC: RM: '),
(42, 'RM notes: 1. About Arya - Dad was CS grad who worked at MSFT in USA - Fascination with Space and Robots - BITS Hyderabad - led Cubesat team 2. Pixxel - 2 year stint - Software he wrote runs 6 satellites - Left because felt pigeonholed into narrow Software work 3. What now? - Curious about Propulsion systems (Ion thrusters / fusion based thrusters) - Committed 12 months to work with BITS HYD CubeSat senior at Godela (YC X25)
From Rahul 2025-11-26: - Top talent at Pixxel - Had to be replaced by 3 people - Part of Pixxel''s Software team - one of the few who would know how the entire system works
Conversation with Arya 2025-11-30: Net: Nothing for DeVC/Z47 here - he has NOT started up; joined his BITS HYD senior Abhijit who is the CoFo @ Godela (YC X25). Was quite underwhelmed by the overall conversation in context of the glowing ref which Effy provided. However, he is definitely a thoughtful FF and made the right decision for himself to join another team versus startup by self.
RM reflections - IF this were FF x Concept, I would be WM from DeVC as well | NOT the best Pixxel alumni FF I''ve met | Too raw & inexperienced to startup: ++ Thoughtful & outside in; recognized that Space/Defense requires either network OR technical edge ++ H&H is clear: Landed up in Space Club; then Dhruva Space and into Pixxel ?? NOT at the same level as Pradyumna Bang and Effy ?? Underwhelming conversation given how glowing Effy''s ref is')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;