INSERT INTO util.enrichment_staging (company_id, content) VALUES
(303, 'Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---'),
(304, 'Action Items: - [ ] Z47/DVC to consult with Confido about their experience with Nixo - [ ] Z47/DVC to provide investment decision within 48-72 hours - [ ] Akash to introduce Sidhu/Chetan to Priya - [ ] Priya to connect with investors via WhatsApp A good evening. How should we do the intro folks? There are three of us today. Should I just introduce the fund and then everyone give one two lines about themselves? This one is also end of call commit or we have time? Don''t have time but not necessarily end of call. Okay. Because given Anand is deeply plugged in so we can be patient. Okay. No, not yet. No, no, I''m just checking. Oh. Hello Priya. Hi. Hi, very nice to meet you guys. Nice to meet you. Is Preeti also joining? No, she unfortunately can''t make it. She has some other important work to attend to, but I''ll be here. Got it, got it. No, so quick context setting here. Akash Rajat Rao will quickly share a bit about us. We are Z47 and DVC, earlier we were known as Matrix Partners India. We invest out of two funds, one is a venture fund, which is more post-seed-seed to Series B. And DVC is a pre-seed-seed fund, where we partner with founders super early in their journey. Pertaining to what you are building, this is a space we''re pretty deeply calibrated in. At one end for customer success and CESPM, we have a company called Rocket Lane, which we had seeded and then let the A and the B in, which was together with ABC. That was from the venture fund. And outside of that in the depl...'),
(305, 'Next Steps from Rahul: - Introductions to consumer brand founders (Mohit Sadani and others) who successfully used mom influencer GTM channel - Market work and customer chats over next 48 hours - Follow-up discussion with Rajat to determine what''s needed for next meeting - Overall positive reaction: found the concept "refreshingly unique" compared to typical consumer brand pitches He was my junior at IIT Gansur. So that''s when I got in touch with him, met Raghav, Atulia and have been at Judo for the last 5 years. So you know about that part of me. Right. So now, sort of decided to move on. Yeah. Because Preksha has been at this Nomado for I think close to six, eight months now and we did some pilot and there was some conviction to sort of start this up. Yeah. But maybe, Priyaksha, you can talk about your background. So now a very similar profile on paper, very different skills. in practice but yes Engineering background, then worked at CS for a couple of years, then IMB, MBA in ''17. Then I joined McKinsey. I was with McKinsey for about a couple of years And then I, after that I also wanted to at that point I joined OYO. They had launched Mountania for upscale hotels and they wanted somebody to create a full operations team for that and how would everything look like. I joined work with Vivek Sinha for a brief period in India and then moved to a role in UK because Rishabh had decided to shift to UK so I also decided to shift along with him. And so they created a role for me whe...'),
(311, 'Go-to-Market Strategy: - Focus on national jurisdiction enterprises (80% of litigation) - Target PSUs and government bodies - Key differentiators: - Speed of filing - Digital experience - Cost advantage - 12-month team growth target: 20 lawyers (5 specialists, 15 process), 20 annotators, 5 tech team
Company Background & Team: - Founded in 2024 by 25-year-old founder from Bangalore - Strong legal connections through family: - Mother is expert in setting up law schools - Co-founder Pratik runs own law firm for 5 years - Third co-founder Takshu (currently in USA) - Initial pivot from education tech to legal tech in Jan 2024
Product & Technology: - AI-powered legal drafting system with human-in-loop verification - Key features: - Translation services ($1/page, 7000 pages/month from Karnataka High Court) - Real-time dashboard for enterprise clients - 14-day timeline to add new legal specializations - 12 annotator/proofreaders (non-lawyers) for quality control - Demo showed automated legal document drafting system
Nyayanidhi Founder <> @Aakash 2025-07-08: Overall: Strong Maybe EO: 4-5 | FMF: 6-7 | Thesis: 7 | Archetype: 5-6 | Spikey: 1 ++ Super spikey founder. Fastracked credits at NIT ++ Hacker tinkerer profile and always been shipping and building ++ very organic build out (as per his narrative) towards the AI first legal play ++ Hustle first execution to get to right platforms, open doors ++ Partenred with right domain co-fos ++ Strongly vouched for by Sidu and Nischhay (jar) ??...'),
(317, 'RM reflections —SM to try to add to his existing $2.1M led by 1984 VC: ++ Outside In; had studied ReTool, Lovable etc ++ Good seller despite being extremely technical ++ H&H is obvious: Built company in high school etc ++ Better than Lovable - can edit in UI, can pin up Neon DB w/o user doing any work ?? Lots of FF traits - had done shallow outside in work (i.e. public sources); didn’t dig into own YC network
RM action items: 1. Get introduction to 1984 Ventures via Olive 1. Send Olive the following: 1. CRUX intro 1. Companies we spoke about
RM Notes:: 1. Moved from Iran 1. Funzie  Brex for non-profits 1. Social consumer splitwise type priduct 1. Got into YC with that idea 1. Interested in code gen 1. Decided to build a lovable competitor 1. “Lovable for Business” is what he is building 1. Integrate with DB 1. Showed demo 1. Could live edit in the GUI - edits flowed into code 1.
Prep notes 2025-07-28T09:06:00.000+05:30: 1. Objective: 1. Get introduced to 1984 Ventures 1. Learn more about ZFellows (?) 1. Raised from Gustav YC and 1984 Ventures 1. Was it Samit Kalra (?) 1. Marc Persival 1. 1. ReTool in an AI first world 1. Prompt to dashboard 1. Thesis is 🎯 - even in an AI first world, users want Dashboards 1. Internal tool building 1. Whenever I hear things like Supabase etc - I don’t know what to do 1. Lovable integration with Supabase was a painful experience for me 1. Everyone told me I shouldn’t use Lovable created files because they are vulnerable 1. I really liked the co...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;