INSERT INTO util.enrichment_staging (company_id, content) VALUES
(232, 'Update shared 2025-10-06T16:32:00.000+05:30: [Video](https://prod-files-secure.s3.us-west-2.amazonaws.com/b21975bb-aebf-48e3-8c44-1573c4404129/2cee6ec5-35b4-468f-9f28-9d2a04bfa1cb/Klaire_GTM_version_%28v4%29.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAZI2LB466524BVX4L%2F20260320%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20260320T103520Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGgaCXVzLXdlc3QtMiJHMEUCIEKdWpQmNtIHwm%2Br9LDJ080sF0GCiZMZl3Y%2FTJ3QJS3RAiEAzp08S0MJmNPu2kU3RWq8HnAeB7JTQ909vV8gQ6gGc9oq%2FwMIMRAAGgw2Mzc0MjMxODM4MDUiDJb9OeNHS3e8B1oN%2ByrcA0MPYpTFfGjGb6BoqjAvn0XZ7FxgSXuuhh8HIzXJ%2B2NdBhluBD02IpIQbi5DQW1SMS4uvx1nVOIpb6ZL9Jj%2FHhKl9hg4FR4IhIyTGofE4SSxF3JQOMNs5nAcRa8nf53JbCQIqF%2FXMukrpUxdEau0m78tW%2BVq1FKJ9IU%2FNZI9ybhOwoI3ivyphDWhgyWvqvbc5BPgcg0KFvDXd1O9Oy2aYzOa3HvDIcyCMvbRZ1sGgBiVv3IAVg1C3Bj9hqzBPSnQAOtXMACApOyjXykpel1wzkIK411U15iior9Pj7LO0NcJU2sIoGhJBeEiL66gwhDIsRXStTRXqyYT%2FLyHYWfn6Dr4euVogk9ofgbG3gDe2rfNBVZ3%2FChK3qrbOmlzFPpdronZiUqSTJL5Y6jkdIV34iarO%2BHvaY3s6ljGvyg%2BCyjJGZPRgvjFI0MVKe8ty4ksT4NuPOsrILqhBrmf5JM3m0OeHAzZaoiu4CCacSTbZz4KYU3bPuQS53Rk2vISYE2IGt602j7mrY3SVuhpy%2BIMANCBQWLWJRO%2FPlO8jdBOkc3t1oWlzV5EmwzNpe2cO0%2FZKemfDGuif17rh4f9aIYKB8%2F6D0bM8HiTZ%2BjlffbaHxdnzgufCqgEGqPNgUZhMID9880GOqUBWkba8YUhI9DbkoWgHuRU0pIwteiA2CW2jqxiPmtHFNJc%2F01qtmiWZaVritZpvFWJ1ZyZGf6RQRHbS18bLqkHmmX8%2Bx1HhM4EuYgBYMTh3wl6PHudPvHt4RW%2FscG9FpBiugRwAXsnIYfc%2FUlQTCUssMJveUtSLv22zDcBPsls4r56sHftwA86M74QXchbl1BCOvX6...'),
(233, 'Product & Technology Differentiation: - Built tracking system for brand inventory movement - Focus on top-selling styles identified through inventory tracking - Limited curation strategy (targeting 6-7K styles vs marketplace model) - Developing Tinder-like UI for better preference understanding - Emphasis on quick delivery to reduce return rates (currently seeing significantly lower returns than industry average of 35-40%)
Notes:: Pivoted to Qcom for Fashion. Meeting funds this week (Elevation tomo/day after) Connected with me 1m back to discuss the idea to understand failure points. Met again today – to discuss fund raise strategies. Launched 10days back – progress below. No deck – 10 days of ops. **CV: M+ | **Think we should get more eyes on the guy - if nothing then get one more point on eval line. <u>Avi let me know if I can set this up – in the meantime will do ex-employee refs.</u> This may not be the right round given he has some execution to prove - <u>but DeVC should lean in imo - better founder than Slikk</u> **Spikey = 1 (***I’ve always liked him – overall rate him higher than Ackshay at Slikk***); Thesis: 7 | TAM: 8** ++ Marketing / GTM – the team has always had an edge ++ Best product/tech team among the 9-10 QcomXfashion players ++ Interesting thoughts on “discovery and assortment” ++ Hackers – “figuring hacks to understand top sellers for brands (so that we are not a liquidation channel, but a pareto channel)” – Interesting POV ++ Speed of iteration ++ been fru...'),
(235, 'Notes:: <u>**AP: Maybe to Maybe -ve (Apr-23, to update latest views)**</u> + Entrepreneurial +/? EO-like profile, but an engineering track guy + Track record at Flipkart, Anil G angel investing in his last venture + Rapid progress from last time. Incorporated the co., going all-in on bank partnerships + Thesis: Credit over UPI rails ? Unclear capability as a solo Fintech founder ? Philosophical/anecdotal over sharp and succinct consumer insights ? Anil''s ref - may/may not invest in this venture ? Unclear right to win vs. existing incumbents/new vertical players who will launch this ? Raise doesn''t make sense <u>**Dhairen - Maybe**</u> Zpikey - close to 0.5 (product) + Commercial, resourceful - *claims that he has cracked the same terms as OneCard for secured CC. Using FK network to get bottom commercials from vendors* + Numerate, analytical - *thoughts around commerce as rewards for retention* + Followership - *entire team from WeTradeApp has stuck around, are these T1 folks?* + Thesis - positive on credit on UPI - *credit penetration driver in UPI native user base + higher wallet share of spends* ?+ FS business building? Though comes across as a quick learner ? Good start but Qs on scaling up? GTM for scale up seemed weak too, will need to double click <u>**Founder**</u> [Prashant Kumar](https://www.linkedin.com/in/prashantkumar6/) - Founder and CEO @ WeTradeApp (1.25 yrs), Head of Engg. @ Protonn (10 mo), Head of Engg. @ Flipkart Wholesale (7.75 yrs), Syncapse (1.25 yrs), P...'),
(238, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): '),
(240, 'Action Items: - [ ] Founder to speak with Nitin at 6:30pm today - [ ] Investors to debrief and circle back with decision - [ ] Connect founder with more founders for peer support - [ ] New hire (ex-Droom) to start January 19th and develop used car frameworks - [ ] Begin state expansion applications for next year (Delhi/Bombay) I was studying for finals as well. And then I was in Europe for three to four years actually. So I was doing my under-tatuation from there, from University of St. Gallen. So it''s like a small town at the northern side of Switzerland, very close to the German borders. It has like 80,000 people population. So either you will find very, very old people or like very young folks. Nobody in the middle, you know. And so I was specializing in finance and more on the transaction side is what I was learning over there. in the transaction team itself. It''s called TAS actually over there. And I was working along with the German team. German team would be the backend team. But the Swiss team was obviously the frontend team. So a lot of traditional clients over there understood that learning German as a skill set is very important for me. But nonetheless, all my team members were very kind enough to give me all the English speaking clients. But I was actually doing German learning as well over there. And simultaneously actually when I entered Europe, the dangle had just hit in. So there was a lot of displacement from Gulf countries of immigrants. So we started doing ...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;