INSERT INTO util.enrichment_staging (company_id, content) VALUES
(336, 'Meeting with founders at GFF sidelines 2024-08-29T18:28:00.000+05:30: Attendees: @Anonymous and @Rahul Mathur 1. Avi 1. Darbangha 1. IIT-D for college ; electrical engineering 1. Wanted to do PhD 1. Joined Booz out of college 1. 2013 → 1st company; e-comm boom 1. 2015 got acquired by CarDekho for PriceDekho 1. COS → 8 to 9 month stint 1. Built auto lending business at CarDekho → worked with a bunch of banks 1. Good understanding of FinOps 1. Credence → 2nd company 1. 2017 → 2023 1. Initially only domestic lending 1. Then COVID hit → so began lending to study abroad market 1. NBFC license got returned due to Mauritius money 1. 2nd buyout offer from Shriram Finance 1. Lending book was subsumed into Travel India 1. Top 3 learnings → asked by @Anonymous 1. Find problem statements which let you work on them for 10-15 years 1. Arbitrage opportunities exist for a reason; focus on fundamental problems 1. Other co-fo 1. From J&K → Studied there till 10th standard 1. BTech Delhi 1. Interest in cyber & data security 1. Joined IIIT Delhi as a Privacy Researcher 1. Masters in Data Security from France 1. Learned about GDPR 1. 1st company 1. Disecto 1. Got Govt grants 1. Homomorphic encryption for data sharing 1. Blume & Omidyar keen to invest 1. Spent 2 years 1. India’s top law firm 1. Built their privacy vertical 1. Didn’t enjoy doing consulting 1. How do Co-Fo’s know each other? 1. Met online on LinkedIn 1. Privacy focus was of interest to both 1. Why this? 1. Younger generation cares 1...'),
(337, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '),
(338, 'Product review 2026-01-16T13:57:00.000+05:30: - Same space as the PPM from Khatabook - family finance manager - Decent build - but seems like FF building out of domain - lots of simple misses e.g. doesn’t have a PW flow for docs onboarding etc [Child Page: PeaceVault Product Review]
Quick ref from Ravish (COO @ Khatabook) 2026-01-16T13:30:00.000+05:30: 1. He''s pretty good 1. I think he''ll do great as a founder. Don''t really have specific points. He led a few initiatives at our end and did well.'),
(339, 'De-brief (if any): From @Aakash Overall: Maybe for DeVC Spikey: 0.5 | EF/FF: 4-5 | Archetype: 7-8 | Thesis: 5 - + playing to large latent demand market and strong trendline; timing risk is real though and they are aware that they are playing to a market with maturing problem awareness but limited solution awareness as of today - + Continue to like Shashank and probably one of the most thoughtful product thinkers with a business bent; product sense is strong but not top 1%, makes up for it with learning and continuous iteration - + Real need gap for high intent and solution aware users. Eg: preventive first users who do not wish to go to a hospital for prevention or are underserved by standard clinical practioners - Will get their cold start and early single centre break even with non scalable GTM ; going to struggle in the scale up - They have good thoughts on testing based GTM wedge for scale, but that is going to be a risk one would have to take - Lack of FMF can be substituted somewhat by surrounding with folks like Rohit MA if he comes in via Peer (Shashank is super keen to have him lead) Would surely be a community cheque for us, already qualified given marshot plus other angels would step in. Hard to see this as a candidate to dial up our entry cheque given lack of FMF and no experience with consumer GTM. Getting to scalable GTM post early PMF is an additional challenge they’ll have to tackle post first centre success. Next steps: They are looking to raise $1.5 (lead) +...'),
(341, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;