INSERT INTO util.enrichment_staging (company_id, content) VALUES
(371, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: '),
(374, 'Ashwin''s Internal Notes - PASS (FYI since EF) - 2026-02-27: Pass for me. CTO who''s surrounded himself with two other technical cofounders and unproven on GTM. Refs middling. POSITIVES: - EF backed, sold a company, CTO @ Simpl - Strong technical mind - Thoughtful and pragmatic - Workspot scaled to $20M but flatlined after - Puneet mostly looked after tech, limited business focus - Well networked in US, some good angel investments CONCERNS: - Thesis: AI to improve engineering documentation (maintain docs across codebase, enable agents to understand via context). Winner-take-all play with Entire.io and other strong competitors already. Wouldn''t bet on this team to take them on. - Customer backward-ness low - has strong opinions, will build good initial product but might stay blind to customer feedback on iterating it - GTM muscle missing - his cofounders are two principal engineers. Should have hired complementary skills. - Refs okayish --- REFERENCE 1: Ashwini, VP @ Simpl (reported to him) POSITIVES: - Strong at hustling and getting things done (sets up war rooms, pushes integrations through) - Good problem solver in execution-heavy situations - Very effective networker; uses personal network (Flipkart, Swiggy, etc.) to unlock deals and integrations - Can evolve/learn new areas (picked up GTM basics over ~8 months, went on pitches like Payne 3 to Myntra) - Defends his team well and is an acceptable stakeholder manager - Handles peer-level, technical/business counterparts well (...'),
(375, 'Analysis by dev - 2026-01-06: ### Company Snapshot Problem & solution AI agents generate hundreds of unmanaged local Python runtimes on developers’ laptops outside Git, CI, and cloud security tools, creating an endpoint visibility gap in regulated enterprises. PyEnvManager secures these shadow runtimes with instant SBOMs, fleet-wide vulns search in about 2 seconds, and enterprise-grade runtime visibility across endpoints. Ideal customer profile and pricing Target: AI-heavy teams, security-forward enterprises, and regulated industries; bottom-up adoption driving authoritative runtime telemetry. Market signals indicate broad enterprise footprint with multi‑endpoint Python environments; pricing modeled per developer and per enterprise tier (CORE per-developer; PREMIUM Enterprise with governance features). Unit economics cited: 98% gross margin due to client-side processing and a DB-less architecture. Status of product & traction highlight Early beta with tangible usage: 48 organic users across 7+ countries; 2 paid customers. Product emphasizes fleet visibility, SBOMs, rapid global searches, air-gap native deployment, and one-interface management for Python environments. (1) Founders and Key Team Name – Title Siddarth Pai – Co-founder Simhadri Govindappa – Co-founder One-line career summaries; track records Siddarth: previously at JPMC, Walmart, and GE Healthcare. Simhadri: security at scale at AWS (AppSec Guardian) and Uber (SSE); Apache Hive committer. Functional responsibility...'),
(377, 'Company Snapshot: Problem & solution Qila Games pursues a social-first hybrid-casual model aimed at delivering premium games with high LTVs in India, MENA, and LATAM. Hybrid-casual combines simple mechanics with the monetisation depth of mid-core IAP-heavy games, targeting the region’s rising willingness to pay and microtransactions. First IP Ludo Hero is positioned to hybrid-casualise a globally familiar mechanic (Ludo) to drive retention and monetisation at scale. Ideal customer profile and pricing Target markets: India, MENA, LATAM. Pricing: IAP-heavy monetisation; exact pricing model not disclosed. Status of product & traction highlight Ludo Hero live on Android and iOS; game trailer available; early traction indicates strong retention and engagement; on track to reach $7M ARR by 2027.
(2) Product and Technology: Product stage Live on Android and iOS (Ludo Hero). Core functionality & tech stack Not disclosed. Unique IP Not disclosed beyond leveraging a globally familiar IP (Ludo) for hybrid-casualisation. Key differentiators vs substitutes Hybrid-casual approach combines familiar mechanics with live-ops, progression, and meta-economies to improve retention and monetisation over ad-heavy, single-session titles. Implementation complexity / switching costs Not disclosed.
(5) Business Model and GTM: Pricing model IAP-heavy monetisation. Distribution channels & partnerships Not disclosed. Sales cycle length & decision maker Not disclosed. Customer retention strategy Live-ops, ...'),
(378, 'Deck insights from Notion AI on 2025-04-30T18:01:00.000+05:30: Based on the investor deck attachment, [Qodex.ai](http://qodex.ai/) is an AI-powered API testing and documentation platform. Here are the key points: - **Product:** AI-powered platform for software testing with vertical AI agents, aiming to reduce testing time by half by 2025 and costs by one-third - **Traction:** Currently serving 2 enterprise and 12+ mid-market companies, with 50+ active projects - **Team:** - Siddhant Mohan (CEO): 3x founder, [ex-Builder.ai](http://ex-builder.ai/) Head of Engineering - Shreya Srivastava (COO): 3x founder with startup experience - Strong technical team with members from AWS, eBay, and other tech companies - **Market Opportunity:** $16B annual market size, targeting the $30B automation testing market that''s growing at 18% - **Vision:** Aims to become the customizable AI Assistant for Developers by 2030 ---
Qodex AIBackground & Experience: - Founded Review Maniacs in college - review aggregation platform for online shopping - Joined [Builder.ai](http://builder.ai/) as founding engineer, rose to CTO/CPO through Series B - Led team of ~150 tech/product people across India, US - Built Builder Cloud - infrastructure optimization product - Achieved significant enterprise customer adoption (Flipkart, Myntra)
Notes:: Overall: WMB for Z47 given FF. Would rate him on 0.5 spiky for tech. US GTM is a clear gap and he hits the $1M target with US MM and enterprise cos then this is interesting ...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;