INSERT INTO util.enrichment_staging (company_id, content) VALUES
(289, 'Investor Feedback & Decision: - **Z47''s assessment**: - Very high bar for QSR investments - Founders "not bad but nothing exceptional" - Category not sufficiently differentiated (every market has street food) - Prefer non-linear business models over linear store-by-store expansion - 10% EBITDA at ₹20 lakh stores "not great" - economics typically degrade as businesses scale - First few outlets often have better economics that aren''t replicable at scale - Network-wide EBITDA likely to settle at 8-10% - **Key investor concerns**: - Things get difficult at 10-20 outlet scale due to competition, food consistency issues, or location choices - 15% monthly attrition means 150 people leaving monthly at 100-store scale - Important metrics to track: customer feedback, NPS, repeat rates, same-store sales growth - **Investment decision**: Pass from Z47, but Titan Fund is leading the round And both moving and targeting the new target with the update in Bangalore for the Ramadhin survey for today. We all built that up for the update in Bangalore now. Then we also started downloads to operate your veg pan to find out Yes, so about me, I am a commerce graduate turned chef. Before I met Tanay at Mesa, I spent roughly two and a half years working in the kitchen. I started my culinary training in France and then ended up spending two years working in Sweden in a Michelin star restaurant and also in the south of France. So I worked across different formats, Michelin star hotels. In the meanwhile,...'),
(290, 'Action Items: - [ ] Circle back regarding next steps - [ ] Follow up on establishing team in Bay Area Now within a pre-construction, the task can be looked into four different phases. The first one is feasibility, second scoping and costing, third scheduling and procurement and finally construction readiness. After construction readiness, it goes into the project manager who does the execution through the handover. But a project manager usually deals with one project at any point in time. Now compared to that, a pre-con manager... It is not an execution, they deal with multiple projects. Now, the idea for the preform manager, as I was saying, they have to bring in more business. So, the more the number of projects they are able to deal with in parallel, the better it is for them. So, that''s where their North Star metric lies. Now, they had all of these four phases. We land in scoping and costing, that''s the second phase. It will expand to others, but the buyer is the same for all of the phases, because it is the pre-con manager. Now in scoping and costing, primarily what a pre-con manager does is scope sheets, bid levelling and price benchmarking. While I am saying this, I am talking from the perspective of a general contractor, all of it. Pre-con teams exist with owners, developers, subcontractors across the ecosystem, but we work with only general contractors to begin with. Now, when the general contractor receives or the pre-con manager receives all the bid packages from t...'),
(291, 'AS: Weak Maybe: + In domain founders, good pedigree  – GE + Rolls Royce + Technically strong + Arjun and Rohit seem to have a good leader -follower dynamics ? Founder archetype is  not Matrix ZOB – didn’t see any H&H or ambition to make It very big ? Moat in technology – gas turbines well researched and in commercial use already ? Limited TAM and team also unclear on end market – speaking of multiple use cases but no real pipeline ? Prototype still under development, leveraging IISC facilities ? Thesis – need to understand space better **Meeting Notes:** [Rohit Chouhan](https://www.linkedin.com/in/rohit-chouhan-842b063a/?originalSubdomain=in) - Masters from IIT Delhi - Joined DRDO as Scientist in GTRE - Developing gas turbine engine for Tejas - Developed for 4 years: Kaveri engine - Worked on hot end, development on supply chain – foreign vendors etc - Worked on small gas turbine also – on cruise missile - Joined GE - Known for execution excellence - Started gas turbine team from scratch – became global tech leader for 40-140 mw power gen machine - Designed 3-4 new products, and new tech development - Has more than 50 US granted patents: 20 is on new gas turbine, 30 on new tech within turbine components for efficiency - End use case of their turbines - Aviation – powering aircraft engine - Same tech also used in power generation – electricity - Fundamental diff: in power gen weight is not a constraint, in aviation need lighter variant - Their first product is more suited to A...'),
(292, 'Deck 2026-03-10T11:26:00.000+05:30: [File: download](https://prod-files-secure.s3.us-west-2.amazonaws.com/b21975bb-aebf-48e3-8c44-1573c4404129/57a143dc-6603-4927-94a5-bf5bc6271f9a/2026_03_10_Nama_Stay.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAZI2LB466TDK7S7WY%2F20260320%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20260320T110025Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGgaCXVzLXdlc3QtMiJGMEQCIDG%2F40sSul6%2BZ9DMQ8TseacEBaKWicSR2lh6n2Ng%2BFAxAiBlxv1qSNj99GnVXHn0gUWDTNE5Fibo%2B3K9DyvkRmMjRSr%2FAwgxEAAaDDYzNzQyMzE4MzgwNSIMB%2B99qIcvDGn7aZnxKtwDJ3qvQPncQdIe5lLYLyeV1Je%2FlJ4GSUB7STdaeCsp8htO9VQ765yrtFNF4LcmTG8deJAiSbcbIYTR2HExJVeUKzUhsWhOxT8EF6zlfsnIYvciQBYtU0hON9fTE76BdpQZKbjdWDnNUkW7BnpJbP1vZOyK%2FnMb6S7IzSu%2FRl5ON0IBj0cpihp9hyvmHzHj%2FJaXm%2Fr5f0uDhPne7XR6xJ50Jn4jv1TkPBUuBz37Yfc8wnWOSvGVwzwnwdTzsAu8cMatz8Q6tB%2ByGJOgQnKQItYmyM4iu4b9jtOMnO6V2Op6NR3cgEmCkT5ZdWolluXyqd2nZyZCq5WIidEIqdA97ID71oYHvZYCej2qagBhhNa1VrjWzCY8QWK7DaEBWeCuL35A2nvIMuInedSz6dKKCwaRR%2F3cOY01xJz7g3oMWTvDt1KWF17im3OyyMqTjYX0jA8MfNAMMEgqhyGn6nvxevExN436uuwD23DML3vXR0KfylQ8rh7ciJFCIUJ7o%2BXmdfnfegeulSAGQQQi4m9UAlPzO24zTXmFHHpdwSRNeYH1%2FAVflWmwKUiiJjmmp750HAhFw6MM1KYzpsh6Hg45NQ%2Fm6PmSwUvSocBMGWPxZ5QC4pdqVQ5C6Q44f4J6wb4wuP3zzQY6pgFlZONdrk%2B41qzVSC7OA2QlU%2FAVe8NoMGcogjFqgntJFNJDguXp%2BS4bunnmVIe6LW0yGVSz7aVzk42KrvAJm1aQFlUz8QNFnuvvj7S67BjuMLkRgQJB%2BIBomabx7d0auHEedIrwWuEre21eBv%2BMGzmjJ%2BnLI9CFk8dsLzutfhcEM8hmWFtJw9%2BV1yVXPPFCQD0pwpwcYpdVz...'),
(293, 'Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): ')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;