INSERT INTO util.enrichment_staging (company_id, content) VALUES
(216, 'Received from Rahul - 2026-03-13: [https://www.linkedin.com/in/jagdeep-singh-805b55124?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app](https://www.linkedin.com/in/jagdeep-singh-805b55124?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app) Groww director/business head of broking starting up ---'),
(217, 'Post-Meeting Investor Debrief: The investors expressed skepticism after the meeting. Concerns raised included: - Lack of clear moat despite claims of simple, superior design - Questions about why Xiaomi (known for despeccing products) hasn''t implemented similar design improvements - Uncertainty about learnings from previous startup failure/wind-down - Doubts about founder''s ability to scale in a difficult category The investors agreed to pass on the opportunity. This is all the malls, Phoenix, PurchaseLegal, Nexus, It''s all of the chains, right? McDonald''s, Subway, KFC, a lot of independent types are for $1,000. We''ll start with one. So that was my bread and butter for the longest time. Then in 2021, we decided we wanted to do something else. We no longer wanted to be an app, but we wanted to continue driving to fall to stores. So we came up with what is today the only affiliate program for offline stores, which is like seamless, clean, neat, etc. I ran that for three years until 2024. We raised a lot of money for that business. We were backed by all of the amazing folks, founders of Swiggy, Razorpay, Mama Earth, and so on. I was building a company with my fiancee at the time. We parted ways. And I decided I don''t know, I wanted to pursue that opportunity. We were lucky enough to get an acqui-hire from Razorpay, but we turned that down because it was like one next invested capital for a three-year lock-in. But instead, we rolled up a trust and all of my investors got equity i...'),
(220, 'Web Research:: - From Pilot to Profit: Survey Reveals the Financial Services Industry Is Doubling Down on AI Investment and Open Source Explore NVIDIA’s AI solutions and enterprise-level AI platforms for financial services. NVIDIA and Global Industrial Software Leaders Partner With India’s Largest Manufacturers to Drive AI Boom https://blogs.nvidia.com/blog/ai-in-financial-services-survey-2026/ - AI Goes Vertical in Financial Services - by Singularity AMC This is just one example. Millions of scenarios and insurance offerings, based on their possible outcomes with real-time risk assessment could shape the future of insurance as power of compute continu https://www.singularityone.in/p/ai-goes-vertical-in-financial-services - Top startups in Native AI in Financial Services in India (Dec, 2025) - Tracxn Native AI in Financial Services Sector in India has a total of 81 companies which include top companies like <strong>HyperVerge, Scienaptic and Arya.ai</strong>. https://tracxn.com/d/explore/native-ai-in-financial-services-startups-in-india/__Q1Gma5Dgr6QVb3HupvIku84g3GlxeG-3iONQF1m-lZU/companies - Financial AI: 21 Cases of Artificial Intelligence in Banking • UXDA | Financial UX Design Virtually every major bank has financial AI pilot programs, with common use cases around fraud detection, chatbot customer service and credit risk analysis. The momentum is driven by both competitive https://www.theuxda.com/blog/ai-gold-rush-21-digital-banking-ai-case-studies-cx-transformation - To...'),
(221, '**Background and Role at MPL:**: - Hired during COVID (2019) as Rachit''s replacement in design leadership - Initially hired as AVP of design but needed grooming for the role - Later became head of design after an intermediate hire was let go - Successfully aligned the design team with objective business KPIs - Demonstrated steady leadership during turbulent times, including a 60% team reduction **Key Strengths:** - Meticulous and calm under pressure - Resilient and reliable during challenging periods - Excellent people leader (7-8/10 rating) - Strong at lateral and downward management - Objective in difficult decisions, not letting personal relationships affect judgment - Considered among the top 5 design managers Rachit has worked with **Areas for Development:** - Not strong at upward management - Inverted priority hierarchy: Team > Design > Product > Company (should be reversed) - Rated 5-6/10 as a business leader - Unclear if he would have the foresight to preemptively identify business challenges - Receptive to feedback but had limited progress in business orientation **Recommendations:** - [ ] Consider advising Ketan to find a co-founder who is stronger on business acumen - [ ] Conduct additional reference checks to verify business capabilities - [ ] Assess whether Ketan''s business perspective has evolved since leaving MPL ---
RM Notes: 1. Hired Ketan to replace himself - during COVID | 2019 1. Rachit was going to start another initiative within MPL 1. 2-3 months in real...'),
(222, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): ')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;