INSERT INTO util.enrichment_staging (company_id, content) VALUES
(275, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): '),
(277, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): '),
(279, 'Next Steps: - [ ] @Krish Bajaj to try the product and provide feedback - [ ] @Rahul Mathur to conduct reference checks on the founder - [ ] If progressing, arrange meeting with another partner at DVC - [ ] @Rahul Mathur to potentially connect founder with additional potential users Notes 1. Dr Winson Park - Korean researcher - 1. Hybrid job based in Dubai 1. Founder of Xpay recommended him 1. Product #1 - sentiment analysis for brands 1. $20 per month 1. Product #2 - receptionist for dentists 1. $500 per month from clinics 1. Was selling from India to USA 1. Discontinued 1. WhatsApp 1. Doing via Linked Devices 1. Indian user willing to pay $50 per month 1. US user willing to pay $80 per month 1. They want Slack integration 1. Shipped for Rishabh Dodo Payments 1. Smart / inherent virality via “@loop” 1. Users: 1. CA or Doctor for Qs 1. Founders to monitor senitments from 1. Students / others use it to listen to WA groups Sir, can I get one green tea please? Okay sir. Thank you. Hey Amon, how are you doing? Hey man, very nice background. Where are you calling from today? I''m in Bangalore. Thanks sir, it''s a fake background. No, I''ll go in. I''m in Bangalore. Residency has a global network, so I''m part of Bangalore right now. But yeah, I''ll go in Jan. For like 3 months. Where are you right now? I was in Bangalore. He is in HSR. Currently, I am in Badubhishnadi. Residency is a very good thing. I recently was in SF, I met Abhinav from Breather and he speaks very highly of the resid...'),
(283, 'Deck: [File: download](https://prod-files-secure.s3.us-west-2.amazonaws.com/b21975bb-aebf-48e3-8c44-1573c4404129/c03c41e0-d2d8-4543-b15d-a8d53a028d10/1._Modus_AI--Fundraising.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAZI2LB4666H7XLVMC%2F20260320%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20260320T105658Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGgaCXVzLXdlc3QtMiJHMEUCIQD%2FGwFQao5dI0GDb0x7cTeid9oZgJvyW3cDhABH3pf1DQIgC7f3rxd8uGiKg5KHV2Qm%2FpWbTb2nxymg0%2FiQ7Y9vpNQq%2FwMIMRAAGgw2Mzc0MjMxODM4MDUiDBytoewTaYvbMdVlwircA9RuoshDLpVmLUs5HzjvLIafs%2F8vodmSo2haKbTwYaNq7QsDD1%2F60JZdzJoJ1MuXmiMSTVfhi1%2BRmjYWfpx8DkTLVV2D476v21rBhx5MhjJFnwDWLDb9Vt422VEniywh2u0MkWmkQNVJUKBibTKixMDJ11zET1udRjc5rMrCqktenqwwLJApNTstRRY2yOqj05VVl7ZBSGKyHtAtmYaOX1y7DaYD542MYsIzax84lcuDaRqyaEYQHJzmGNk58ll0CPrHE7Dn4W%2FJytkBTf7%2F5vRnqnQKjo1h3RD3Ly77ym%2BuwaCXgf89w8bKXPngKJT%2BKDFGrVitPB7%2B9n7EOt3q695JXKLe6x03OZFdDBGfrbzfBdidKjG%2FQV8XxbLcOmae6L%2FtLW%2FXT4FowuNryQ9P1dRoQL78baiqkfZ5v6CHq0C1djUH4Uc5wGbcx04soPh5OUbyrqlA9foKr1ftn1ihzs0j33zoLfrXYgRjMOZ8PXE3NL6EqymbDWQukJ721H62fntScwONK5iw0OsrXMX%2Bfj5N7BOGkyN2bnWLcCaNem8idcqs6B34vJoi0aorH%2Fe0PAD%2F0YgV1UsVQhPorYXkNEmzHJt5EMTlRvXld8xr7yeWLKcw%2BqhG%2BK5sjqWDMJv8880GOqUB58NbLqpzQXZeLn6vIAMKvgYBzbTVKS43VBnwTQnawerr9deqPDSGyhVCsuTEjxw7pLu4xI2%2BPKdrwcPz6eMZgJbvLnc1BrgR9HU2BYwXMpTVG25glDq5DeTPFaQE9VzJnr9ULlwdGml%2FIC%2BAdxlrEiGDLC2VNDiC4ZT7r88CALFKhbuve2UJjT5SMvJeEeytgkwdGuwQMXq3X1PY%2BmtYjiUgxd%2Fv&X-...'),
(284, 'Notes:: 1. **Childhood** 1. Full Hindi guy 1. From small town in Bihar 1. Not strong financial background 1. 23 years old 1. **Rewards / gaming business** 1. First business he built at 17 1. Built an app on no-code platform 1. Got 1L+ installs 1. Was making $4K per month || scaled to 500K installs 1. Google killed the business by changing ads policy 1. **2nd business** 1. 1M installs 1. WhatsApp related business 1. Each QA update killed the release 1. BLR - Jain Univ — just before COVID - left 1. **Food delivery business in his local city** 1. Started before Swiggy & Zomato post COVID 1. Swiggy & Zomato entered which killed the business 1. Sold the software & logistics to a restaurant business locally 1. **Kutumb** 1. Approached Abhishek with an earlier idea 1. Abhishek told him to come to Kutumb & test 1. Wanted to find the next $1bn idea 1. Ran thousands of ads 1. Spoke to customers across T1 and T2 1. Explored a lot of T1/T2 cities 1. Tried multiple D2C products 1. Problem in D2C → frequency 1. **His learnings** 1. Snacks → high frequency category 1. Companies are making guilt free western snacks 1. Why not make traditional snacks guilt free 1. Ran 50 ads variants — found 50 SKUs 1. Saw QC tailwind 1. Mom is the culinary expert 1. He figured out something about the form factor (I can’t understand Hindi) 1. **MIS** 1. No QC | no 3P market 1. October - ₹3L in Sales | 70% pre-paid | CAC 1. **What would change if he had capital** 1. 3 years — ₹100 crore 1. **Kitchen** 1. Start...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(289, 'Investor Feedback & Decision: - **Z47''s assessment**: - Very high bar for QSR investments - Founders "not bad but nothing exceptional" - Category not sufficiently differentiated (every market has street food) - Prefer non-linear business models over linear store-by-store expansion - 10% EBITDA at ₹20 lakh stores "not great" - economics typically degrade as businesses scale - First few outlets often have better economics that aren''t replicable at scale - Network-wide EBITDA likely to settle at 8-10% - **Key investor concerns**: - Things get difficult at 10-20 outlet scale due to competition, food consistency issues, or location choices - 15% monthly attrition means 150 people leaving monthly at 100-store scale - Important metrics to track: customer feedback, NPS, repeat rates, same-store sales growth - **Investment decision**: Pass from Z47, but Titan Fund is leading the round And both moving and targeting the new target with the update in Bangalore for the Ramadhin survey for today. We all built that up for the update in Bangalore now. Then we also started downloads to operate your veg pan to find out Yes, so about me, I am a commerce graduate turned chef. Before I met Tanay at Mesa, I spent roughly two and a half years working in the kitchen. I started my culinary training in France and then ended up spending two years working in Sweden in a Michelin star restaurant and also in the south of France. So I worked across different formats, Michelin star hotels. In the meanwhile,...'),
(290, 'Action Items: - [ ] Circle back regarding next steps - [ ] Follow up on establishing team in Bay Area Now within a pre-construction, the task can be looked into four different phases. The first one is feasibility, second scoping and costing, third scheduling and procurement and finally construction readiness. After construction readiness, it goes into the project manager who does the execution through the handover. But a project manager usually deals with one project at any point in time. Now compared to that, a pre-con manager... It is not an execution, they deal with multiple projects. Now, the idea for the preform manager, as I was saying, they have to bring in more business. So, the more the number of projects they are able to deal with in parallel, the better it is for them. So, that''s where their North Star metric lies. Now, they had all of these four phases. We land in scoping and costing, that''s the second phase. It will expand to others, but the buyer is the same for all of the phases, because it is the pre-con manager. Now in scoping and costing, primarily what a pre-con manager does is scope sheets, bid levelling and price benchmarking. While I am saying this, I am talking from the perspective of a general contractor, all of it. Pre-con teams exist with owners, developers, subcontractors across the ecosystem, but we work with only general contractors to begin with. Now, when the general contractor receives or the pre-con manager receives all the bid packages from t...'),
(291, 'AS: Weak Maybe: + In domain founders, good pedigree  – GE + Rolls Royce + Technically strong + Arjun and Rohit seem to have a good leader -follower dynamics ? Founder archetype is  not Matrix ZOB – didn’t see any H&H or ambition to make It very big ? Moat in technology – gas turbines well researched and in commercial use already ? Limited TAM and team also unclear on end market – speaking of multiple use cases but no real pipeline ? Prototype still under development, leveraging IISC facilities ? Thesis – need to understand space better **Meeting Notes:** [Rohit Chouhan](https://www.linkedin.com/in/rohit-chouhan-842b063a/?originalSubdomain=in) - Masters from IIT Delhi - Joined DRDO as Scientist in GTRE - Developing gas turbine engine for Tejas - Developed for 4 years: Kaveri engine - Worked on hot end, development on supply chain – foreign vendors etc - Worked on small gas turbine also – on cruise missile - Joined GE - Known for execution excellence - Started gas turbine team from scratch – became global tech leader for 40-140 mw power gen machine - Designed 3-4 new products, and new tech development - Has more than 50 US granted patents: 20 is on new gas turbine, 30 on new tech within turbine components for efficiency - End use case of their turbines - Aviation – powering aircraft engine - Same tech also used in power generation – electricity - Fundamental diff: in power gen weight is not a constraint, in aviation need lighter variant - Their first product is more suited to A...'),
(292, 'Deck 2026-03-10T11:26:00.000+05:30: [File: download](https://prod-files-secure.s3.us-west-2.amazonaws.com/b21975bb-aebf-48e3-8c44-1573c4404129/57a143dc-6603-4927-94a5-bf5bc6271f9a/2026_03_10_Nama_Stay.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAZI2LB466TDK7S7WY%2F20260320%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20260320T110025Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGgaCXVzLXdlc3QtMiJGMEQCIDG%2F40sSul6%2BZ9DMQ8TseacEBaKWicSR2lh6n2Ng%2BFAxAiBlxv1qSNj99GnVXHn0gUWDTNE5Fibo%2B3K9DyvkRmMjRSr%2FAwgxEAAaDDYzNzQyMzE4MzgwNSIMB%2B99qIcvDGn7aZnxKtwDJ3qvQPncQdIe5lLYLyeV1Je%2FlJ4GSUB7STdaeCsp8htO9VQ765yrtFNF4LcmTG8deJAiSbcbIYTR2HExJVeUKzUhsWhOxT8EF6zlfsnIYvciQBYtU0hON9fTE76BdpQZKbjdWDnNUkW7BnpJbP1vZOyK%2FnMb6S7IzSu%2FRl5ON0IBj0cpihp9hyvmHzHj%2FJaXm%2Fr5f0uDhPne7XR6xJ50Jn4jv1TkPBUuBz37Yfc8wnWOSvGVwzwnwdTzsAu8cMatz8Q6tB%2ByGJOgQnKQItYmyM4iu4b9jtOMnO6V2Op6NR3cgEmCkT5ZdWolluXyqd2nZyZCq5WIidEIqdA97ID71oYHvZYCej2qagBhhNa1VrjWzCY8QWK7DaEBWeCuL35A2nvIMuInedSz6dKKCwaRR%2F3cOY01xJz7g3oMWTvDt1KWF17im3OyyMqTjYX0jA8MfNAMMEgqhyGn6nvxevExN436uuwD23DML3vXR0KfylQ8rh7ciJFCIUJ7o%2BXmdfnfegeulSAGQQQi4m9UAlPzO24zTXmFHHpdwSRNeYH1%2FAVflWmwKUiiJjmmp750HAhFw6MM1KYzpsh6Hg45NQ%2Fm6PmSwUvSocBMGWPxZ5QC4pdqVQ5C6Q44f4J6wb4wuP3zzQY6pgFlZONdrk%2B41qzVSC7OA2QlU%2FAVe8NoMGcogjFqgntJFNJDguXp%2BS4bunnmVIe6LW0yGVSz7aVzk42KrvAJm1aQFlUz8QNFnuvvj7S67BjuMLkRgQJB%2BIBomabx7d0auHEedIrwWuEre21eBv%2BMGzmjJ%2BnLI9CFk8dsLzutfhcEM8hmWFtJw9%2BV1yVXPPFCQD0pwpwcYpdVz...'),
(293, 'Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): ')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(294, 'Notes:: Surfacing [Navanc](https://www.navanc.com/about-us), they''re building a tool for property evaluation which is used by lenders in collateral assessment for secured loans. Essentially replacing the local valuer model which has issues such as opacity, TAT, fraud, etc. Founder is an EO with extensive experience in the space. Early traction is also decent - ~30 lakhs MRR, cracked mid-sized NBFCs and in final stages of cracking large NBFCs. The company is raising $2-3 mn. currently. Please find [vault](https://deltazen47.sharepoint.com/:f:/s/TheVault/EoVazkQZAohMugwEJVG_hCUBzM4qFPjTsHBLgOKa2tFOEg?e=czvCd3) link, customer refs + our eval views below - <u>**Eval Views**</u> **Taha - Maybe** + EO building in domain with significant hours in the space, good set of initial clients as well- IRMA + ICICI+ NBFC (pattern match) + Depth in the space --- had clear answers on property diligence(state level), valuation ? Unsure on what this product is — BRE, AI assisted workflow, services with a CRM ? End Scale outcome-- can he expand into legal workflows as well **Dhairen – Maybe** + Domain native + Addressing a major pain point for lenders, can see a play here - need to do ref on delta in efficiency + pricing + Interesting traction - Billing 7-10 lakhs p.m. to mid scale lenders quickly ? Product v/s company? Ability to expand into adjacencies? ? There''s a large services angle at play so will need understand if there''s potential for a business with quality rev. or is it just an aggrega...'),
(295, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): '),
(297, 'Draft: Hi team, Sharing the heads-up note for our investment in [Neuralzome Cybernetics](/11f29bccb6fc8040a51cf08cae0cb796). This is a Quickly Teachable Agent platform — allowing users to train equipment or machinery to perform actions or exhibit behaviors. The initial use-case is precision agriculture in the USA. Neuralzome Cybernetics is a spin-out of the AI & Robotics team plus IP from [Flo Mobility](https://flomobility.com/) (a Blume Founder’s Fund portfolio company) DeVC is investing $100K/₹86L as part of a wider ₹12 crore round led by 8X Ventures This is a Venture Partner cheque (via Ashwini) which also meets the DeVC Community Top Up criteria **Founders** 1. [Mohan Shivam](https://www.linkedin.com/in/mohansivam/) — CEO 1. ex CoFo at CTO at Flo Mobility (3 YOE) 1. Ex CoFo at GAMASOME (8.5 YOE) 1. [Aditya Shriwastava](https://www.linkedin.com/in/adish-ai/) — CTO 1. ex head of robotics at Flo Mobility (2 YOE) 1. ex engineer at iFuture Robitics (1.5 YOE) 1. BITS Mera graduate **Investing Process** 1. This was sourced by the DeVC Collective via Soumitra Sharma 1. Cash did the 1PE followed by expert chat (with Peepul Agri founder) 1. From expert chat —  *“Neural is a top notch team | polymath robotics is also doing similar in US, but likely going to be multiple expensive. cost is key here.” * 1. Mohit & DC did a 2PE 1. Per Mohit — *“Spikey 1 with a spike in product and hustle, and resilience.”* 1. Details were surfaced to the full DeVC Collective 1. Ashwini: *“Positives: Fou...'),
(301, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): '),
(302, 'Heads up note 2025-10-18T16:29:00.000+05:30 from @Rahul Mathur: Hi team, Sharing the heads-up note for our investment in [Nimo Planet](https://www.nimoplanet.com/). The company is shipping/fielding spatial computing for work (Core + OS + glasses) Their proposed solution layer is “Nimo Infinity: Personal AI Workspace” — a canvas with “prompt-to-mini-AI apps,” browser agents for legacy apps, sandboxed memory/context, and an MCP app store. DeVC is investing $50K as part of a 700K round @ $5M post money valuation led by [Mucker Capital](https://mucker.com/) Note: Since this is a community top-up to Anand Lalwani; we will be doing deeper work during our November 25 trip to SF where we will spend time with the founder **Founders** 1. [Rohildev Nattukallingal](https://www.linkedin.com/in/rohildev/) 1. 8.5 YOE @ previous startup 1. Had raised ~$3.2M in VC funding (led by Kalaari India) 1. Launch world''s first gesture based wireless smart ring called Neyya 1. [Suneesh Thuluthiyil](/1c829bccb6fc803f8c38fbaa5ef0617f) 1. 8.5 YOE @ previous startup (together) **Investing Process** 1. We were introduced to Rohildev by Anand Lalwani (CoFo @ Cardinal Robotics) who had already committed to invest $50K into the company and is now adding a further $50K 1. Cash did a 1PE - Weak Maybe for Core Cheque 1. *?? Purely technology out and just doesnt seem like a marketable product builder* 1. *?? Not a first principles CX thinker* 1. *?? Lacks growth chops and past history is un-inspiring. Tinkerer sci...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(303, 'Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---'),
(304, 'Action Items: - [ ] Z47/DVC to consult with Confido about their experience with Nixo - [ ] Z47/DVC to provide investment decision within 48-72 hours - [ ] Akash to introduce Sidhu/Chetan to Priya - [ ] Priya to connect with investors via WhatsApp A good evening. How should we do the intro folks? There are three of us today. Should I just introduce the fund and then everyone give one two lines about themselves? This one is also end of call commit or we have time? Don''t have time but not necessarily end of call. Okay. Because given Anand is deeply plugged in so we can be patient. Okay. No, not yet. No, no, I''m just checking. Oh. Hello Priya. Hi. Hi, very nice to meet you guys. Nice to meet you. Is Preeti also joining? No, she unfortunately can''t make it. She has some other important work to attend to, but I''ll be here. Got it, got it. No, so quick context setting here. Akash Rajat Rao will quickly share a bit about us. We are Z47 and DVC, earlier we were known as Matrix Partners India. We invest out of two funds, one is a venture fund, which is more post-seed-seed to Series B. And DVC is a pre-seed-seed fund, where we partner with founders super early in their journey. Pertaining to what you are building, this is a space we''re pretty deeply calibrated in. At one end for customer success and CESPM, we have a company called Rocket Lane, which we had seeded and then let the A and the B in, which was together with ABC. That was from the venture fund. And outside of that in the depl...'),
(305, 'Next Steps from Rahul: - Introductions to consumer brand founders (Mohit Sadani and others) who successfully used mom influencer GTM channel - Market work and customer chats over next 48 hours - Follow-up discussion with Rajat to determine what''s needed for next meeting - Overall positive reaction: found the concept "refreshingly unique" compared to typical consumer brand pitches He was my junior at IIT Gansur. So that''s when I got in touch with him, met Raghav, Atulia and have been at Judo for the last 5 years. So you know about that part of me. Right. So now, sort of decided to move on. Yeah. Because Preksha has been at this Nomado for I think close to six, eight months now and we did some pilot and there was some conviction to sort of start this up. Yeah. But maybe, Priyaksha, you can talk about your background. So now a very similar profile on paper, very different skills. in practice but yes Engineering background, then worked at CS for a couple of years, then IMB, MBA in ''17. Then I joined McKinsey. I was with McKinsey for about a couple of years And then I, after that I also wanted to at that point I joined OYO. They had launched Mountania for upscale hotels and they wanted somebody to create a full operations team for that and how would everything look like. I joined work with Vivek Sinha for a brief period in India and then moved to a role in UK because Rishabh had decided to shift to UK so I also decided to shift along with him. And so they created a role for me whe...'),
(311, 'Go-to-Market Strategy: - Focus on national jurisdiction enterprises (80% of litigation) - Target PSUs and government bodies - Key differentiators: - Speed of filing - Digital experience - Cost advantage - 12-month team growth target: 20 lawyers (5 specialists, 15 process), 20 annotators, 5 tech team
Company Background & Team: - Founded in 2024 by 25-year-old founder from Bangalore - Strong legal connections through family: - Mother is expert in setting up law schools - Co-founder Pratik runs own law firm for 5 years - Third co-founder Takshu (currently in USA) - Initial pivot from education tech to legal tech in Jan 2024
Product & Technology: - AI-powered legal drafting system with human-in-loop verification - Key features: - Translation services ($1/page, 7000 pages/month from Karnataka High Court) - Real-time dashboard for enterprise clients - 14-day timeline to add new legal specializations - 12 annotator/proofreaders (non-lawyers) for quality control - Demo showed automated legal document drafting system
Nyayanidhi Founder <> @Aakash 2025-07-08: Overall: Strong Maybe EO: 4-5 | FMF: 6-7 | Thesis: 7 | Archetype: 5-6 | Spikey: 1 ++ Super spikey founder. Fastracked credits at NIT ++ Hacker tinkerer profile and always been shipping and building ++ very organic build out (as per his narrative) towards the AI first legal play ++ Hustle first execution to get to right platforms, open doors ++ Partenred with right domain co-fos ++ Strongly vouched for by Sidu and Nischhay (jar) ??...'),
(317, 'RM reflections —SM to try to add to his existing $2.1M led by 1984 VC: ++ Outside In; had studied ReTool, Lovable etc ++ Good seller despite being extremely technical ++ H&H is obvious: Built company in high school etc ++ Better than Lovable - can edit in UI, can pin up Neon DB w/o user doing any work ?? Lots of FF traits - had done shallow outside in work (i.e. public sources); didn’t dig into own YC network
RM action items: 1. Get introduction to 1984 Ventures via Olive 1. Send Olive the following: 1. CRUX intro 1. Companies we spoke about
RM Notes:: 1. Moved from Iran 1. Funzie  Brex for non-profits 1. Social consumer splitwise type priduct 1. Got into YC with that idea 1. Interested in code gen 1. Decided to build a lovable competitor 1. “Lovable for Business” is what he is building 1. Integrate with DB 1. Showed demo 1. Could live edit in the GUI - edits flowed into code 1.
Prep notes 2025-07-28T09:06:00.000+05:30: 1. Objective: 1. Get introduced to 1984 Ventures 1. Learn more about ZFellows (?) 1. Raised from Gustav YC and 1984 Ventures 1. Was it Samit Kalra (?) 1. Marc Persival 1. 1. ReTool in an AI first world 1. Prompt to dashboard 1. Thesis is 🎯 - even in an AI first world, users want Dashboards 1. Internal tool building 1. Whenever I hear things like Supabase etc - I don’t know what to do 1. Lovable integration with Supabase was a painful experience for me 1. Everyone told me I shouldn’t use Lovable created files because they are vulnerable 1. I really liked the co...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(318, 'OnCall Owl — summary (from the 2‑pager): - **What it is:** An **autonomous AI “on-call engineer”** that can **detect, diagnose, mitigate, verify, and document** production incidents without paging a human. - **Problem:** Modern distributed systems still rely on humans for on-call. The deck claims **60–80% of incidents are repetitive/deterministic**, while **SRE cost is high** (e.g., $180K+ senior SRE salary; **$5M–$15M annual SRE spend** at ~$500M ARR SaaS). - **How it works (capabilities):** - **Detects** anomalies from observability tools (Datadog, CloudWatch, Prometheus, Grafana) - **Diagnoses** via correlating deploy history, metrics, traces, config changes - **Mitigates** via actions like rollback, scale, restart, feature flag, traffic shift, failover, within guardrails - **Verifies** recovery before closing incident - **Learns** by drafting RCA, updating runbooks, creating follow-up tickets - Safety model: customers define **safety zones + approval thresholds**, with a **copilot → autonomy** progression. - **Why it matters / positioning:** Framed as **headcount replacement (labor leverage)** rather than incremental tooling. Target is to reduce L1/L2 on-call burden and MTTR, and be **infra-agnostic** across clouds/Kubernetes and the observability stack (not vendor-locked). - **Business model (deck numbers):** - “Free to start” (connect stack, observe first shift) - Pricing shown as **$500/shift/month** (also mentions **$99/mo/shift** earlier) plus **consumption/credit pa...'),
(320, 'AI Notes: **OnFinance journey and challenges** **2025-04-28T14:32:00.000+05:30** Himanshu joined OnFinance after reconnecting with Anuj, a childhood acquaintance from the same locality with whom he shared a friend group but wasn''t particularly close. Their relationship began with Himanshu providing GTM consultation before joining full-time to handle go-to-market while Anuj focused on fundraising and Priyesh on building the technology. **Company Evolution:** OnFinance began as a Singapore entity focused on crypto: - Initial product was a crypto and US equity advisory platform with a proprietary recommendation engine - Scaled to 100,000 users and accumulated $50M in AUM - Struggled to monetize with a subscription model - Raised angel funding for this initial product - Pivoted to Compliance OS after conversations with banks, Smallcase, Angel One, and other financial institutions **Leadership and Working Style:** The founding team operated with notable characteristics: - Anuj is described as persuasive with banks and skilled at leveraging his network - Strong BITS alumni connections helped secure initial meetings - Creative networking approaches including taking golf course membership to connect with potential clients - Culture of gift-giving to prospects (e.g., champagne for good meetings) - Work environment involved 24/7 schedules with team living together in a shared flat **Internal Challenges:** Several issues affected the company culture: - Poor conflict resolution processes...'),
(321, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(323, 'Analysis by dev - 2026-01-08: ### Company Snapshot Problem & solution OpusCollect positions itself as an AI-first full-stack collections platform aimed at moving from pre-delinquency to hard-bucket collections, addressing a market with fragmented pan-India field operations and little scale in field-based collections. Market notes emphasize a gap in pan-India field collectors and a shift toward AI-enabled, data-driven recovery processes for banks and NBFCs. Ideal customer profile and pricing Direct clients include Unity Bank, Jana Bank, Avanti Finance, BikeBazaar, Branch, with additional through-partner channels (Fusion, ESAF, Cashe). Total assets under management ~₹900 crore; monthly collections ~₹6 crore. Pricing signals: - Take rates reported as 10% regular, 15% SMA, 20% for 90+ DP buckets. - Revenue drivers indicate 60–70% commission from collections, 15–18% automated legal services, 5–8% AI-driven collections, 2–8% data enrichment; for >90DPD, commissions can be 25–35% of amount collected. - For Kissht, a go-live target of ₹1 crore per month billing is noted. [Inference] Pricing appears to mix performance-based commissions with verticalized service fees; no formal external pricing sheet disclosed. Status of product & traction highlight Live, multi-channel field operations with AI/automation components: - In-house bot calling, route optimization, automated case allocation, and digital legal workflow. - Android field-collection app; real-time field tracking; 64k digital leg...'),
(324, 'Heads up note from @Rahul Mathur 2025-08-23T15:18:00.000+05:30: Hi team, Sharing the heads-up note for our investment in [Orange Slice AI](https://www.ycombinator.com/companies/orange-slice). The company provides AI agents that find you customers who show demand signals - the agents crawl the internet for signals/firmographic data that help sales teams find high-intent prospects by continuously monitoring the internet for buying signals and firmographic changes DeVC is investing $250K as part of a post-YC SAFE round at a $25M cap with MFN clause **Founders** 1. [Kishan Sripada](https://www.linkedin.com/in/kishansripada/) (Co-Founder & CTO) 1. 1 YOE as SDE Intern @ Ramp 1. Ran a successful dance formation app used by Disney, Broadway, Lakers etc 1. Ran an “Airbnb for kitchen space” business during COVID 1. Market making platform connecting unused restaurant kitchens with home cooks 1. Sold to restaurant chain Bravo for $150K 1. Ref from Ramp Manager: "Good kid but young and hard market” 1. In context: "This guy (the manager) is harsh so even a terse vote of approval like this is strong!” 1. UMich ‘25 - dropout 1. [Vihaar Nandigala](https://www.linkedin.com/in/vihaarnandigala/) (Co-Founder & CEO) 1. Left $500K TC placement at JPMC to start this business 1. UMich ‘25 - dropout **Investing Process** 1. This was sourced by simultaneously DeVC IP team (YC mining) & Z47 Enterprise AI team 1. Ashwin & Krish did the 1st call from a Product Eval POV - post which he shared with the wide...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(325, 'Meeting Prep — 2026-03-02: **Source: **DocSend deck + email pre-read from raj@withorbi.com (Mar 2, 2026) **Deck: **[https://docsend.com/view/y3wrtejc6wv8kem4](https://docsend.com/view/y3wrtejc6wv8kem4) ### Traction - 1,110+ invite-only beta users - 30% WoW growth (Nov-Jan) - 60% M1 retention (best cohorts: 80%) - 26 min avg session (2.5x Roblox), max 6 hrs/week - 50% referral rate ### Market - US 5-12: 30M kids × $123 ARPU = $3.7B/yr - Global: 1.2B+ digital-native kids × $60 = $70B+/yr - AI companions: $37B (2025) → $552B (2035), 31% CAGR ### GTM - Homeschooling networks (VELA, Primer, National Microschooling Center) - App Store waitlist: 3K+ | Parent influencers: 10K+ | Gaming creators: 50K+ - Monetization: microtransactions + subscriptions ### Raise $2M seed. Roadmap: Phase 1 digital worlds → Phase 2 cross-app (Minecraft, YouTube) → Phase 3 offline (toys, wearables) ### Key Questions 1. Safety & regulatory: COPPA, Character.AI lawsuits, content moderation framework? 1. Valuation & DeVC fit: $2M raise at what val? Where does $30-150K cheque fit? 1. FrontRow post-mortem: same team, what failed, what''s different? 1. Retention depth: M3/M6 curves? Novelty decay risk in kids products? 1. Unit economics: inference cost per session? Can microtx + subs cover it? 1. Roblox defense: what if Roblox adds AI companions? ---
AI notes: ### Founder Backgrounds - **Raj** leads growth at Hobby; previously taught sports, arts, and math to kids in a government school in India starting at age 1...'),
(327, 'Rajat - Follow-up Call Request - 2026-02-26: Rajat requesting follow-up call with Aakash and Rahul after initial call with Raj Singh (CEO). Sneha to set up - Raj is based in the US. --- PRE-READ FROM RAJ (24 Feb 2026): PRODUCT DEMO & SESSION RECORDINGS SHARED: 1. Product demo video - Video link provided 2. Session recordings to show core user behaviors: SESSION #1 - Emma, 10 yo | 45 mins session | 2 days ago TLDR Insights: - Treats her pet "Whiskers" like a living being with needs, engaging in care-taking activities like making soup and visiting the vet when her cat is sick - Invents mini-games and activities to do together (playing fetch, painting, learning to spell) - KEY QUOTES: "You are my favourite part of the day." "I can do this all day and night." SESSION #2 - Freddy, 9 yo | 1 Hour 31 mins | Today | M2 cohort TLDR Insights: - Even in month 2, Freddy is still highly engaged, his storylines are richly detailed, unusually specific about the world, characters, and micro-details - Brings all his favourite characters like Sonic to life, creates adventure storyline with them and his pet --- ORIGINAL PRE-READ (23 Feb 2026): COMPANY OVERVIEW: Orbi is building AI companions for kids designed for play, learning, and social connection. Kids are skipping Roblox to create social worlds with their companions, spending up to 4 hours per day. TRACTION: - Beta with 1000+ kids - Growing 30% WoW - 60% M1 retention TEAM: 1. Raj (CEO) - Led growth for India''s first alt-tech university from...'),
(329, 'Key Metrics & Product: - YC W26 batch | 4 employees | HQ: 311 California St, San Francisco - Axis outperforms Google DeepMind''s AlphaGenome by 6.7% on regulatory element binding prediction - Building largest proprietary dataset of millions of experimentally validated regulatory DNA sequences - 72% sequence diversity — generated sequences explore genuinely novel design space - Wet lab + AI — currently testing sequences in lab to validate
RM notes: - Yash raised money from Contrary Capital - Started at end of 2024 - Dropped out of college - Released first model in October before YC - Encode data set - Scientific Advisor - Dr. Manolis Kellis — Professor of CS, MIT + Broad Institute (regulatory genomics) - Keen to connect Onco data in India - Mass of data available - Raised $3M funding to date - Signing LOIs from hospitals - Targeting 3-5 LOIs - BOM hospital is pending ethics committees - CloudNine
AI notes: ### Action Items & Next Steps ### Company Background & Founding Story ### Breakthrough Model & Technical Approach ### Data Strategy & Scaling Approach ### India Hospital Partnership Strategy ### Experimental Approach with Hospital Samples ### Business Model & Revenue Streams ### Funding Status & Plans ### Network & Connections Discussed
Scientific Advisory Board: - Dr. Manolis Kellis — Professor of CS, MIT + Broad Institute (regulatory genomics) - Dr. Nicole Paulk — Founder & CEO Siren Biotechnology, Asst Professor UCSF (AAV gene therapy expert) - Dr. Rashid Bashir — Dean, Gr...'),
(331, 'Rajat reflections: ++ Hustler ++ Outside-in +? Reasonably thoughtful ++ High agency ?? Value in business lies in automation of invoice sending, 100% lead capture & follow-ups etc ?? Risk of Sales adoption; RA has seen it in his own family business ?? Thin product right now ?? Tough business to build Rajat Qs 1. Why pick Industrials & Manufacturing? 1. Why do India only? ### Action Items & Next Steps ### Product Overview & Problem Statement ### Solution Description ### Current Capabilities & Roadmap ### Business Model & Pricing ### Go-to-Market Strategy ### Traction & Metrics ### Team Composition ### Fundraising Details ### Growth Strategy & Market Opportunity ### Key Challenges & Discussion Points
Received from Rahul - 2026-03-07: [https://in.linkedin.com/in/rohitrajxd](https://in.linkedin.com/in/rohitrajxd) --- ### Action Items ### Z47/DeVC Investment Philosophy ### Founder''s Background and Journey ### Previous Company: Worker AI ### Current Company: Pactyl ### Team - **Ravi** (technical): IIT Monday computer science, Mars rover community, job offer from Turing by end of second year, previously built cloud gaming company - **Nishit Sharma** (business development): ### Fundraising Details ### Competitive Landscape & Market Context ### Next Steps with Z47
DE w/ Bhuvan (CTO @ OfBusiness) 2026-03-19T18:32:00.000+05:30: Context: OfB actually building something quite similar and an analytics copilot on Tally to give business insights; hasn’t seen a product demo - pending for their...'),
(335, '2nd convo with @Aakash and @Rahul Mathur: 1. **Family background** 1. Sajial and Sailesh are blood siblings 1. Their uncle owns Hello Kids 1. All relatives are involved in the secondary steel business in Raipur 1. Right from Manfacturing to the retailer part of the value chain 1. Some relatives have CAPEX outlay of ~₹50 crore to ₹200 crore 1. Their father is the odd one out in the family i.e. owns a confectionary business 1. **Saijal background** 1. Rank #2 in IIT-B Metallurgy department; batch of 2023 1. Studied under: Prof Vishy, Manish Pandey and Sanjay (who is her mentor) 1. Thesis: Secondary steel manufacturing; published in ASM journal 1. Managed to get JSW to partner with IIT-B to finance a fest & research projects 1. Has done internships at Jupiter, Rocketium, BharatX 1. Decided to NOT pursue the funded PhD from IIT-B with Tata Steel since she felt India’s journey on green steel was very nascent & work was too elementary 1. Got a PPO from Kearney; worked in GGN office because of their energy projects 1. in 4 months, got placed in the project working with Ministry of Road Transport 1. It was a project to map out Indian highways for ~25 years with Nitin Gadkari 1. Left after this project because it then became project management 1. **Sailesh background** 1. Christ College 1. Dropped out 1. Did consulting biz for Ed in 2nd year to make money 1. Uncle convinced father to support him with this decision 1. Had lots of friends who were in IITs — saw their innovation 1. Saw R...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
