INSERT INTO util.enrichment_staging (company_id, content) VALUES
(436, 'RM notes: 1. “Altdevin” was initial name 1. 2 months ago 1. Devin web UI was very bad 1. Dev only operated as a Slack bot 1. Started coding at age 13 1. Codeforces etc - learnt C++ himself | competitive programming 1. 9th to 12th - studied for JEE | did CP 1. gave Olympiads - national bronze for CP 1. Sarvam intern 1. June 2024 - internship 1. LinkedIn post 1. Standard application process 1. Worked on AI Agents team 1. Operated like a quasi consulting business 1. AI X Coding - crowded but problems exist 1. Shiro is a shameless clone of OpenAI’s Codex 1. Iterate like mad - learn from users 1. At Sarvam - used ChatGPT & VSCode together | then used Cursor 1. User 1. Being leveraged for side or personal projects 1. Enterprise ask 1. Want a way to preview / browser attached to sandbox to see the UI before PR being raised 1. Wanted terminal ask 1. Value: 1. Code maintenance > Code Gen 1. Wants to pull in data from other sources to suggest changes to the product
**Background & Experience**: - Started coding with C++ at age 13 (competitive programming) - Won bronze medal at national level for competitive programming - Previously interned at Sarvam AI (2.5 months) - Worked on AI agents team - First startup office experience
**Current Product (Shiro)**: - Started building 2 months ago - Initially aimed to be better version of Devin with web interface - Current features: - GitHub integration - Kanban board functionality - Pay-per-task pricing model (no rate limiting or token caps) - Use...'),
(439, 'BRC on Anu Engineer (main CoFo) from [Ajay Agarwal](https://www.linkedin.com/in/ajay-agrawal-aa79b12/?originalSubdomain=in) (Sirion Labs) done by @Aakash 2025-05-25: On email to @Rajat Agarwal 1. happy to speak and share me experiences w/ Anu. 1. BTW, I’m investing 500k in the SAFE round as well. Anu''s Key Strengths - Technical excellence and clear communication - Strong ability to simplify complex problems into simple language - Skilled at breaking down complex problems for both executives and production teams - Distributed team management capabilities - Successfully led 100% distributed edge team pre-COVID - Managed team of 24 (6 in Seattle, 18 globally) at Sirion - Strong at maintaining tight cadence with distributed teams - Personal qualities - Very humble and grounded approach - Direct but not confrontational in disagreements - Highly transparent in communications - Strong customer empathy and friendly demeanor Technical Leadership Experience - At Sirion: - Managed parallel engineering team of 20-25 people - Focused on AI-native stack for auto-extraction - Led implementation of BERT/Roberta models - Currently 1,200 different models deployed at Sirion - Strong technical followership - Demonstrated ability to quickly build technical teams - Successfully recruited past team members across multiple companies - Highly adaptable to new technologies - Stays current with latest developments - Research-oriented mindset - Quick to implement new approaches Areas for Support/Watch-o...'),
(443, 'Analysis by dev - 2026-02-04: ### Company Snapshot Problem & solution Soulside Al offers an Integrated AI platform for High-Acuity Behavioral Healthcare to automate compliance and documentation, addressing workforce strain (clinician turnover, documentation time) and rising claim denials/regulatory pressure. Key product claims include automated documentation and audit workflows, a FineTuning Engine for rapid payer requirement updates, and a voiceprint-based Group AI. Outcomes cited: reduce documentation time by ~80%, lower claim denials by up to 25%, faster claim submission (4 days vs 22), and avoidance of clawbacks. Ideal customer profile and pricing Target market: Moderate‑high acuity Behavioral Health (including mental health, substance use, eating disorders), with multi-location facilities. Immediate market sizing highlights in the deck point to ~35K facilities as the addressable base. Pricing signals include: ACV pricing ranges around $85–$250 per license per month; additional pricing cues show per-intervention pricing and multi‑product potential (documentation and compliance). Immediate SAM ~ $27B; SOM in the 10–15% range within the near term (3–4B) per the provided sizing slides; TAM cited as $240B with a longer‑term SAM ~ $150B. Status of product & traction highlight Live revenue as of Jan 2026 with ongoing pilots; notable milestones include: - Feb 2025: first revenue; Jul 2025: second customer; Oct–Nov 2025: one customer per week; Dec 2025: >$500K ARR; Jan 2026: live...'),
(444, 'Conversation notes with @Rahul Mathur from 09.07.2024: 1. Founders: 1. [Apurwa Masook](https://www.linkedin.com/in/apurwamasook/?originalSubdomain=in) — ISRO (internship) 1. [Sudarshan Samal](https://www.linkedin.com/in/sudarshan-samal-0267686b/?originalSubdomain=in) – L&T & ISRO (internship) 1. About Co-Fos 1. All from Orissa 1. Went to the same college - VSS Univ of Tech in Burla 1. 2nd year of college is when they began building rockets (2016) 1. None have aerospace background / family background in Govt services 1. Apurwa had a brief internship stint with ISRO in 2018 1. Discovery of rockets happened during alumni day event 1. College had got a ₹50L Grant from ISRO → hence had facilities 1. Worked on a project for local dam → to figure out where sedimentation & silting was taking place 1. Business 1. Order book (includes 2 POs and 1x iDEX order) ~ ₹35 crore at MOQ 1. Since they are building solid propellant→ this comes under export control 1. So while market is global; it requires G2G tie-ups to enable EXIM 1. Will need to invest ₹20 crore into CAPEX for facility 1. Facility needs to be on land which they BUY or LEASE for 99 years since license to do explosives is tied to the location of use 1. Will explore getting land from a defense corridor 1. Fundraising 1. Raised ~7 months ago ₹52 crore pre-money → ₹7 crore raise 1. From Angels only 1. HVB Angels invested $300K 1. Current round will be ₹30 crore on ~ ₹120 crore pre-money 1. In IC with Mounttech (Former Def Secretary’...'),
(449, 'Scoring: **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious | ? | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | 8 | **10** | | Product Chops | 2 | 2 | | S&M Chops | 1 | 2 | | Domain knowledge & skills | 2 | 3 | | Breadth of exposure | 1 | 1 | | Familiarity/repeat work | 1 | 1 | | Advantage | 1 | 1 | |  |  |  | | **EO** | 7 | **10** | | 1-10 strength or some 0 to 10 | 4 | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership | 1 | 1 | | Network leverage | 1 | 1 | | Compounders |  | 1 | | Wealth top decile | 1 | 1 | |  |  |  | | **Thesis** | 6 | **10** | | Good thesis, sizable TAM | 5 | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline | 1 | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(451, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(456, 'AI notes: ### Fund Backgrounds and Structure ### Investment Strategy ### Portfolio Companies ### Future Plans ### Action Items
RM notes: 1. Groww founders invested through Stargazer LLP since 2020 1. 60 investments to date 1. Small cheques 1. Mehta Family was the first investor in Groww 1. This is a CAT 2 AIF - Mehta Equities was the investment manager 1. Got license in 2023 1. ₹70 crore Fund I 1. 39 companies invested to date 1. Early cheques were ₹15L 1. Now doing ₹5 crore cheques 1. Thesis 1. Not tied down to BFSI - sector agnostic 1. Consumer (FirstClub, Zepto, Swiggy, Handpickd, Gaming, Caava, Bold Care) 1. FinTech (excluding Wealth, Lending) - keen on Infra & compliance - PowerEdge, Decentro  etc 1. AI - OnFinance, Snowmountain AI, Maxim AI 1. Have done some Pre-IPO as well 1. Lots of investments in common with DeVC Fund I 1. Cybrilla 1. Finsire 1. Riverline 1. PowerEdge 1. Snowmountain AI 1. Co’s he wants us to check out: 1. [https://www.revway.io/](https://www.revway.io/) 1. [https://babblebots.ai/](https://babblebots.ai/) 1. Fund II 1. TBD 1. Has been proposed 1. ₹120 crore CAT I AIF 1. Want to do more early stage (Seed to Series A) 1. Avoiding pre-IPO 1.
Action items: 1. Modus Secure - [https://www.modussecure.com/](https://www.modussecure.com/) 1. [https://portfolio.devc.com/](https://portfolio.devc.com/) 1. Someone to share a rough evaluation work?
Conversation 2025-10-17T11:44:00.000+05:30: '),
(460, 'Heads up note 2025-10-18T12:00:00.000+05:30 from @Rahul Mathur: Hi team, Sharing the heads-up note for our investment in [Stellon Labs](https://stellonlabs.com/) - an AI research lab that is building tiny frontier AI models that can run on edge devices like smartphones, wearables and embedded system DeVC is investing $250K as part of a post YC $5.2M round at $45M post money led by Felicis Ventures (early investors in Canva, Mercor, Notion etc) *Note: Cash was able to generate pull with the founders given his questions regarding the LPIPS approach and 1 bit quantization; founders appreciated the team’s depth in edge models & therefore created room in this round for DeVC * **Founders** 1. [Rohan Joshi](https://www.linkedin.com/in/rohan-m-joshi/) - CEO 1. MS @ CMU in Robotics (2019-2021) 1. 4 YOE @ Meta 1. [Divam Gupta](https://www.linkedin.com/in/divamgupta/) - CTO 1. MS @ CMU in AI (2019-2021) 1. 4 YOE @ Meta 1. 1.5 YOE @ MSFT Research **Investing Process** 1. **We sourced Stellon Labs as part of the YC S25 structured mining process** 1. Their Kitten TTS model accumulated over 8,000 GitHub stars and 60,000 model downloads on Hugging Face within two weeks of release prior to us interacting with the founders 1. **Cash & Krish did the 1PE** 1. Cash - Maybe 1. *Net: Sharp guys and might just build something specialized, but unlikely going to be something that catches fire. Can see a Mistral like journey* 1. *++ Technical spike is 1 and has the right BG with CMU and Meta (both CoFo...'),
(461, 'Attendees:: | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): '),
(463, 'Scoring (can be copied for multiple people): | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 | |  |  |  | | **Spikey** | `Calculate out of 10` | **10** | | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: ')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(464, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(465, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '),
(466, 'Notes:: Spikey: non 0; <10% that this is a 1. Might surprise on upside given depth of early research he had come with and execution hustle (has 400 users already while building solo) Wants to build DevOps PaaS Render.com without a cloud lock in ; day 0 or whenever, customers can switch to own cloud. Have told him to think productized services like [https://www.percona.com](https://www.percona.com/) for mid market Notes from chat : Grew up in Bombay Undergrad was there Masters in US Tried a startup in 2009 - ed-tech Had a choice between Nykaa and Clevertap Why deployment Io ? AT Dezerv didn’t prioritise dev ops Felt that is the same at all cos Devops can be automated using AI Vision is to build an assistant for Devops and SRE for early teams They deploy on users AWS unlike render where when you scale you’d have to migrate Some kind of a PaaS experience on AWS Have around 300 users from 40 countries Wanted to build distribution first | currently all individual  developers Q to him : How do you solve distribution ? Easy to catch render type ICP ..but harder to solve distribution ? Two people right now. Full time is only Ankit. Another CT developer is part time Have built a Devops assistant too MLT becomes simple and chat based
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ...'),
(471, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(472, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: ')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(474, 'Notes:: 1. **How did we connect?** 1. Raghu from PB 1. Raghu is a friend 1. He is being advised by Umang from CarDekho Group 1. Recently did the NCR visit circuit 1. **Pranil** 1. From Mumbai 1. South — suburbs — Ghatpokar — Powai now 1. GUJ middle class household 1. Dad is a trader of dry fruits & dates 1. Engineering — KJ Somaiya 1. MBA - GIM Goa 1. Citi banker for life 1. UHNI wealth mgt — ₹45 crore portfolio 1. Ratan tata family office client 1. Specialized domains across identity, fraud & risk 1. Karza 1. 0-1 journey as Product person 1. 8 member team at joining 1. 250 team at exit 1. Resp. w/ CTO to hire engineering staff of 150 1. Making 20L in revenue at entry 1. Making 85 crore in revenue at exit 1. Sold to Perfios for ₹650 crore 1. Built video KYC product + sandbox 1. Industry 1st product — reference check for onboarding new hires 1. Left a lot of money on table leaving prior to acquisition by Perfios 1. MetaMap 1. Moved to Mexico city for a bit 1. 15 member team (non-Indians; LATINO, EU etc) 1. $700K revenue in one year — self serve channel 1. Distressed sold to a global giant 1. Bureau.ID 1. Scaled x5 revenue on identity side 1. Head of Product role 1. He stumbled upon Tenacio 1. Waited for a long time — built for others; now for self 1. **Learning** 1. Perfios made Karza’s identity into a non-sexy industry 1. Identity biz is 85% GM — but lots of inbound competitors which brings the margin down 1. Karza growth rate is ~8% versus industry 20% 1. New players eating ...'),
(478, 'Meeting at the founder’s home 2024-08-29: Attendees: @Anonymous, @Aakash and @Rahul Mathur 1. Conversations with Mallika were very helpful - didn''t want to let her go after 45 minutes 1. Want to speak to Shashank from TWT but he hasn''t responded as yet to their message 1. Questions they asked - How is DeVC money invested? - who from DeVC would be leading the investment? - Is any board seat required? 1. General Qs they asked - Do we give a board seat? - what are drag rights? - should we be worried about exit clauses? 1. Have asked for one day to come back on the ₹2.5 crore + ₹0.5 crore allocation 1. Advice given by team - Move as many of the items to CS as possible - Push Fireside to close DD ASAP 1. Business right now - Doing ₹70L revenue - have a single fabric right now - going to China to speak to manufacturers to source one more new fabric 1. Other observations - Adith from Zepto is a friend, he has been giving them QC search data - CoFo has a sewing machine in her room which she uses to create samples - Founders aren''t surrounded by the right mentors, these are product marketers - Choksi''s family business on husband side is precision medical equipment which is sold to all types of hospitals and clinics - they have offered to help with MedMitra
Meeting at the founder’s office 2025-03-03: -'),
(479, 'Heads up note 2025-08-27T15:18:00.000+05:30 from @Rahul Mathur: Hi team, Sharing the heads-up note for our investment in [Tesora AI](https://tesora.ai/). It is an AI procurement analyst that streamlines the work of a sourcing team; starting with Hard Tech industries where qualified engineers earning $150K+ per annum are required to make calls / write emails to secure necessary components for complex systems. DeVC is investing $200K via the standard YC SAFE @ $20M Cap; this is a $3M round **Founders** 1. [Vivek R](https://www.linkedin.com/in/vivek-r-928871173/) 1. 2 YOE as PE investor at Sycamore Partners ($14b AUM) 1. 2 YOE @ McKinsey & Company 1. BRC from [Aditya Sukumar](https://www.linkedin.com/in/adithyasukumar?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app) (EM @ McKinsey) 1. *Top performer. Great technical skill set.* 1. *Definitely top decile compared to analysts and associates. * 1. *Would do whatever it took to get it done* 1. *Staying super late and being last one out was norm with him* 1. *Would you blindly back him: YES* 1. BA/MBA in Economics & Finance from UChicago; MBA was on full scholarship 1. [Federico G](https://www.linkedin.com/in/federico-reyes-gomez/) : 1. 3 YOE @ Kumo AI as founding engineer (fastest promotion) 1. *BRC from Viman Deb (Head of Product @ Kumo AI)* 1. *Fed is top 3 engineers in my 16 years career* 1. *Went on his own to use his extra time to be part of the solutions engineering team and going to customers. *...'),
(482, 'Notes:: **Views:** Yashi: Strong Maybe (should do more work with a 2PE) **Spiky: **0 **EF/FF: **FF **Founder Archetype: **6 **FMF: **7 **Thesis: **6 + found him very close to 0.5 spiky, is commercial and thoughtful + knows what he is building well – could answer 2-3 layers of questions ? working on building speciality textiles for various use cases across industries (more B2B than B2C) – should deep dive + has executed reasonably well within the limited time: got great customer logos on board, one core selling product and an R&D person from domain + Decent traction with high margins: 0.5 Cr MRR with 2.75 Cr in written orders, 16% CM3 average ? need to take all of this keeping in mind the history of building in textiles ? would like to diligence on the defensibility of the product and how real the pipeline is **Notes:** **Team** [Mayank Tibrewala](https://www.linkedin.com/in/mayank-tibrewala-9abab817/?originalSubdomain=in) - Background: - Born and raised in Mumbai in a Marwari family - Father was former CFO at WellSpin India, now runs his own CA/auditing firm - Mother is a homemaker - Has a younger sister who is a CA and IIM Lucknow graduate, working in private equity - Education: - Studied Aerospace Engineering at IIT Kharagpur - MBA from IIM Ahmedabad - Career: - Started at Arete Advisors (consulting, acquired by Bain) - Chief of Staff at Asaan Jobs (acquired by OLX) - Led global denims business at Fashinza ($15M ARR) (1 year) [**Akash Kalra**](https://www.linkedin.com/in/ak...'),
(483, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(485, 'Notes:: Ankit, Sahil - Both delhi, Modern and VV 2002 batch - Ankit – UK, CA, BNP Paribas - Sahil – IIMK **Ankit and Sahil started Dineout** - Lots of consumer insight and customers moving favored it as a booming industry - Restaurant tech platform - Supply chain management - Dineout passport - Payments - Close to 100mn users annually; 0.5bn GMV - Acquired by Swiggy – Jul 22 - Ticket size went up – earning 200rs / order Took 10% cash, rest Swiggy stocks Integrated Dineout till Dec ‘23 **Jan ’24 went into gardening** - UK wait times are 2 years – 8mn people waiting for a surgery; unofficially 13mn - Last trimester didn’t meet the doctor - Why are people not travelling to India 99% of travel comes from developing nation – Bangladesh, Africa, etc… - Agent driven - Agent network in both countries is strong – there are 6 agents involved - Hospitals themselves are holding camps, etc From Europe, people aren’t coming to India - 2019, 200k - 2023, 0.5mn people going to Eastern Europe 2 arbitrages at play - 3 year wait becomes 4 weeks - Avg private care of GBP 25k is 15k in Eastern Europe Why are people not coming to India? - Lack of trust in Indian infrastructure - 60k doctors in NHS are Indian - Lack of after care - Hospital stay is just 20% of the overall country - Guest houses have sprung up for these - 1-2k where attendant runs around - Or 5 star which is expensive and no after care - What if there’s an issue in case something goes wrong after I come back - Problem is the UK doct...'),
(486, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(488, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(491, '**Dhairen - Maybe for DeVC; Clear no for fund considering founder archetype**: Spikey 1, especially considering he is a 21 yo building in fintech - ++ High agency and strong clarity of thought for a 21-year-old founder ++ Outside in, numerate and analytical - tracking all the right metrics, sahi customer reviews mining, thinking about the right expansion levers - ++ Outside in, numerate and analytical - tracking all the right metrics, sahi customer reviews mining, thinking about the right expansion levers - ?? Don''t love the product, don''t see any edge and app is glitchy - ?? Is there a real product edge or is it just an ICP play - ?? Quality of user - 3k CAC, 8-10k ARPU are not top tier metrics; also, how much can one sweat this ICP? **Meeting Notes** **Company Overview & Current Status** - Trackk - AI-first mobile trading platform targeting Gen Z (18-30 age group) - Youngest company to receive direct broking license (obtained 4 months ago) - Previously operated as sub-broker, now direct exchange registration - Founded when CEO was 18, now 21 years old (5-year journey) - Current metrics and traction: - 1.3 lakh total signups on platform - 30,000 DMAT accounts opened during sub-broker period - ~1 lakh trades processed monthly (when sub-broker) - 90% user retention on current insights platform - 85% of user base acquired are first-time traders - Funding round structure - looking to raise ~$3-3.5M at $13M post **Platform Architecture & Technology Stack** - Core technology built...'),
(493, 'Notes from @Yashasvi Madhogaria as of 2024-08-20: Adding the notes, deck and latest update from Tradeface – another company building in retailer supply chain with a vision to leverage ONDC – have started with a small pilot **AS Views: (as of December’23)** Overall: PWC as Maybe on founder, but extremely low margin, competitive and commoditised business. - +Good pedigree teams. Classic EOs - +Insightful, 2 order thinking + outside in nd - + Commercial – whole thesis is based on doing wholesales online but profitably - ? Low margins – Udaan business essentially and subscale – no clear margin expansion lever - ? No real tech moat in the business, ONDC as an enabler but not core - ? Monetization and value prop **Meeting notes** [Sebastian](https://www.linkedin.com/in/sebastiangvempeny/?original_referer=https%3A%2F%2Fwww.google.com%2F&originalSubdomain=in) - 19 years of experience - Started with Citibank – liabilities, sales etc. - Metro cash and carry – was leading the trader(reseller business) - Then moved to Udaan – trade marketing for 3 years [Shivaram](https://www.linkedin.com/in/shivramdega/?originalSubdomain=in) - Tech guy, ex Co Founder of Xero Apps - Engineering Team lead at Paytm Insider (3 yrs) - Software Architect at Capital Float (4 yrs) [Vaibhav](https://www.linkedin.com/in/vaibhav-verma-16a1115/?originalSubdomain=in'') - Ex head of pricing at Udaan (3 yrs) - Senior GM of Pricing at Metro cash and carry (10 yrs) - NMIMS MBA Problem: - Earlier Kiraanas were family busi...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
