INSERT INTO util.enrichment_staging (company_id, content) VALUES
(88, 'Discussion on 20.09.2024: 1. Cash flow position 1. Learnings so far 1. Business right now 1. Discussions with others 1. Next steps 1. RM Reflections
Investor updates (since RM is an Angel): [Page: April 2024 Update] [Page: May 2024 update] [Page: June 2024 update] [Page: July 2024 update] [Page: August 2024 update]'),
(90, 'Z47 meeting 2025-10-23: KK Overall view: WM for DeVC Spikey: 0 to 0.5 ++ resourseful ++ hustler ++ intellectually honest ++ outside in ++ staying right things on thesis ?? numerate not much ?? not commercial ?? no consumer insight TK Overall View: WM to Maybe- for DeVC and WM for Z Spikey: 0 Spike Needed: consumer/product and exec ops ++ hustler and hardworking ++ highly iterative; take  customer feedback and improve ++ Jugaadu types; copy insight from other companies and them execute ++ Dhandha mindset ?? Not brand builder types ?? still have more drop shipping mentality; look at trends and some learnings from Kishore biyani; quickly copy it without thinking much ?? no unique thought process ?? trying to too do many things at the same time ?? no key differentiation Detailed Meeting Notes (23.10.25) Founder Background - Vedang (22), Psychology major; started Clapstore in 2020 during COVID lockdown while in 11th–12th grade - First-time founder from a family of educators (mother: govt college lecturer, father: tuition teacher); driven by desire to be first in family to build a business and have autonomy - Initially aspired to join defense services; COVID shifted focus to entrepreneurship—started with dropshipping via TikTok (US market), scaled to ₹6–7L per month before facing supplier scams - Transitioned from dropshipping to buying from manufacturers and managing own packaging/dispatch; later evolved into designing and manufacturing products after discovering success with non-...'),
(92, 'Ref from Anand (CEO @ MinIO): Got a ref from Anand, CEO @ MinIO; Great kid and sharp, but concerns on 0-1 and will leave this in the pass category for us. - Top 3 engineers for his tenure that AB has seen over the years - Problem solver and will be able to figure out any domain you through at him - Steep learnings curve - Humble, seeks advice, etc - H&H - worked amongst the hardest in his team ? Needs direction for 0-1. someone has to guide him the right direction. Can solve problems, but needs a guiding hand on what problem to focus on; ? Not angel investing because of the domain. AB doesnt get the space and not sure why sid picked it. Detailed notes Anand context - deeply involved in product and engineering side - he was part of our AI team - he was under 2 other AI leads - He started as an intern - he was a fresher but worked at a senior engineer levl - he was part of senior discussions as well - very good problem sovler - he is the perfect kid every parents dreams of - very skilled, hardowrking, no bad habits, sharp - He works really hard; hardest in the team - Skillset wise - fast learner - very sharp learning curve - how you think about rpoblem solving and picking the right approach, he had good clarity - what i dont know enough - his domain in real estate - picked real estate as a market but i cant guage enough on wether its a real problem - realtors are bad customers - dont know how big it is - Relative grading to others - dont like interns - but he was one of the few...'),
(94, 'Ashwin''s Series A Notes - Summary - 2026-01-30: **Founders:** Akash, Neel, Prajwal - All IITM ''22 grads, no prior work experience. **Round:** Series A - $10M raise, wants $80M post. Has offer from US fund at lower valuation. **KP Views:** WMB and pass - also speaking to seed investor for reference. **NOTE FOR V:** FYI in case you''d like to meet them, but Ashwin doesn''t see us doing this round. --- **POSITIVES** **Tech spike:** Strong technical team solving tough challenges. **Founder quality:** "Akash is sharp and spiky on intrinsics. Not overly aggressive, but he''s consistently been at it." **Traction (~$2M ARR):** Added ~$1M ARR in last 6 months. --- **CONCERNS** **Thesis - AI-first Loom:** Shoot explainer/product videos with AI voiceovers, graphics, auto-zoom. "Started with L&D, then moved to sales, then customer success, and now thinking of jumping to marketing. Overall, the approach feels too iterative for my liking - throwing 10 things at a wall to see what sticks." **GTM:** "Growth is good, but there''s still no repeatable GTM motion. It feels sporadic and heavily LinkedIn-driven (founder posts)." **ACVs:** Mostly less than $5K. Largest enterprise customer ~$40K, but most are small teams. **Auto content updating:** Looking to launch feature connecting to video repositories. "Companies like GitHub have dedicated teams for this, so it could be an interesting thesis. But given how much they''ve jumped around historically, I''m not confident this will stick either."'),
(95, 'Marketscan & Breakdown by Trinika 2025-09-12: Hi Team, Adding the breakdown of market landscape and workflow in the excel here Quick summary of key questions below: ![](cid:3199483326*image001.png@01DC22BC.55A4C510) Is the problem big enough? - Yes, because in a content/video production process, three prep tasks - proxy creation, renaming/restructuring, and audio–video sync - together take ~5-7% of the total production budget and ~10-15% of assistant editor time. - Example: a 60-second ad or micro-drama with 4 cameras and separate sound typically needs 20-30hrs from AE before the first cut - iteration speed is higher for microdrama so faster speed req - TAM (for these three steps): Global ~$3B; US ~$1.2B. - SAM (automation wedge): Global ~$1.5B; US ~$0.5B. - At 10% penetration of SAM: ~$150M ARR global; ~$50M ARR US Big gaps in workflow today? - Camera card to storage: For most cameras, copying from card to local drive and cloud is still manual. Only Canon paired with Frame.io (Adobe-owned) auto-copies to both. - Transfer & naming: Cameras save files as C0001 or A002C012; editors need script-friendly names like Scene3_Take5. Renaming remains manual. - Project & bins: Folders nomenclature varies from agencies to agencies – some do it by - day, by actor, or scene. No tool auto-restructures into clean bins/folder by scene/shot/take. - Audio–video sync: Tools handle clear lip-sync, but struggle when lips aren’t visible or timing is creative. Example: a voice-over on a montage, or...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(96, 'AI notes: This transcript captures a reference check call with Rohit about Vishal, a former colleague from LiveSpace, followed by a discussion about Aptile''s upcoming product launch. Reference Check on Vishal Background and Role at LiveSpace - Vishal was among the first four team members at LiveSpace - Worked at LiveSpace for 5-6 years (2015-2021) - Grew from software engineer to director of engineering - Headed the CMS and pricing engine for on-demand construction of home interiors - Managed complex technical systems independently without much support Working Style and Strengths - Described as reliable, dependable, and level-headed - Technically outstanding and thoughtful in decision-making - Calm demeanor, especially during conflicts or heated discussions - More prepared and thoughtful before communicating ideas - Works well with different personalities in cross-functional settings - Considered among the top 5 team members Rohit has worked with Areas for Development - Not naturally charismatic or outspoken in communication - Might face challenges in business model development and identifying margin opportunities - As a technical founder, may need complementary skills for business aspects - Would benefit from hiring team members with complementary business skills Aptile Product Launch Discussion Action Items - [ ] Rohit to prepare and send early access package including: - [ ] Rahul and Mohit to help promote Aptile on LinkedIn (they have 110K and 50-55K followers respectivel...'),
(97, 'Received from Rahul - 2025-11-09: https://www.linkedin.com/in/ashishpratapdoshi/ <- CollektAI in Collections - came up in convo w/ CRED Cash Collections POC who Miten introduced me to Screen | P0 | POC: Rahul Mathur ---'),
(98, 'Received from Rahul - 2026-03-13: Building in Fintech - PFM with a great wedge. This is a short blurb: CA sees taxes, not investments.  Broker sees investments, not liabilities.  Bank sees balances, not goals. India''s 2 crore ₹30L+ income households have three advisors and no one who owns the outcome. Command is that entity. A personal finance agent that unifies accounts, loans, taxes, and investments and converts the full picture into proactive, executable actions. Before you ask. India''s Account Aggregator framework makes unified financial data real. AI makes continuous personalised optimisation possible. The financial rails are live. We''re building above every bank, broker, and insurer in India, the default decision layer for the end customer, the operating system for personal finance. Ankur Garg (Ex- Great Learning, Capital One, Morgan Stanley), Varun Gupta (Ex- Embibe, Ola, Linkedin) ---'),
(101, 'Background & Experience: - Previously at Microsoft in OfficeAI team, led voice experiences (grew to 6M users) - Led product work on Microsoft Designer team (AI-native design engine) - Worked at Prathyush as first PM (10th/11th employee) - Left in December to explore new opportunities
Market Strategy: - Targeting two segments: - Testing with both segments to identify common primitives - Sees opportunity in Canva’s current “bloated” state with AI features
Overall: Weak maybe: EO: 6-7 | Thesis: 5 | FMF: 6-7 | Archetype: 7-8 | Spike: 0.5 ++ Has the product spike but to omuch meandering SPC archetype with little focus on GTM ++ Is thoughtful and assimilates inputs and feedback ?? Wants to build a creation tool for creative agencies ?? Hasn’t spent much time. Thinking and prouct protype that she showed was poorere than first set of control net product workflows seen in AI community ?? Lacks the GTM muscle both for prosumer growth and b2b sales led ?? Wasn’t deeply calibrated on vairous plays beyond krea and more horizontal tools
Current Project Overview: - Building AI-native video editor with custom workflows - Key features: - Started development ~3 weeks ago - Testing with initial partners:
Technical Approach: - Focus on solving iteration challenges in AI generation - Built on open source models - Aims to reduce costs (target: significantly below current $100 cost for multi-tool workflows) - Integrates multiple capabilities:'),
(103, 'Prep 2026-03-19T23:33:00.000+05:30: Confluence Labs (YC W26) | confluence.sh What they do AI research lab building foundation models optimised for learning efficiency in data-sparse domains — drug design, materials science, hardware engineering, physics discovery. Their thesis: modern ML only excels where you can collect massive training data. In domains where data is expensive or slow to generate (physical experiments), current AI fails. Confluence''s approach: combine LLMs with discrete program synthesis to maximise what you can learn from a small number of experiments. Two-track strategy: 1. Hypothesis generation — AI that designs maximally informative experiments so each one teaches you the most 1. Data-efficient modelling — program synthesis + LLMs to make predictions with far fewer data points Technical milestone Came out of stealth with 97.9% on ARC-AGI-2 at $11.77/task — SOTA at launch (Feb 2026). ARC-AGI-2 is considered one of the hardest AI benchmarks in the world (tests novel reasoning from just a few examples). Approaching 100% on what was previously considered unsolvable. Open-sourced the solver. Backed by YC and Paul Graham personally. --- Founders 1. Brent Burdick (Co-Founder) — [LinkedIn not publicly indexed] 1. Niranjan Baskaran (Co-Founder) — linkedin.com/in/niranjan-baskaran-a906a5205 Both are extremely young (combined age ~43), no traditional industry pedigree — pure research talent profile. The Paul Graham backing is notable signal here.')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(105, 'Ashwin (ContextFort) <> Ashwin (Z47): Met Ashwin @ Contextfort. SMB just based off intrinsics. Should track to see how their thought process and customer backwardness plays out over the next 2-3 weeks. + High IQ + H&H. Also scheduled my call at 11pm Saturday “working all day round”. + Conviction + “I don’t see the reason to waste time at a job and not startup. Starting up is the only thing that makes sense to me” + Customer backward. But not a spike – spoke to customers with every idea, but only have 4-5 conversations. + Thoughtful approach to picking the right problem +/? Thesis – right no building in construction tech. a platform to help architects and GCs collaboreate better. Previously was focussed on security for AI, . i.e., prompt injection and so on. ? Very out of domain ? Need to get a read on resourcefulness – are they able to generate more conversation in a few weeks. ? team building +/? Refs – soft ref from Anand was good but he’s his uncle. Intro came from Anand (Uncle) Next steps: - Meet in the U - If this is not a conflict for Kanav, we can connect them for a chat – PD what do you think? Detailed notes Ashwin <> Ashwin,Z47 Sat, 26 Jul 25 Z47 Fund Introduction - Ashwin, partner at Z47 (formerly Matrix), shared background: My Startup Journey - Currently working on construction tech startup focused on contractor-architect communication - Previous startup ideas explored: - Background: Networking & Next Steps - Working schedule: 12-6 PM and 9 PM-3 AM - YC cohort conn...'),
(106, 'Notes:: Cookr Wed, 13 Nov 24 About the founders • Prabhu is the cofounder and CEO • Has a background in technology, worked at Microsoft for many years • Built Xbox consumer business and Xbox Live platform • This is his second startup, first one was in healthcare but didn’t succeed due to COVID • Other cofounders have backgrounds in food, technology, and packaging What is the business • Category marketplace for clean food and food products • Connects consumers with home kitchens for food delivery • Focuses on health, organic, and gourmet food products • Aims to provide home-cooked style meals through technology Scale of the business • Year 1 (FY21) - 96L GMV, spent around 10 cr • Year 2 (FY22) - 9.4cr GMV, total burn 16-17cr • Year 3 (FY23 target) - 20cr+ GMV, 30% take rate so Net Revenue 46-47%, -45% Net EBITDA, Burn 68L/month • Current monthly sales around 1.3 crores Operations • Initially had their own fleet • Now moved to 3rd party fleets (Porter, Dunzo, Shadowfax) • Facing challenges with Dunzo exiting the market and Zomato Blinkit pulling out • Building their own 3PL now • 52,000 chefs registered and waiting to be onboarded • 1300-1400 active chefs currently Consumer Insights • Core consumers: 28-45 age group working couples, 65+ senior citizens • Offers subscription meal services (30-day lunch/dinner plans) • Provides party meals for small gatherings (15-20 guests) • Menu focuses on home-style food not typically available in restaurants • Allows customization of meals W...'),
(109, 'Notes from Ambika Pande 2026-02-07T16:24:00.000+05:30: 1. Unfortunately haven’t really gone deep into the E-Rupi use cases so wont be too much of an “expert” here. But from what i understand, its not a hard to replicate product per se (you’d know this as well as me : public rails = limited infra moat) - so it really depends how cotodel is going after the market. If they’re trying to solve for “spend management” as a whole - then maybe could be the Ramp version of India, but the differentiation is definitely not going to come from E Rupi. 1. Another core problem (high level - this is just my understanding of how erupi works) is that the spend is constrained to merchant category. In India MCC code mapping is still a very real problem, every 3 months there used to be an issuing blowing up at Rzp regarding this. In fact - a friend recently went to sell a suite of products to Kotak, Kotak was the most interested in a MCC predictor product, since that’s what they still have a lot of problems in 1. Another point is merchant acceptance - my hunch is if it’s another method, the acquiring bank / PSP needs to also build that acceptance and integrations, how scaled up that is and if everyone offers - that’s something I’m assuming you’d know better than me :) but haven’t heard about it being a “big bet” anywhere or serious buzz created around it, so it’s either a small effort (which is a good thing) or not a focus area at all'),
(110, 'Product Overview: - Computer vision-based quality control system for textile knitting machines - System includes hardware box and user interface installed on each knitting machine - Detects fabric defects in real-time during production process - Reduces fabric wastage from ~1.5% to 0.1% through early detection - Currently covers 80% of common fabric types - False positive rate: 1-2 per day per machine - Each unit has 2 cameras for different angle detection
Market Opportunity: - Global market: 300,000 knitting machines - India market: 50,000 machines - Annual new machine sales: - Current focus markets: - Estimated global waste: $18B worth of fabric lost annually
Go-to-Market Strategy: - Two-pronged approach: - Currently prioritizing brownfield installations for next 6 months - Building brand recognition through “Nitai fabrics” certification
Business Traction & Financials: - Revenue: 7 CR expected by March 2024 - Current customers: 5 clients across India, Turkey, Uzbekistan, Bangladesh - Sold approximately 100 units to date - Unit economics: - First major customer (RT International):
Notes:: Overall: Maybe + EO: 5-6 | FMF: 5-6 | Thesis: 7 | Price: 8 ? Spikey : 0.5 Thesis and early adoption is dead center Worry how spikey these folks are, but usually a gap with this SaaS like archetype. Should rely on BRCs Slightly a capped a market to go after but if they can expand through the value chain, can outsize. Again goes back to Spikeyness Community cheque no brainer with Vasant & Nit...'),
(113, 'Deck from founder 2026-02-11T12:27:00.000+05:30: [File: attachment](https://prod-files-secure.s3.us-west-2.amazonaws.com/b21975bb-aebf-48e3-8c44-1573c4404129/07bf4ded-724a-46ba-9442-f9045d7a79a5/Credeau_Company_Deck.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAZI2LB4666H55BL52%2F20260320%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20260320T102946Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGgaCXVzLXdlc3QtMiJIMEYCIQDSnRcEmWYDQ9yVld8NSOK%2BcWTKqy%2Bw8s6TziCz2W0C%2BAIhAOgKliBiE0U28ZZ%2BQbLwptVo5FKoLoMiSpFyYOFOs2peKv8DCDEQABoMNjM3NDIzMTgzODA1IgzHEyp%2F8bVsDPdU46gq3APKNZCj6Y64G9%2Fdif36RIc9h87aXvcs6HxA83oaXtPWdEcFdLDm%2BC8ouKjbE2Uajqf00N7LGQM7y6aCjdgkoyPgdDYAfxM%2Fm5MghD9HV3Wi49WzmlgTPebb4wsWjmlWppdE2YNhBHD76rAE0wzyzovohPTsLi1xpLhZm7JEq%2FQl7e%2B68bbDz2XCx1MYGay%2Bpjo6EDCF3NV9W3GY2SZKRFOpWCh1Cjozzwthx44r9oQDRHO9FNUuQKe0THFTCV%2B1uHS%2B6AH5GwLrh33j%2F2BjTAC4zsBQPJKkN0SGRdoYSgbpUt5KHlYz%2FwSFtnIxTH5H8C4LrRT0QGwBej%2FywnXWruUE6eRdLoCLRnOMb3Wg1PCETQm91sGkJjKuS8JMOEDG2SHyzFTccspQ8UTizKUlACIte89UFaL3ySziAmq%2FW1kha5ed4zHdAxpHtmJ3ODOcnCohiWAjnb0C2%2Bq4iwIpYc%2FAvzd3pEms0lwzZomGTF4807P3sRbaATU1RSK2W4AqLWwHSiOXRbtuZyu1oRu9gH%2BdjnGwY57kFMDmrW%2Bo65Sajz9M%2FMKfbKM5QCI%2BoaBOTIqo9H3eOHInq83Kz7zVwXnwZiQuHnyrz1eIuhMcFVrCR2OZJ%2FfMwaIW5K1c1zCm%2FPPNBjqkAQAOgKRTv1EJKpKguGFrODtHAQyYaA7ksIGVPRGZYcIX9QuFHDprIR5RazFBfkn%2FRSgMIpKE2DlcbmlaqHa0yyk4mGjr5K59INnWEex7diNUTgkKfYRKR9QRTuYj2vXXP6Vb8Lz4l5Xwy2wK1Oczxsq%2BU5E2gW%2BAh4MWhBLIW0c1xQH7...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(114, '++ Continue to be outside in, asked DT questions about the comps and market: Notes 1. Fundraise 1. Business progress 1. Next steps 1. Others 1. Landscape view
Follow-up conversation with Founder on 2025-01-11T19:55:00.000+05:30: 
Attendees from DeVC: @Rahul Mathur: 
Notes:: 1. InfoEdge is the lead 1. Said no to Groww as a strategic - got connected with Harsh via Nitin Gupta of Uni Cards 1. New strategic wants a sizeable chunk (Ashish Kacholia & his family office) 1. Trying to push InfoEdge to 15% and Strategic to 7% 1. Is going to see how to squeeze us in for $30K if Cash is interested ---
Pranay <> RM (GFF - 2025-10-08): '),
(115, 'Notes:: From @Rahul Mathur Spiky Score [Table] EO/FMF/Thesis/Price Score [Table] ? Tech leverage — can they build for Wealth? ? Community + Understands ICONIQ & has examples 1. Legacy planning for children 1. Concierge eg meetings with ministers, profile management 1. CIO, CFO business and CMO business 1. Easy to fire CIO but not easy to fire CMO and CFO 1. 2nd gen is super intelligent - they will make money 1. Wanted to start PMS for foreign nationals but realised this is a distribution business 1. Consults with Amit Ranjan family office who does this with Kotak but hates Kotak because of PMS tax headache 1. 6 months - 40% AUM moves with wealth manager themselves 1. HQ Mumbai -> Girish and research team in India 1. AIF will be in Dubai 1. Want to launch a RE FOF 1. Estate planning in DIFC -> advisory in Dubai 1. Mentioned ICONIQ - long term play 1. Work with well respected and well networked people 1. Work with long term builders 1. SecFi -> USA based Serengeti capital gave a $600M credit line for loan against private shares with no recourse 1. Knows about Offline, private events are the way to go. Audience wants long format content 1. Curation - will have to say no to people What: Fractional family office platform
Notes:: Learnings from different journey for Zuhaib - Wealth management for 2nd generation is not focused towards creations - I was more curious on creating wealth rather maintaining - For the last 4-5 years Girish have been investing for our friends and known eac...'),
(117, 'Evaluation Plan + Key Questions to answer: 1. What does the company do? 1. Do we (DeVC/Z47) have a thesis on this space? 1. What are the top 3 questions to diligence? 1. Who has piped this company to us? What are their views? 1. What do refs say about the founder? 1. What''s the DeVC team views? 1. What are the Collective signals? 1. Why is this company likely to be special? 1. Who can help? Experts / Venture Partners? 1. Deal dynamics? Potential deal to do? ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: '),
(118, 'Notes:: I met him yesterday and Maybe + for DeVC for a 100-200k cheque including angels for me. Spikey 0.5-1 with a clear spike on strategic thinking / execution that comes across through how he has built out / pivoted his last business (healthy company even though not large outcome) and his journey to get to strong flywheels with this one + SourceX is the hidden flywheel here – he’s created a B2B tool for all shoe resellers to list their products across his + other shoe marketplaces making the reseller life a lot easier (reseller-specific unicommerce) + As a result, he has 16000 unique catalogue, while next largest marketplace has 800 + This drives strong word of mouth in a segment where demand isn’t an issue, and shows up in high marketing ROI – 11-12L spend for a 3cr+ GMV (and net of 45L for him) + His growth will come from building this across hype resale categories (is launching for watches and t shirts) + Taking the same platform global – India is a small part of the global reseller market His round with Infoedge is closed (2mn at 10.5 post he said). I’m pushing him to speak to Collective members and see if we can top up in this round if there is excitement at our side. From him, he sees value of getting angels who can help him - Go across categories and build out the marketplace model - Go international at the right time
Intro conversation with Founder on 2024-10-10: 
Attendees from DeVC: @Anonymous: '),
(122, 'Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(124, 'Evaluation Plan + Key Questions to answer: 1. What does the company do? 1. Do we (DeVC/Z47) have a thesis on this space? 1. What are the top 3 questions to diligence? 1. Who has piped this company to us? What are their views? 1. What do refs say about the founder? 1. What''s the DeVC team views? 1. What are the Collective signals? 1. Why is this company likely to be special? 1. Who can help? Experts / Venture Partners? 1. Deal dynamics? Potential deal to do? ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: '),
(127, 'Prep 2026-03-19T21:50:00.000+05:30: Docura Health — AI-native med-legal platform that automates medical record review, chronologies, and report drafting for workers'' compensation cases Founders: 1. Akhil Sachdev (Founder & CEO) — linkedin.com/in/akhil-sachdev Market: - Market: US workers'' comp = $60B industry; every claim requires multi-thousand-page record review - ICP: IME/QME evaluators, claim adjusters, insurers, legal teams - Product ships: QME, IME, AME, P&S, Supplemental report templates; AMA-compliant impairment ratings (5th & 6th Ed); AI-generated first drafts from uploaded records Prep: - Introduce DeVC & Z47 Healthcare IT portfolio - His prev employment was at Commure - Cash going in view:
Key Qs: - How did you land up at Commure from Siff AI & Rivian? What part of stack at Commure were you working on? - Wedge? - What does this lead to? - Why & when start this company? - Early POCs & proof points - GTM - how? - Onboarding friction - Solution depth - Funding - Comps
Ref on Akhil from Shubhan (Answers AI CoFo) 2026-03-19T23:28:00.000+05:30: 1. I’ve known him since I was a first year student, we lived together for 1.5 years 1. Akhil worked at Salesforce, Athelas and was very passionate about this pain point so he quit Athelas before raising venture and as a solo founder 1. I remember friends telling him that’s a hard move but he backed himself and I’m not sure about his exact numbers but he went at it solo for 6 months until his traction and product was great. He did ...'),
(128, 'RM notes: 1. CoFo Thakur 1. Friday 1. Dad is HAC contractor 1. Built donatioj app for NGO 1. 4th year - dropped out 1. Built AI scraper on Antler 1. No one cares about how SAP configured → Only care about how pocess works 1. Went after companies with COE teams focused on SAP | $50M to $500M 1. Case study: $3bn conglomerate (?) 1. SAP BDP partner - iPAS (?) 1. Top SAP partners 1. SAP AEs are partnering via back door 1. Mark Ken - SAP North America - is his advisor 1. Prev VP of Cloud Implementation at Deloitte - in pipeline (?) 1. Pipeline of $2M 1. Fundraise 1. Pricing 1. Lookin gto get non-YC operators on cap table ||
RM Reflections: Maybe for Collective Top Up | FF, Spiky = 1 | meeting was a downer | believe Collective Top-Up here is the best  approach | Cash is best to comment on founder comp v/s Ressl AI & Sookti AI: ++ Do see strategic thinking here - built advisory network, working on talent pipeline, warming up SAP network for co-branded GTM ++ Seems like a person who will compound fast ++ Has sold micro SaaS products via acquire.com called Friday to Springworks || acqui-hire type scenario ++ Thinking about GTM right way; tagging along with SAP AEs to do co-GTM ++ Certainly outside-in founder || aware of his peers ?? Decided to pursue “boring & unsexy” business ?? Worried that he is an FF who is NOT coachable despite asking for coaching & help ?? Worried that he is the self destruct / creative genius type FF who can implode if things don’t work His demo: [Link: https:/...'),
(130, 'Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---'),
(131, 'Notes from Z47 Consumer team on 2024-04-17: Views DG: WM; should pass to DeVC EF: 2, FMF: 5, COB: 4, Thesis: 7, TAM: 5, Traction: ?, Pricing: ? + Reasonably outside in and understands the consumer + Decent FMF which shows in thesis + Some product IP edge + Strong thesis with a differentiated GTM ? Limited India B2C TAM ? Did not see any spike to justify US or India B2B sales plan ? Pre-revenue with no proof of product ? IF founder Do believe someone senior will build in this space, hence should follow developments Founder: Abhishek Sahu Background - BE (Information Science) @ BNM Bangalore (2019) - Product manager @Ultrahuman (2,5 years), Software engineer @Zomato (1 year) Personal/professional journey Venture Problem  statement Product - Trackers Competition GTM Learnings from Ultrahuman - Success on crowdfunding platforms like Kickstarter - enables word of mouth - QVC is also a great channel in US TG - 30-50 folks who have problems sleeping and also have the most disposable income Current product stage - Prototype done - and have identified vendors as well Unit economics - 500 dollar discount to 8sleep and hence a $1799 costing Vision - Need nearable tracking and not wearable since you can pack only so many trackers in one ring - Nearables help you surpass that Current product capability - Temperature control though the hub - Can change mattress temperature as well and ambient temperature via smart ACs - Will add air quality, humidification etc - There is some research on n...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(132, 'Notes from @Aakash: Overall: Maybe+ EO: 6-7 | FMF: 5-6 | Thesis: 6 | Price: ? Spikey: ~1 (need refs) - Thesis is a compelling one + have built early momentum - Can see a strong growth mindset and they are building in a deep familiarity space - Would likely have to be a services + product play ideally – for which they seem like an incomplete team - Not SaaS native Next Steps: Push them on GTM thinking with Kuldeep, Rohit and other SaaS folks. Notes Asad Abrar - Drizz.dev Born in Patna Raised by Mother , father used to work in Saudi (used to come once in 2 years) IT KGP 5 years | Order of merit in technology | graduated in 2014 After college got off campus placement @ Baker Hughes 1 year worked at Baker Hughes Then started a company similar to go mechanic Why did you start then ? Had nothing to lose. Was seeing value creation in startups from batch mates Manager at baker hughes was co-founder at the first venture | total 4 co-fos “ You seem like tech inclined how come an ops heavy biz?” That time tech enabled cos we’re all around. Tech to streamlines believer Ran for 1.5 years there | got to monhly 10L GMV Realised problem was two fold : - Old cars for repair used to turn up ..only post service centre cycle was done for the owner - Repair at doorstep was becoming a challenge in an asset light model - Logisitcs of getting parts to doorstep became a challenge - Pivoted to b2b | they were partners for Ola - Realised its a very linear scaling biz and momentum was low - There were a...'),
(134, 'Evaluation Plan + Key Questions to answer: 1. What does the company do? 1. Do we (DeVC/Z47) have a thesis on this space? 1. What are the top 3 questions to diligence? 1. Who has piped this company to us? What are their views? 1. What do refs say about the founder? 1. What''s the DeVC team views? 1. What are the Collective signals? 1. Why is this company likely to be special? 1. Who can help? Experts / Venture Partners? 1. Deal dynamics? Potential deal to do? ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: '),
(135, 'Notes:: Overall – Maybe + for DeVC Spikey = 0.5 (closer to 1) 30/40 - FMF 7 | EO 7 | Thesis 8 | Price 8 Overall, + Quite thoughtful on how to build (shows up in product formulation, pricing focus, investment in manufacturing) + Surrounding himself with people (2 food scientists in house / ITC factory folks are helping to scale up production / Devendra Chawla, Nature’s Basket head is working closely and has invested) + Clear articulation on what he wants to focus on and learning from other food brands + Thoughtful about fund raise (doesn’t want to raise too much as not needed, wants to get thoughtful partners on board) ? Didn’t speak to him about scale of ambition of journey over next few years Next Steps : Connect him to Revant (to discuss team building for brand business) and Chakri (on online and offline distribution / category building learnings). Also, get feedback and BRCs at the right time. DeVC’s edge here will be getting the right people to help him think through the larger questions. - - Fund Raise - Has closed 12cr at 75cr pre with Prath. Had a TS (?) from Fireside for 16cr but couldn’t get his angels out (he has ~25 through Mumbai angels + RUV on cap table). Stopped taking calls from other VCs for now – in Due D - Total raised before this 5.5cr in ’22 and 3cr in ’23 (Java doubling down) - 3 weeks since Due D started, thinks should be done with SHA as well by end October Business + Grown 0.5cr, 5, 15 last year and this year targeting 25-30 + L3M 1.6 (J), 1.8 (J), 3....'),
(138, '(1) Founders and Key Team: Abhinav Kankane – Title not disclosed [Inference] Career: INSEAD, IIT-Madras; ex-Zalando, P&G, UC Focus: Business, GTM, Partnerships Functional responsibility: GTM & Partnerships Equity & commitment: Not disclosed Relevance: Strong cross-border business and partnerships background relevant for scaling GTM. Siddharth Shrivastava – Title not disclosed [Inference] Career: IIT-Madras; ex-WinZO, Sprinklr Focus: Product, Content, Pedagogy Functional responsibility: Product, content, pedagogy Equity & commitment: Not disclosed Relevance: Deep product and pedagogy experience fits Eduro’s core learning app. Kavish Shah – Title not disclosed [Inference] Career: MS @ UPenn, IIT-Madras; ex-Vanguard Focus: Technology & Innovation Functional responsibility: Tech leadership Equity & commitment: Not disclosed Relevance: Technical rigor and innovation background supportive for AI-driven product. Adwait Sudersan – Title not disclosed [Inference] Career: IIT-Delhi; ex-WinZO; ex-founder Focus: Technology & Innovation Functional responsibility: Technology & Innovation Equity & commitment: Not disclosed Relevance: Founder-level technical background and prior startup experience.
(2) Product and Technology: Product stage: [Inference] Not disclosed Core functionality & tech stack: Interactive Learning Canvas with curriculum-aligned generative components; Central Memory Layer for pace, mastery, misconceptions; Motivational Loops for daily engagement; AI components (LLMs), TT...'),
(144, 'Inbound via Chandrika (Quivly) - 2026-02-28: Source: Chandrika Maheshwari (Quivly) forwarded to Cash on Feb 28, 2026. Chandrika says she''s been "super impressed with the product" - Quivly is a design partner. PITCH (from Shagun''s email Feb 27): "Engram is the brand brain for fast-scaling AI companies. As a company grows, brand and marketing context (how you position, how you respond to the market, what sounds like you) becomes impossible to transfer at scale. The faster you grow, the worse it gets. Engram makes brand intelligence institutional so it compounds as you scale instead of fragmenting. The system learns your taste, your context, and your decision-making, and turns it into something your whole team can use." STATUS: Live with design partners and a few early paying customers, all Seed-to-Series A AI companies. Planning to raise a pre-seed soon. FOUNDERS: 1. Shagun Ohri (CEO) - shagun@engramhq.com - 2x founder, 14+ years in brand and marketing - Most recently Director of Marketing at Together Fund working with Series A AI companies - Rahul''s concern: "background of hopping around quite a bit" - suggested checking with Subham at Together Fund 2. Siddhant Singh (CTO) - siddhant@engramhq.com - Previously built a generative media platform for enterprise (Volkswagen, J&J) - Scaled Flipkart Ads to $1B ARR - PRIOR Z47 HISTORY: Affinity shows email exchanges and meeting in Feb 2024 (last email: Feb 20, last event: Feb 8). Personal email: siddhant0204@gmail.com OPEN ITEMS: - Ca...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(147, 'Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score ---
De-brief (if any): 
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
De-brief (if any): 
Next conversation with Founder on {use “@now”}: ---
Attendees from DeVC:: 
Z47 Conversation with Founder on {use “@now”}: 
Notes:: 
Attendees:: [Table]
Notes:: '),
(148, 'Evaluation Plan + Key Questions to answer: 1. What does the company do? 1. Do we (DeVC/Z47) have a thesis on this space? 1. What are the top 3 questions to diligence? 1. Who has piped this company to us? What are their views? 1. What do refs say about the founder? 1. What''s the DeVC team views? 1. What are the Collective signals? 1. Why is this company likely to be special? 1. Who can help? Experts / Venture Partners? 1. Deal dynamics? Potential deal to do? ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: '),
(149, 'About the Company: - ExtraaEdge provides a full-stack marketing and sales SaaS platform for the education industry, leveraging predictive analytics, automation, and AI-driven tools to improve student acquisition and recruitment processes. - They are targeting educational institutions such as universities, test prep organizations, overseas study consultants, and coaching centers. - Annual Recurring Revenue (ARR): $2M (2023-24) and has grown 3.2x ARR since 2022. - They have 276 global education brands, including universities and mid-market players with the following split - Enterprise (23%), Mid-Market (15%), SMB (62%). - The core offerings are 1) predictive enrolment engine with 83% accuracy using proprietary LLMs and ML models, 2) automated CRM, lead nurturing, ROI trackers, and centralized communication tools, 3) GenAI-powered co-pilots for sales teams and prospective students to enhance conversion rates - They are well reviewed and testimonials indicate improved application rates by 22% and increased conversions for remote counseling teams by 18%, making it a trusted partner in education recruitment. - They are currently selling in MENA, UK, Europe and India Founders - Abhishek Ballabh (CEO) - Data Science and B2B SaaS expert with a background in AI and ML. - ExtraaEdge – ’18 - now - OnDeck – Founder Fellowship ’22 - SaaSBoomi – SGx W20 - Instructional Design Head – MindTickle ’13-15 - Software Architech – HSBC ‘09-13 - Sushil Mundada (COO) - 15+ years in product engineerin...'),
(151, 'AI notes:: Anirudh, founder of Faff, presented their personal assistant service to potential investors from DVC. Faff aims to democratize access to personal assistants through a combination of human operators and AI automation. Founder Background - Anirudh graduated from IIT Bombay in 2022 (Chemical Engineering) - Worked at Facebook AI Research (FAIR) in London on reducing AI hallucinations - Met co-founder Het Patel at an Entrepreneur First hackathon - Raised $125K from Entrepreneur First in December Business Model & Metrics - Personal assistant service targeting tasks not covered by specialized apps - Users send requests via WhatsApp to a Relationship Manager who assigns tasks to "Faffers" - 182 current users paying ₹2,000/month - Top users average 5 tasks per week - Target demographic: 25-35 year olds with ~₹40 LPA income - Most common tasks: digital tasks (web check-ins, Uber booking), finding local services, and sourcing local products Operations & Economics - Relationship Manager assigns tasks to Faffers (task executors) - Currently paying Faffers ₹50K/month, planning to reduce to ₹30K with better SOPs - Each Faffer currently handles ~12 tasks/day - Negative unit economics with ₹2K gross margin burn per customer - Payments handled through user wallet or direct payment by users Automation Strategy - 6140% of voice workflow already automated (restaurant reservations, pharmacy calls) -  4114/*-92w34r5t678Goal to increase Faffer productivity from 12 to 50+ tasks per day - C...'),
(153, 'AI notes: Jigar, a former Goldman Sachs risk analyst, presented his startup which is building an AI-powered analytics platform for asset managers. The meeting covered product strategy, market positioning, and fundraising plans. Background and Experience - Worked at Goldman Sachs (2016-2020) in Risk Informatics team - Used machine learning and AI for firm-wide risk management - Developed systems to analyze 50 scenarios across 2 million positions - Previously worked in market risk for Asia Special Situations Group - Focused on ensuring no FX or interest rate risk in emerging markets deals Product Vision - Creating AI-powered risk and factor analysis for fundamental equity investors - Key workflow integration: morning portfolio review meetings - Generates reports analyzing what moved the portfolio yesterday - Creates customized factor models with real-world explanations - Not positioning as "selling alpha generation" (strategic approach) - Integrating with data sources including Polymarket, Google News, and Alpha Vantage Target Market - Fundamental asset managers with under $100B AUM - Focus on firms without large quant teams (80% of market currently underserved) - Initial beachhead: firms with 2-3 quant people who need supplemental capabilities - Already working with design partners like Marcellus, Arga, GCM, and Grosvenor Business Potential - Current market: similar services generate $800M revenue with only 10% AUM penetration - Aladdin (competitor) generates $1B in revenue wi...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
