INSERT INTO util.enrichment_staging (company_id, content) VALUES
(389, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(390, '**Broker SaaS**: We have been iterating hard on the core of Realiti’s SaaS foray, the Broker GTM. After lot of experiments we are ready to publish authoritative numbers on our first sales campaign in June 2024. **Total Leads - 600** **Leads in active follow up - 380** **User Self Signups - 90 ** **Realiti Microsite activation  - 35 ** **Paid customers - 10** Some key points to note here: - All of these are **Self Signups** originating purely from Google and FB campaigns and not by forced cold calling - The** Microsite activation** is a very important step. It is an industry first product which puts a ultra modern variant of a self branded ‘99 acres’ or ‘MagicBricks’ in the hands of each broker. And again these are fully user initiated activations - **> 50 % **of the unconverted leads from this campaign are fully warm and our conversions and word of mouth is only improving day by day Most importantly this is totally in addition to our existing **$200K ARR** from our builder line of business. Our immediate goal is to increase magnitude of these campaigns and hit predictable monthly revenues from the Broker SaaS line of business
Overall Marketing Efforts: - It is a massive effort to sell any SaaS to SMEs in India, especially to brokers in real estate - On top of that, achieving self signups, activations of microsites and paid conversion takes a lot of tireless efforts on content creation, experimentation and best-in-class marketing automation - There has been a radical overhaul ...'),
(394, 'Ishita from Westbridge on Credgenics & Collections 2026-01-15T19:29:00.000+05:30: *Context: Ishita Shah was the sole analyst on the Credgenics deal done by Westbridge in 2022. She continues to be the primary POC for Westbridge on the portfolio management for this company, spends significant amount of time with Chief of Staff and CEO, even spent three weeks embedded in a Credgenics customer called *[*SMFG India Capital*](https://www.smfgindiacredit.com/)* (investor in Yes Bank & owner of LendingKart) * Net: She is -ve on the Collections & wider FinTech Infra opportunity in India because BFSI co’s don’t want to pay for Tech and want a “cost plus” pricing model for services. Not possible to dominate the industry because BFSI wants vendor re-risking with 2-3 players for key services like Collections. However, reading between the lines - there is an opportunity to build the “2nd place” Tech enabled collections agency (potentially w/ some ARC partnerships) due to the nature of this industry - 2nd place Spocto has been acquired, 3rd place Credit Nirvana, Perfios acquired Credit Nirvana. But, given what has happened w/ Perfios et al in Fin Infra - one has to be careful about entry price & TAM ceiling. Notes from convo: 1. Credgenics 1. Started as pure-play Tech vendor 1. But, even when WestBridge was underwriting in 2022, it was apparent that Services will be important 1. Wasn’t underwritten as a SaaS company 1. SaaS TAM =$200M v/s Services TAM = $1bn 1. However, they underestimated ...'),
(395, 'Attendees from DeVC: @Anonymous: - Early employee in Urban Ladder. Get BRC from [Untitled](https://www.notion.so/8cc6d1e9f866433a80646661afb1a7c2) - Spent 5 years in Australia building a funded furtniture startup, that got acquired as they ran out of cash - Has done ops, inventory, product management, NPD etc at both companies - Wants to move back to India, be closer to family, settle in Bangalore - Explored home as well, but not excited by it - Thinks there is a space for a fabric innovation first brand starting with menswear - Tshirt priced at 3500 - Pants priced at 4000-5000 - Speaking to Shuchi at Fireside, Rajiv at Antler and a few others - Will come back and pick up early Jan with folks - Raising 500k - Told him to raise 1mn instead to manage inventory - Good top down story teller, but didn’t find consumer insights or RTW yet in this conversation **Founder Introduction:** Rushabh, previously involved in building businesses in the home and furniture sector, is now exploring opportunities in the fashion industry with a focus on functional apparel. **Business Idea:** He is considering launching a brand called PRBT, inspired by the concept of peak performance and ascension. The brand aims to create functional, stylish, and comfortable apparel using innovative materials that cater to the evolving lifestyle needs of consumers. - **Brand Concept:** - PRBT is inspired by the idea of peak performance and ascension, aiming to offer apparel that is both functional and stylish. - T...'),
(398, '**Detailed Notes**: **Background** - Started in 2011-12 with iCouchApp - Moved across India; dad was in a government job - Mostly lived in Calcutta and Delhi - Did college at BIT Meerut - Worked at Wipro, then left with Ashish - Initially funded by Morpheus **Early Inspiration** - Decision to start came from Rohit Marwade, a senior in college who was the inspiration - Another college friend worked at Indigo Star, Hotstar - Ashish was the CTO - Satvik and him were electronics majors - Senior was doing college stuff and went to IITB - Eureka was the first B-plan competition in India - He won a prize and we all spoke about it - "I got the keeda after that" - Worked at Wipro for experience and didn''t like it - Read about global startups being built - Used to go to all the B-plan competitions - Met Sameer at some of these events **First Venture - iCouchApp** - Got 5L funding - "That was a lot of money then" - Ashish left immediately; "I paid him half of my salary" - Indus Khaitan rejected their idea initially - They left their jobs and Morpheus didn''t invest at first - Took money from dad and started - Morpheus liked what they built later - After they invested, raised money from others - Then started building the company - Got to 5-6L revenue per month **iCouchApp Product Journey** - 2M subscribers - Partnered with KBC and others - "We saw things crash when we did KBC" - "We were just looking to solve our own problem back then" - No DTH or satellite available - Wanted to build a r...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(399, 'Heads up note from @Aakash 2025-04-04T19:22:00.000+05:30: Sharing a brief note for our $50K investment in [Revspot’s](https://www.revspot.ai/) pre-seed round, amounting to 0.75% ownership. This is round where paperwork is closing now, we had committed in Sept 2024. The co has since scaled to $300K ARR, even hitting $80K ACVs with Indian customers. This is a community cheque underwriting with RK, Chirag, Aakrit and Miten The co is raising $1.4 Mn at $6.6 M post money. Round is being co-led by Titan and Infoedge ventures This was brought to us by RK and product was strongly vouched for with a strong reference on Darshan. We are restricting this to a community cheque even with multiple folks from the collective giving a strong signal, given lack of FMF on SaaS GTM and very India first build out **About Co** - Revspot is building AI powered pre-sales agents and marketing intelligence tools for the non-SaaS world where MQL generation is key to growth (vis Financial services, Real Estate, O2O platforms) - They have early traction with Livspace, Dezerv, Meragi, Stabl Money and multiple other cos and are adding logos at a fast clip **Founding Team** 1. [Darshan Subhash](https://www.linkedin.com/in/darshansubash/?originalSubdomain=in) - Was leading customer success in 6Sense in his most recent stint. Got there via slintel acquisition (where he was the chief of stagff) - Was earlier leading sales strategy at Livspace and had a short stint at Unacademy - IIM Indore 2014 1. [Varun Garg](...'),
(400, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '),
(401, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '),
(404, 'Heads Up Note 2025-11-25T09:18:00.000+05:30: Hi team, Sharing the heads-up note for our investment in WorkAtoms which is a text to workflow builder for non-engineering knowledge work (e.g. content writing, social media monitoring, responding to inbound requests etc) - initial focus is on Marketing & GTM teams DeVC is investing $50K as part of a $2M SAFE round @ $10M post money valuation *Note: This is a founder-first investment (based on IIT-B signals) + Community Top Up to *[*Nikhil*](https://www.linkedin.com/in/nikhil-abraham)* from Cloud Chef (new DeVC Collective member in US). Hence, we have sized the cheque accordingly & will do more work in coming months as they tighten their GTM and sharpen their product (hopefully for a single vertical) * **Founders** 1. [Dhruv Jaglan](https://www.linkedin.com/in/dhruv-jaglan/) - CEO & Founder 1. IIT Bombay CS 2020 1. 2.5 YOE @ BabbleBots AI - was promoted from Founding Engineer to Co-Founder 1. 1.5 YOE @ LinkedIn India 1. From Cash:* ++ soft refs from IIT-B network on Dhruv : “Rockstar and would get anything done”, “Machau ladka hai.. keeps picking new things and building”* 1. [Georgi Boby](https://www.linkedin.com/in/georgi-boby-07b081161/) - COO & Co-Founder 1. 6.5 YOR @ Cloudchef as Founding Engineer 1. IIT Bombay 2019 1. From Cash: *++ Table thumping ref on Georgi from Nikhil @ Cloud Chef and Ashray @ Rephrase AI* **Investing Process** 1. We were introduced to Dhruv Jaglan (main founder) via Activate AI (Aakrit & Pratyush) 1. Act...'),
(405, 'Attendees:: | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(406, 'Notes:: 1. **Ankit & other CoFo Jayant** 1. Pissed off that students couldn’t take CS programs unless they did pre-reqs 1. Made a simple web tool to map out pre-reqs & simulate the pathways in future semester 1. 1 year together selling software to corporate training academies 1. Both were Tech CoFos hence no Sales muscle 1. **Abhishek** 1. Feb 2024 → Jayant and Abhishek wanted to do something together 1. Put everything on the line to built a business 1. Ankit has student loan 1. Jayant has left PPO 1. Tried to sell personal transcribing tool to founders 1. His dad has taken an unsecured biz loan at 48% p.a. 1. **Problem → multi lingual conversations in Indian call center** 1. Spammed everyone on LinkedIn 1. Jazib Ali from Slice → collections team is 300 versus CX team is 30 1. Sometimes caller goes beyond boundaries to demand collections 1. Went to Poonawala Fincorp NBFC call center in Pune — “couldn’t imagine place in the world where 300 people are shouting” 1. Understood that QC executive (20 of them) will fill in forms 1. “Wanted to move from cost center to revenue generation” — started as QC tool but realized collections is better 1. **Learnings** 1. Being first to collections is critical 1. “Promise To Pay” disposition doesn’t capture the full context of the call 1. Collections call analysis is the wedge 1. Now migrated to making the collections call 1. **GTM** 1. Spammed on LinkedIn — tried different copy 1. Nira Money — cold email 1. Jupiter, Groww — cold email as well...'),
(408, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '),
(410, 'Scoring (can be copied for multiple people): DC: **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | 2 | **10** | | Product Chops | 1 | 2 | | S&M Chops | 0 | 2 | | Domain knowledge & skills | 1 | 3 | | Breadth of exposure | 0 | 1 | | Familiarity/repeat work | 0 | 1 | | Advantage | 0 | 1 | |  |  |  | | **EO** | 2 | **10** | | 1-10 strength or some 0 to 10 | 2 | 4 | | Commercial POC/history | 0 | 1 | | Thoughtful hustle and hunger | 0 | 1 | | Referenceability and followership | 0 | 1 | | Network leverage | 0 | 1 | | Compounders | 0 | 1 | | Wealth top decile | 0 | 1 | |  |  |  | | **Thesis** | 7 | **10** | | Good thesis, sizable TAM | 5 | 5 | | (++) small share of direct SAM = large rev $$ | 1 | 1 | | (++) Tailwinds + secular super strong trendline | 1 | 1 | | (++) Key is product IP only or Biz acumen only | 0 | 1 | | (++) Early Traction proof points | 0 | 1 | | (++) Table thumping expert/DEVC Founder validation | 0 | 1 | |  |  |  | | **Price (Post Money)** | 10 | **10** | | Sub 6M | 10 | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on 2024-09-30: 
Attendees from DeVC: @Anonymous and @Anonymous: 
Notes:: We are building routines - beauty & personal care quick commerce, and reaching out for our pre-se...'),
(411, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(415, 'AI notes: ### Business Background & Team ### Product Vision ### Target Market ### Strategic Considerations ### Current Status ### Action Items
RM reflections: ++ Love the fact that they want to bootstrap to MVP, test w/ customers and ONLY then consider raising a round ++ Clear Why Now for this AI credit companion type business; we have a thesis ++ in-domain with 10K+ hours, esp for Som who has done 8 YOE @ KreditBee ++ Som’s wife used to lead Perf Marketing @ KreditBee so she will help them with UA ?? I don’t see a clear spike in either of them ?? Couldn’t see Consumer Tech chops ?? Som does NOT have a breakout trajectory; he is 8 YOE @ KreditBee even after IIM Cal; only AVP level ?? Don’t see either founder as a good seller Key Qs for me - What are the refs on Som (given he doesn’t have family who worked at KreditBee; Shobhit’s elder brother roped him into KreditBee) - What is the quality of this team v/s Oolka & GoCredit? should get MPE when they are ready
Conversation 2025-10-03T15:29:00.000+05:30: ')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(416, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '),
(418, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(421, 'Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1 | | (++) Tailwinds + secular super strong trendline |  | 1 | | (++) Key is product IP only or Biz acumen only |  | 1 | | (++) Early Traction proof points |  | 1 | | (++) Table thumping expert/DEVC Founder validation |  | 1 | |  |  |  | | Sub 6M |  | 10 | | 6-10 M |  | 8 | | 10-15 M |  | 6 | | 15-25 M |  | 4 | | 25M+ |  | 2 |
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: '),
(422, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(423, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(425, 'AI notes: ### Action Items ### Nilesh''s Background & Career Journey - **Kearney Experience (5 years):** Worked as consultant focused on consumer sector, including year-long project with Marico; gained experience across full apparel value chain from fiber to retail stores; stayed at Kearney due to strong people culture and bottom-up organization structure - **COVID Inflection Point:** Consulting remotely felt isolating compared to collaborative hotel work; prompted career transition after being last from batch to leave Kearney - **Meesho Journey (Growth Lead):** Joined initially for supply chain role but pivoted to user acquisition and growth; led team of performance marketers and influencer managers; helped Meesho become world''s most downloaded shopping app - **Three Phases at Meesho:** Started with install acquisition, expanded to new user activation (including on-app product work in pod structure), eventually led branding and creative as well as all user growth reporting to Vidit - **Key Meesho Learnings:** User-first approach with significant user research before any initiative approval; importance of strong rationale for low prices; building distribution over brand; focusing on large basket categories ### Idea Exploration & Validation Process - **Three Ideas Evaluated:** - **Co-founder Background:** Anu (life partner) brings 10 years of product experience from Gulf Talent, Insider (built live events pre-COVID), and NinjaCart (built Mandi News pricing tool for traders) ###...'),
(427, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** | Identifiable Spike |  | 2 | | Bold & Ambitious |  | 1 | | Clear & Insightful Thinker |  | 2 | | Relentless & Grit |  | 1 | | High rate of growth |  | 1 | | Execution excellence |  | 2 | | High ownership |  | 1 | **EO/FMF/Thesis/Price Score** | **FMF** | `Calculate out of 10` | **10** | | Product Chops |  | 2 | | S&M Chops |  | 2 | | Domain knowledge & skills |  | 3 | | Breadth of exposure |  | 1 | | Familiarity/repeat work |  | 1 | | Advantage |  | 1 | |  |  |  | | **EO** | `Calculate out of 10` | **10** | | 1-10 strength or some 0 to 10 |  | 4 | | Commercial POC/history |  | 1 | | Thoughtful hustle and hunger |  | 1 | | Referenceability and followership |  | 1 | | Network leverage |  | 1 | | Compounders |  | 1 | | Wealth top decile |  | 1 | |  |  |  | | **Thesis** | `Calculate out of 10` | **10** | | Good thesis, sizable TAM |  | 5 | | (++) small share of direct SAM = large rev $$ |  | 1...'),
(428, 'Notes: Surfacing Selkea , this is an ex RBI H bank compliance focused team (starting with an AMA compliance bot trained on RBI circulars).Founders claim to have been part of the creation of the mule account identifier and ULI at RBIH. Raising a $1M round , claim to have commits from Rajesh Bansal and a few other RBI folks as angels who will also come on board as advisors. **Founders** [**Abhishek Mishra**](https://www.linkedin.com/in/abhishekmishra96/) - Senior Assc (CEOs office RBI H) , MT - RBL Bank ( 1 yr) , Ashoka Uni Comp Sci [**Varun Menon**](https://www.linkedin.com/in/sureshvarunmenon/)** **- Senior Assc RBI H (3 yrs), Loyola BCom , NLU Masters **TT- Weak Maybe/too early  for Z47 ($1M raise), Maybe for DeVC** Interesting thesis and space in which they are building, however the current product is quite weak (no real workflows like Anuj at OnFi), on sales they are much better on call but no clients yet **Could be interesting to meet and track given reg access and top down sales pull.** + Interesting space - Compliance AI- Hair on Fire problem from an AML and risk perspective + Team - understand how to sell to banks - entrenched with regulators- " Will be one step ahead on regulations - all the folks working on guidelines are mentors" ? No real POCs despite 1 year of being operational ? Very dismissive on competition - " Competition (OnFi) got AMCs cause they''re easy, bank mei aap ko warm intro lena padega to sell" **Selkea** **Product Overview** - Building a compliance ...'),
(431, '**Company Overview**: - Founded October 2023, registered June 2024 - Building automated satellite system for pharmaceutical manufacturing in space - Starting as CRO (Contract Research Organization), evolving to CDMO (Contract Development Manufacturing Organization) - Global focus from day one, despite being an Indian company - Recently raised ₹5 crore from Campus Fund **Mission & Motivation** - Antriksh founded company after his mother''s cancer treatment experience with Keytruda (developed in space) - Identified key pain points in current space pharmaceutical manufacturing: - Limited frequency (can''t do 4 tests/year) - High costs (Merck spent $15M for few ml) - Disruptions from astronauts'' movements affecting gravity - Personal investment: Founder declined Munich job offer, invested full savings **Technology & Innovation** - Three-part satellite system: 1. Satellite bus (purchased off-shelf) 1. Automated pharmaceutical processing module (prototype ready) 1. Re-entry module with proprietary heat shield - Producing pharmaceutical/protein crystals that serve as "blueprint compounds" - Key IP: Lightweight heat shield (1/3 weight of commercial options) - Reusable satellite design enables quarterly missions without building new satellites **Team Structure** - Antriksh - pharmaceutical experiments and payload - Jivitesh - operations and design (previously worked on CAN satellite projects for ISRO) - Monica - space mission planning (former NASA and German Aerospace Center) - Team con...'),
(433, '**Meeting Notes**: **Founder Background- **[**Karan Goyal**](https://www.linkedin.com/in/karan-goyal-6b1099188/) - Origin & early exposure: Grew up in Samana (near Patiala cantonment), surrounded by tanks and artillery; developed early fascination with defense. - Family context: Comes from a business family (yarn mill background), saw entrepreneurship at home. - Education: IIT Delhi graduate, Class of 2022. - Member of the Formula Student race car team for 4 years — hands-on hardware building, teamwork, and exposure to startup culture. - Inspired by seniors who started Baaz Bikes and Vecmocon, both now beyond Series B. - Influences: - Studied US defense-tech ecosystem — particularly Anduril (Palmer Luckey, ex-Oculus, and Palantir alumni). - Read *Kill Chain* by Anduril’s co-founder; internalized concept that modern warfare revolves around building and disrupting the “kill chain.” - Concluded that robotics will disrupt defense the most, creating room for a new “Lockheed Martin.” **Company Formation & Team** - Founded: 2022–23 after noticing drone-based drug smuggling on the India–Pakistan border. - Initial setup: Funded by founder’s father; started in a 2BHK apartment in Gurgaon converted into a workshop. - Co-founders: 5 IIT Delhi graduates. - Initially balanced jobs with building; all now full-time. - Team split: - 2 on business, investment, manufacturing, finance. - 3 on technical verticals: AI on edge (computer vision), radar development, and interceptor engineering. **Tec...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
