INSERT INTO util.enrichment_staging (company_id, content) VALUES
(154, '1PE meeting w/ @Dhairen Tohliani 2026-02-19: Surfacing Finlead AI, they are building a commission management solution for insurers. Essentially bringing in dynamic commission structures to help insurers manage EOM better. Founders are spikey FFs and this is a clear pain point basis our insurance infra work in the past. Looking to raise $300-400k now and would recommend a 2PE from DeVC considering the founders, trendline and early momentum. Have pinged someone from PhonePe insurance for a BRC on the founder, will add the deck here as well. Views Dhairen – Maybe+, if refs check out and there is real substance behind what they’re conveying then clear SM ++ Entrepreneurial and hacky guys with early track record of achievement ++ H&H - was advising startups, got in touch with IRDAI for pushing current product ++ Sales motion - GoDigit (signed), Royal Sundaram (POC), Care - not easy to get insurers on board, so early especially ++ Insights and maturity for the age was surprising - in touch with regulators, ONDC, have foresight - deferred insurance implications ++ Thesis - EOM pressure is real - managing commissions better is addressing a clear pain point ?? Product is a thin wedge; they will need to keep iterating to expand ACVs - could get capped quickly on this current one if insurers try to move in-house ?? Positioning v/s reality – need to do refs here Meeting Notes Company Overview & Problem Statement - FinLead AI building B2B insurance commission management solutions - Founde...'),
(157, 'Deck 2026-03-20T05:42:00.000+05:30: --- [File: attachment](https://prod-files-secure.s3.us-west-2.amazonaws.com/b21975bb-aebf-48e3-8c44-1573c4404129/388099bb-2c83-4cd4-b004-d67ee5130d0a/Firi.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAZI2LB466UA77UFQM%2F20260320%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20260320T103111Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGgaCXVzLXdlc3QtMiJGMEQCIAjR1%2FmOn94RxOu80GGrr8o161UpwC5DLvufUXyZ1E9QAiAgon%2Fcwopz%2BBQXS%2F8p95tqvyBpjToki0i7SiqvDHBOASr%2FAwgxEAAaDDYzNzQyMzE4MzgwNSIMo7zSX7qyUUCIgwTaKtwDZ7o3rhjnk%2BBfsK9bVab0hcIc3xEHV0Nk6TIpgxf22VkirHjhmCEngZOJxLcPK2K8rgdfV8dmj1FGpkfUJVgGJ6ovf6xWzfiS8j44MT5QrV09LtKGyPJDSVvGXwVtKediVJfQbtuoBSjQjOBzLail%2BtX%2BBzp4uQQ1K9N5Y%2Bap2r0%2FBWHWJqSoJ6JLV6TX7L7U3M5Q81xdT%2BE8s5%2FgKPYg%2BFFkXChHGlQSvy8m9c%2F2NcNrrDnBi87SBvLRRTFaG3ZL4slKFxd0rxLLWiaQA8nvMl2ytrxbihSHUXgukc1P1eFwtD%2B8Aohe%2FN1iWcmE4eN32zP4hXAac7%2BO5Bm17Jlr2CfamrvzVmJWDeiGKPXZXF4akfklutSCTtn4m0xDPjtE7q7uQVNldloKYhCOTbav%2FUk7uM9Mt8z%2FaFPD%2BWoazA3LivchZQyBb7cCyfsTd9nrrxdGOAxCUSMAC9rtg0kvq3Bj0n%2BKWT5tH%2FhsVj8xR4TeA2OIrK3dFl11BsBwo0DnCYfNmg8wa7Zv5rjsneyaqVX%2FqTT7qJs4QF1WJMblpnkTsoyLpyXaM8Meeb%2BSSBEDHl3TaVAjgsaSU8u8nFHgO0kCJXj3%2BfbCJtWsCeR2R3xntdrZlPEq60%2FvH9wwyvzzzQY6pgHMq4qzj0t3WVLhnEuLigoYScn0FjIjhKDhgfm5o1ANAgt1IPS%2FM01Mo0GyxrqttfTnYCs%2FM0Bqw0kQk542nxr6tra7QPBS8DqjFCkHtKA%2B%2Bb585NSGRb0jwTTPuJI%2B0DwEpVeq2VLqLXwkL3SSGy7LfNDdJm6ZrK5LCUlxT7N0LAXFA3sq9PKxNrw1GVZJJQ358%2...'),
(159, 'Financial Update — Mar 2026 (Audit): - 2025 Revenue: ~$30,000 - Current Monthly Revenue: ~$5,000 - Jan 2026 Cash Balance: $90,000 - Monthly Burn (current): $20,000 - Burn expected to reduce further — targeting near-zero in 2-3 months'),
(160, 'From @Anonymous: Agreed with views below – spoke to her today. Spikey – 0 (just hasn’t operated before and surprising lack of ambition for what she has done so far) EO 5| FMF 5| Thesis 5| Price 8 - Speaks well – has a good consultant background and work - Is going deep on product, consumer insights and brands ? Isn’t aiming for a big outcome ? Wants only patient capital ? Is building a team very luxury – will potentially build a new age Kama with a small TG ? Didn’t hear enough depth on what the market is, what consumers are saying, GTM Next – Pass and track for next [Table] [Table]
Convo 2024-09-17T17:59:00.000+05:30 with @Anonymous and @Anonymous: Rachna Bahadur: - Was at Bain and could only work with companies in small capacities - Looking to move deeper into value chain and couldnt find much - Byjus chased me for 6+ months and made an offer to head the international business that I couldnt refuse - Had an opportunity to co-found 82East - couldnt get over the line on the set-up they were offering (good decision in hindside) -  Was one of the most exciting things I refused from all the offers that were coming to me Building a beauty brand focused on women in menopause and menopause segment. Product - Part of the identification was personal and rest research - Delhi & Bombay pincodes - women aged 40-45 and 50-55 to understand whats changing - We speak to women between these age groups. Its more homogenous across different geos - Care is no longer a luxury. Its customer backw...'),
(161, 'Rm notes — Reflections - FF | Concept | Spiky = 0.5 - should validate from BRCs |: ++ Clarity of thought, good articulation around problem space ++ Hard fought learnings from 1st stint - NOT chasing VC or Twitter hype, wants to validate ++ Taking on hard technical problems e.g. OEMs blocking deep links etc ++ Outside in; has studied other players in the market ++ Self taught software engineer ?? Slightly worried this is a missionary profile and NOT a business builder profile ?? Space has been DOA for a long time
Rm notes: 1. Was thinking about doing Master’s 1. Bain 1. Got back into coding after Bain - YouTube video learnings 1. Browser extension 1. Thoughts on device 1. platform agnostic or OEM agnostic | on device layer 1. Wants to challenge → https://www.opal.so/ 1. Building a second brain → Agent on phone 1. Wants to do a Reddit or offline launch to build convection before going to SPC et
Ref from Aniket (Bain) via Ashwin 2025-09-25T15:15:00.000+05:30: 1. Quirky 1. Thinks differently from others 1. Don’t have solid POV on whether he is great at building or a good product guy 1. Generally positive on him, smart guy
prep notes 2025-09-24T21:57:00.000+05:30: 1. Introduced via AeroDome founders who are from IIT Madras ecosystem 1. About Rohith 1. Prev. company was called Flowstate - https://www.flowstate.cc/ 1. New company 1. My notes
Meeting 2025-09-25T12:07:00.000+05:30: 
Ai notes: ')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(164, 'Evaluation Plan + Key Questions to answer: 1. What does the company do? 1. Do we (DeVC/Z47) have a thesis on this space? 1. What are the top 3 questions to diligence? 1. Who has piped this company to us? What are their views? 1. What do refs say about the founder? 1. What''s the DeVC team views? 1. What are the Collective signals? 1. Why is this company likely to be special? 1. Who can help? Experts / Venture Partners? 1. Deal dynamics? Potential deal to do? ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: '),
(165, 'Dhairen - 2026-02-02: Cash/AP had interacted last time around - view was that founders were opportunistic (original plan was fashion, then jumped to stablecoin trendline). Spoke to Saloni this morning - quite positive on the founders compounding. White has invested. Company has pivoted to stablecoin cards with early traction through a reseller model. General interest in spending time given traction in Kast, Aspora etc. Company has moved to global GTM now - unclear what''s the RTW/RTP. Founders in Bangalore Feb 4-6 to meet people. Dhairen wants to join if we''re meeting, or can set up separately.'),
(166, 'Rajat reflections - SM for $100K: ?? Key Q: GTM chops || PDF conversion ++ Clear Why Now because of Tech improvements & AI FOMO ++ Very Spiky || walked in negative - very intelligent folks ++ Product seemed interesting ++ Potential to go viral like Quizziz ++ Superior to the OpenNote team; much better product ++ Clear why now - given this is a P0 problem for every teacher ?? Very raw on GTM || going to be a crowded market ?? Roadblocks from a product adoption lens - if they can integrate into LMS and automate the PDF creation - it could be a game changer ?? Product does get commoditized - but no one will build at their pace
Product & Market Strategy: - Current focus: Math grading with instant feedback and error identification - Processing: Parallel agents handle hundreds of worksheets simultaneously - Vision: “Agile learning” - zero-cost grading/lesson planning enabling personalized learning journeys - Go-to-market approach: - Key market timing advantages:
Heads Up Note 2025-08-26: Hi team, Sharing the heads-up note for our investment in Frizzle Frizzle is an AI-powered solution for grading handwritten math worksheets. The platform helps teachers save 10-15 hours per week on grading while creating a faster feedback loop for students. The founders position their solution as enabling "agile learning" compared to the current "waterfall" approach in education where students wait weeks for feedback. DeVC is investing $100K as part of a YC SAFE round (more details) below Note: deck...'),
(167, '(1) Founders and Key Team: Name – Shrey Doshi – Title - Career snapshot (one-line): BBA in Marketing;Entrepreneurship background; family business in pharmaceutical exports; roles in media sales, digital marketing, and FMCG sales. - Functional responsibility in current venture: Sales, marketing, and related GTM activities (as indicated by roles such as Head of Sales - FMCG and related marketing leadership). - Equity % (if stated) and commitment: Not disclosed. - Relevance of prior experience: Strong in marketing, sales, and distribution channels, which are relevant for consumer wellness product GTM in India; explicit domain experience in FMCG and pharmaceutical exports may aid distribution and partnerships.
Company Snapshot: Problem & solution - Problem: Nutrition does not equal absorption; a large portion of the population has impaired nutrient processing (BCMO1 variant, MTHFR variant), with 48% unable to convert plant carotene to Vitamin A and up to 70% of people needing more supplements/higher dosages without seeing a difference. This aligns with India’s nutrition paradox and demand for more effective, bioavailable solutions. - Solution: A Spirulina-based super algae formulation marketed as having high bioavailability and broad health benefits (anti-aging, anti-inflammatory, immunity, liver and gut health, etc.). Core ingredients cited include Spirulina, chlorophyll, phycocyanin, and carotenoids. Claims include improved nutrient bioavailability and multiple health outcomes ...'),
(168, 'Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(169, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): '),
(173, 'CV / KK / TK <> Nishank 2025-08-23: KK to add views and do deep ref checks <u>**CV Views**</u> <u>Spikey = 1?; Maybe for DeVC; Refs from college can move me to positive zone</u> High intrinsics (to confirm) in a bad business (50rs noodle with GT vision) and not real traction. Key Q to strong maybe: Is the guy real? ++ jugaadu - high enthu, high confidence, potentially high capability ++ numerate ++ IQ ++ seems like he’s done some work on product depth ++ state level badminton player - capability demonstrated across multiple dimensions ?? Not genuine? More excited by “perfora” than “swiggy”; “travel on trains”; “did so many interviews for 0.1% change in spice levels” - feels like a performance of “hustling genius who is consumer first”. Somehow didn’t buy it. ?? no good answer on consumer brands - or why foods ?? very inside out - and full of self (a lot of it is feels like bravado)- so is there a lot of beta? ?? will need refs to see if he’s really got the metal ?? not left BCG yet +? does he actually do all this work on consumer side (should check) <u>**TK Views**</u> <u>Overall: Weak Maybe</u> ++ Spikey = 1, FMF = 0 ++ Inside out ++ Highly numerate and high IQ, will figure out things ++ Strong pedigree and track record of picking things and going in depth – 3 research paper in Intl journals, Politics in IITD, poetry etc in IITD, State level badminton player;  all-rounder type - Does he has the right spike for the food buzz? - No strong reason for moving out of web3 – where ...'),
(175, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): '),
(176, 'Anupam Acharya - Monthly Newsletter - 2026-02-27: January 2026 Performance Update & TaraLabs.ai Launch **MAJOR MILESTONE: Organization rebranded under TaraLabs.ai** - More than a name change - commitment to "democratize credit through AI-led development" - Building "Credit OS" of the future - AI agents manage credit repair, monitoring, automated applications - GoCredit AI remains in development, working toward consumer-facing front-end - Vision: "empower every individual with an autonomous AI credit ally that doesn''t just track scores, but actively improves financial health through automated, intelligent interventions" - Updated vision deck: gocreditai.netlify.app **January 2026 Metrics:** - Total Revenue: ₹10,498,463 (flat due to "Operational Reset") - B2C Subscription Revenue: ₹3,403,565 (+4.4% MoM growth) - Total App Installs: 628,816 (21% organic reach) - Net Profit: ₹1,500,000 (14% margin) **Growing Pains (Jan & Feb):** - Technical Migration (Jan): New onboarding experience, upgraded OTP systems. 4-day breakage causing revenue loss - now stabilized. - Ad Experimentation (Feb): Testing new creatives/targeting under new App flow. Temporary spike in CPAs, dip in ROAS. Multiple exhaustive experiments conducted. - Strategy: Absorbing experimental costs now to identify high-performing "winners" for scale-up. **Path to March Breakout:** - Late February: Normalizing ROAS as they lock in successful AI-driven ad formulas - March (Breakout): Launch of "Loan Kavach" - first major pr...'),
(177, 'Notes:: 1. **Regarding M&A** 1. Decided to NOT go ahead with the M&A involving the family run jewelry business 1. Has since spent the time with QC co’s to understand the opportunity 1. BB founder had considered investing in him but couldn’t go ahead; hence the connect 1. **Regarding hardware** 1. Currently costs ~₹20K BOM including their margins 1. Reason for high cost is that the volume is low 1. They do assembly in-house 1. Working with contract component manufacturers 1. **Quick Commerce opportunity** 1. BB is integrating with Tata Croma and Tata Cliq 1. Will have all the electronics inventory on the QC channel shortly 1. Want to use the gordian delivery box for electronics (mobile, headphones, earphones etc) and gold coin 1. There would be seasonal demand for such products e.g. around the new model launches in mobile phones & festive season for gold coins 1. They expect ~5% of orders to be electronics category 1. Also open to buy the devices from Gordian 1. Also in talks with: 1. Blinkit — Albinder is his POC 1. Zepto — has spoken to the team 1. Rapido — keen to test this on their own delivery channel 1. **Insights** 1. There is wear & tear of the safe boxes hence needs a replacement every 18-36 months 1. He is able to provide telemetry on top of the hardware which is valuable 1. e.g. tamper warning 1. e.g. geolocation 1. **His doubt** 1. Should Gordian rent out the devices to the QC players for the peak demand season? 1. i.e. ~4 months per year 1. And rest of the 4 month...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(180, 'Heads up note written by @Rahul Mathur 2025-04-12T14:33:00.000+05:30: Hi team, Sharing the heads-up note for our investment in [Grexa](https://grexa.ai/). This is an AI marketing app for SMBs in India to automate their entire marketing effort — SEO, SEM, performance & social ads to drive hyperlocal footfall and Sales. DeVC is investing ₹43 Lakhs ($50K) as part of a wider ₹15 crore round led Utsam Somani’s iSeed This is a a Community Top Up w/ Utsav Somani | BRCs pending (ex Testbook CoFo’s) **Founders** 1. [Ashutosh Kumar](https://www.linkedin.com/in/ashutosh-kumar6/?originalSubdomain=in) (ex CoFo and CEO — Testbook) 1. IIT-B ‘07 to ‘12 1. [Arpit Oswal](https://in.linkedin.com/in/arpit-oswal) (ex CPO — Testbook) 1. IIT-B ‘07 to ‘12 1. [Ayush Varshney](https://www.linkedin.com/in/ayushvarshney/?originalSubdomain=in) (ex CTO — Testbook) 1. IIT Kanpur ‘10 to ‘14 1. [Narendra Agrawal](https://www.linkedin.com/in/narendraagrawal7?original_referer=https%3A%2F%2Fwww.google.com%2F&originalSubdomain=in) (ex CoFo & CMO — Testbook) 1. IIT-B ‘07 to ‘12 **Investing Process** 1. Rajat sourced this investment opportunity & shared with Aakash 1. Aakash: “Having known the founders for long, hard to go bigger at entry. Lots of risks that seem like will repeat. “ 1. Aakash did a 1PE with the founders followed by a full team meeting 1. Decision was: “Community cheque is no brainer - trendline strong | founders are known (ex Testbook) ” 1. Utsav committed to lead the round hence decision was to d...'),
(183, 'Key Metrics (as of March 2026): - **Total raised:** ~$12M (Pre-seed $1.4M + Seed $6M + Zuora strategic $5M) - **Cash in bank:** ~$3.5–3.8M - **ARR:** Not stated explicitly; ACV ~$60–120K per customer - **Pipeline:** $12M total; run rate $2.5M, adding ~$0.3M new pipe/month (grown from ~$0.5M to $2.5M in 9 months) - **Direct sales conversion:** ~18% - **Sales team:** 4 AEs (2 enterprise @ $1M quota, 2 mid-market @ $600–650K quota) - Partner
Founder: **Arvind Gopalan** — CEO & Co-founder. Also spoken with Pranay (likely co-founder or early team). Building a partner-led GTM through ERP/billing platform resellers.
Company Overview: Growfin is an AR (Accounts Receivable) automation platform focused on order-to-cash workflows — specifically cash application/reconciliation, collections management, and invoice presentment. Sits in the finance operations layer of the CFO stack, not core accounting/GL. Key integrations with NetSuite and Zuora (Zora), through which it also has a strategic investment.'),
(188, 'Founders Background (from Matrix internal notes) - 2026-02-10: HARSHIT MADAN: IIT KGP (''08-''12), BA at Opera Solutions (12-14), PM at Housing.com (14-15), Co-founder SME financing startup (15-17), Meesho (''17-''22) VP Product to VP & GM Supply Growth. Bob: "One of the sharpest and most structured problem solvers at Meesho. Very calm, composed. Built a very good team. Trusted hand for Vidit." Aakash (Housing days): "Great executor and operator, but not sure if he can do iterative 0-1 stuff in the dark." PRATEEK AGARWAL: IIT KGP (''08-''13), Field Engineer Schlumberger, PM Housing.com, Co-Founder Bite Club (''14-''16) raised ~$1M, Meesho (''16-''22) one of first employees when <10 people. Bob: "Very sharp and high IQ. Very iterative and great for 0-1." Aakash: "Cut out to be an entrepreneur from day 1. Loves to get his hands dirty." Dada ranking: "Prateek > UK > Harshit. Same category as Shobhit (Vegrow), Ankush (DSLR)."
**Nitin Views**: - Overall: The combination of Harshit and Prateek building in the consumer domain is very exciting. They’ve both seen Meesho’s 0-1, 1-10 & 10-100 journeys closely and were instrumental in it. They were always sharp, but their Meesho stints have made them more polished and also taught them team building. They also always wanted to start-up (both had started-up in the past) - Harshit - I’ve worked with Harshit on a couple of short 2-3 week pieces - One of the sharpest and most structured problem solvers at Meesho (was very problem-first) - Very calm, co...'),
(189, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): '),
(190, 'Prep 2025-09-03T09:06:00.000+05:30: [File: download](https://prod-files-secure.s3.us-west-2.amazonaws.com/b21975bb-aebf-48e3-8c44-1573c4404129/ac6d370f-0d1d-45ed-b9dc-8d1a76100cfb/Semel_Shah_Haystack_OnePager.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAZI2LB466Z4A6JIV6%2F20260320%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20260320T102927Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGgaCXVzLXdlc3QtMiJGMEQCIGftJyDy4JSgt75dFJdnDE%2F%2BeAC%2FO2wBJkvT%2FQ6cCswPAiBDR2INkZIi1iz744cF3nD7DySgkWgE7mUsaCiMikBjGyr%2FAwgxEAAaDDYzNzQyMzE4MzgwNSIMD9%2BhMHa8F%2Bm7b0L6KtwDb2I0V3HgxiKKwtxYU56TuH2%2BeMlW2Kx58Ull7z5FZom85fLEeVLHba121J0og2No0r3aKZ1MNc23Pyv5%2FGZjX3kBtUx1w9w9pQj6HfHNPvEnN6LmIdbM1fww0paURRv1X9jjVaMR6eW8yNwoamxY9kQ1Zmni3ML6HTZAllI5FAaY4Bz8oiNbd5uMAR8%2F17M1BMcFF2FYTlC3wZ%2Bq0pVESLs1pcq%2BxetJVMlP7IykymIVe3iF6q7m868%2BysLcn40C6o%2BQQZ3BlwWd18xKJ3vT2q%2B555OulXT%2Fh%2BH6ITFKqTNvxRFB4lAEhWJSDDsAHtsGlPFWC3x%2FD3JysKhgVjRQyYnjyVJrSN1QpRG1yOLNUgU01ZQYs3bwKOVSIjuOss2Wg1XbNblmf6GVqkKPA7oJJ2Klfw6GObroRMSOfMa0UPTsWTURcOHuCNWpFdhsuhpU76SooHMyMFfM1TkKoZj6TJiZGz4cAcFahYU9%2F0FH0VksJ%2BGtgA1WuxkQ7UDnUcfvJo5mttw5Vl8sdeM9lw264pIzyfg8O2%2Bavj7%2FxlF4s1RAq%2FpvMcJ0Hl1KckFPSI7SeC0f8kG05ngcXXBluO%2Fm80Xq9hyNuFJl5oK7DcyzAyR%2B8XVIL59dF3BjtoYwpvzzzQY6pgFQpTWUetuyme3z1Y9LOt2uc0swBhdh23zYo%2Bs%2BVbEroz0e7BPm87G500WtzgstmGe%2F6TOLe5BMK9hoVLabv%2FbgGMQLmbQgsGiTWZYYKyMRqEAHM%2Bvye6Z4ghTLXwSGptGogFletfTnEh8fhBTMn7fmvz00TO5UEGjpqRSwv0yx3GHaqW%2B9%...')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(192, 'References: - Andy and Sandeep’s investment viewed as positive signal - Mentioned comparable models: - VRBO (US) - Stanza - Quintu - FastFox - [Housing.com/CommonFloor](http://housing.com/CommonFloor) **CV:** WM – non incremental points below. ?? Not compounding – feels very inside out. ?? Cannot sell – and this needs a ton of capital ?? All over the place in a prop that he has designed ?? unsure he will get hands dirty and build it out **TD:** **KK:** **NS:** **Spiky: **0 **EF/FF: **EO (insights of an FF) **Founder Archetype: **6 **FMF: **7 **Thesis: **6 ? No spike, inside out thinking. ? No baseline research from supply or demand side. ? Inarticulate, overcomplicated explanation of a straightforward business model. ? No unique insights being a potential EO. <u>**Meeting Notes**</u> **Team** - [Sahil](https://www.linkedin.com/in/sahilludhani/) (Co-founder) - SRCC grad (2009) - Ex-Zomato: International expansion (launched NZ, Malaysia, Indonesia, Philippines) - Led CloudKitchens & Zomato Gold verticals - Ex-Stanza: Led operations, sales strategy, and supply - [Ashutosh](https://www.linkedin.com/in/ashutosh-tandon/) (Co-founder) - SRCC grad (2012) - Ex-Zomato: Sales & global growth team - Ex-CRED: Built CRED Store - Scaled to 1.5M orders/month - 5-6M monthly users (50% of CRED users) **Problem** - Real estate rental market stuck in “classifieds 1.0” - High friction rental process for both owners & tenants - Large security deposits (4-6 months) blocking access - No standardized...'),
(193, 'Final view 2026-01-09T10:28:00.000+05:30: 1. Trupti is the OG at CRED 1. TD had also emailed about this investment but we are late to it 1. Also, late in DeVC Fund I cycle to consider 1. They are selling to USA and neither is moving to USA 1. Next will be Z47 company 1. From @Aakash 1. Didn''t get over the line given past context of them meandering through multiple thesis areas and co-founder mix. 1. Didnt meet the current (near end of fund cycle) bar on AI bets. 1. Trupthi is a great cred OG crew person, but both seemed non-committal to a full US shift and double down. 1. We should be tracking from Z for sure.'),
(194, 'Current Product: AI Agent for ML Development: - Building “Emily” (MLE) - AI agent that replaces ML developers - Core value prop: One good ML developer + agent = work of 5 developers - Target market: Companies spending $2.5M+ on ML talent (5 developers) - Key differentiator vs AutoML: Can reason through ML problems and generate new strategies, not just hyperparameter search
heads up note 2025-08-29T12:43:00.000+05:30 by @Rahul Mathur: Hi team, Sharing the heads-up note for our investment in [Hexo AI](https://hexo.ai/). This is an AI agent which builds ML pipelines & workflows; it is similar to the coding Devin agent - acts like a member of your ML team DeVC is investing $50K as part of a $3M SAFE round @ $15M post money valuation (standard YC SAFE terms) Note: This is a toe-hold into the company; Cash & I are doing more work (e.g. BRCs, expert chats, network introductions & co-investor connects) & seek to form this round after meeting the founder in SF; we have got positive signal from Soumyadeep (DashReels, Z47 portfolio) and Sudarshan (Smallest AI, DeVC portfolio) **Founders** 1. [Kunal Bhatia](https://www.linkedin.com/in/kunalbhatia91/) - CEO 1. BITS ‘12 - MSc Economics graduate 1. 1.5 YOE as CoFo @ SuperLearn 1. Netflix-like learning platform, 100K users, shut down post-COVID when demand evaporated 1. 4.5 YOE as independent consultant on GovTech projects 1. Built grievance system processing 60M complaints for UP Chief Minister 1. [Vignesh Baskaran](https://www.linkedin.com...'),
(195, 'Dhairen - First Meeting - 2026-02-25: Source: DT via SPC India. Founder is SPC fellow. DT Views: ++ Past track record - 2x founder, Bugle acquired by Acceldata ++ GTM wedge identified through company research platform (Empor) +? Acceldata refs needed to calibrate ?? Urgency and courage of conviction - why not put in own money and hire? ?? Real differentiation ?? Why isn''t SPC leaning in here already --- SHAN''S BACKGROUND - 2x founder with strong technical background - 8 years at Google (Maps search, launched "One Today" product) - Built AI company Bugle (acquired by Acceldata during COVID) - Head of AI/ML at Acceldata for 1+ year post-acquisition PRODUCT EVOLUTION: EMPOR TO HEYFINN Started with Empor (company research website): - Built for personal investing research - 40k organic users, $0 marketing spend - Viral among portfolio managers globally - Compresses initial research time from half-day to 1 hour Discovered real pain point through customer conversations: - Portfolio managers need junior analyst capabilities - Typical junior analyst costs $150k-300k annually - Universe limitation: ~200 stocks vs 10k+ investable globally HEYFINN PRODUCT DETAILS Positioning: AI junior research analyst - 45 days old, 6 professional portfolio managers using it - 5 users outside India, including JP Morgan London manager - $10k annual pricing (customer wants $20k) Core capabilities: - Autonomous monitoring (earnings, management changes, analyst reports) - Adjacent stock investigation based ...'),
(198, 'Ref from [Gaurav Shahlot](https://www.linkedin.com/in/gauravshahlot/) (CPO at Khatabook): <u>Context</u>: Gaurav hired Varun into Khatabook 1. he''s got super strong product chops 1. really good at identifying and breaking down problem statements 1. Was good at talking to users & finding opportunities to move the needle on core metrics. 1. Extremely good at working with engineers and people in general. 1. I would totally trust him to build top notch products. 1. Was one of the stronger PMs in my team. 1. **The only callout from my side would be he gets excited by something new & interesting but could lose interest over time.** ---
Notes:: 1. Journey since last conversation 1. Decided to NOT pursue the BFSI x Indian market 1. Came to SFO 1. Worked on some Enterprise ideas - realized that there is no RTW 1. Now focusing on Consumer AI 1. What in Consumer AI? 1. Companion space 1. Approaching it from a proactive AI lens 1. Context & memory across apps (? how is unclear?) 1. Thinking about the accountability space e.g. go to the gym or do some work 1. Very early thoughts 1. Why come to SF? 1. Felt learnings were saturated 1. All VCs suggested that they move to SFO for learning 1. Fundraise situation 1. Raised ~$10K as an Angel round 1. Would spend ~80% of it over next 2 months 1. Looking to do a small $500K Pre-Seed 1. Action items 1. Get introduced to his father who is GCC head for Exxon Mobil in India 1. Introduce him to Riverline AI to beat some sense into the kids ---')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(200, 'Meeting Notes (17 Feb - Gurgaon Office) - 2026-02-26: TARUN''S BACKGROUND & POLICY BAZAAR JOURNEY: - 13 years in ecosystem, started with comparison websites and SEO/SEM - Built revenue models through Google AdSense, then booking engines - Set up Affle''s partnership platform in India - worked with 500+ brands creating performance marketing and partnership models POLICY BAZAAR ACHIEVEMENTS: - Term insurance: Increased commissions from Rs 700 to Rs 3,400 per transaction in 1.5 years - Investment products: Built high-IRR products (15-18%) competing with mutual funds - Motor insurance: Created CURE model, became contribution positive - Health insurance: Developed "one crore health person" product with 15% additional premium - Key insight: One RM per customer dramatically improves NPS/CSAT and purchase control - Health persistency increased from 70-72% to current levels through dedicated RM - Cross-sell ratios improved from 1.4-1.5x to 2.6x transactions, 4x revenue HULP''S CORE CONCEPT & TARGET MARKET: - Personal assistance for modern families - "Can we take away all the pain in your life?" - Target: Parents with two kids not living with their own parents (dual-income households with Rs 70L+ income) - Subscription model at Rs 3,000-5,000/month - One PA managing 12 families initially, scaling to 25-27 families by year three - Architecture: PA as front-end with specialized desks (travel, maid coordination, government forms) in backend THREE CORE PRODUCT PILLARS FOR DAILY USAGE: 1. Meal...'),
(201, 'Notes:: Dr Marcus Setup clinic and the firm about 5 years ago. Focus is health span and not life span: life span is for only the top echelon and low accessible to all. Health span is the focus where you create widespread impact/effects - Supplements have low barrier to entry and low regulation - Devices increasingly exploding in terms of market size; but increasingly commoditized - Diagnostics is high capex and continuous iteration - Clinics is also high capex - so didn''t think about opening chain of clinics - Saw opportunity in data - wearables driving + diagnostic/blood based testing on the rise People are creating data but don''t know what to do with it. Device agnostic centralized intelligence is a value prop. Building a purely digital first experience + partnered with 1mg thyrocare etc have integrated all devices: whoop, garmin etc etc Collect data into central system - scrub and process it - then build a clinical dashboard for end user "Man in the middle approach" - doc/expert validates the output of rule engine (intellectually notes "it''s not ML yet broadly a rule engine") Positive surprise on hypothesis: willingness of people to try Sick care network fragility during pandemic has pushed people to try lifestyle first Increased willingness combined with social media has also created confusion Science and authenticity is the key invite driver: people see the difference between nutritionist vs a clinical practice "we are the only company in India (comparable in US peter in...'),
(206, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): '),
(207, 'AI Notes:: This meeting was an investment evaluation call with Nirav, founder of Ignosis, an Account Aggregator (AA) orchestration and analytics platform in India''s fintech sector. Company Background: - Nirav founded Ignosis in January 2022 after running Pyramid FinTech (IT services company) - He''s selling Pyramid (~50 Cr valuation) to focus on Ignosis - Previously spent 12 years in New York working in fintech - Based in Ahmedabad with 30-person team (24 tech, 6 non-tech) - Co-founder Chintan handles tech while Nirav handles business - Hiring strategy: Recruit locally from colleges and groom young talent Product & Technology: - Provides AA orchestration across multiple Account Aggregators - Creates 20% improvement in AA conversion rates through intelligent routing - Core analytics layer categorizes transactions, identifies income, spending patterns - Offers white-labeled Personal Finance Management (PFM) solutions - Integrates deeply with clients'' loan origination systems - Competitive advantage: Real-time categorization engine with continuous improvement Business Model & Traction: - 50+ clients with only one churn - ~15-16 crore annual revenue - Two main revenue streams: - Lending analytics (60% of revenue): ₹4-7 per fetch - PFM solutions (40% of revenue): ~₹1-1.5 per active user monthly - MobiKwik is largest customer (40L active users, ~₹40L monthly revenue) - Transaction-level margins around 70% - Profitable, but raising capital for potential AA license acquisition Competi...'),
(208, 'Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score** ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): 
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
De-brief (if any): 
Next conversation with Founder on {use “@now”}: ---
Attendees from DeVC:: 
Z47 Conversation with Founder on {use “@now”}: 
Notes:: 
Attendees:: 
Notes:: 
De-brief (if any): ')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
INSERT INTO util.enrichment_staging (company_id, content) VALUES
(216, 'Received from Rahul - 2026-03-13: [https://www.linkedin.com/in/jagdeep-singh-805b55124?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app](https://www.linkedin.com/in/jagdeep-singh-805b55124?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app) Groww director/business head of broking starting up ---'),
(217, 'Post-Meeting Investor Debrief: The investors expressed skepticism after the meeting. Concerns raised included: - Lack of clear moat despite claims of simple, superior design - Questions about why Xiaomi (known for despeccing products) hasn''t implemented similar design improvements - Uncertainty about learnings from previous startup failure/wind-down - Doubts about founder''s ability to scale in a difficult category The investors agreed to pass on the opportunity. This is all the malls, Phoenix, PurchaseLegal, Nexus, It''s all of the chains, right? McDonald''s, Subway, KFC, a lot of independent types are for $1,000. We''ll start with one. So that was my bread and butter for the longest time. Then in 2021, we decided we wanted to do something else. We no longer wanted to be an app, but we wanted to continue driving to fall to stores. So we came up with what is today the only affiliate program for offline stores, which is like seamless, clean, neat, etc. I ran that for three years until 2024. We raised a lot of money for that business. We were backed by all of the amazing folks, founders of Swiggy, Razorpay, Mama Earth, and so on. I was building a company with my fiancee at the time. We parted ways. And I decided I don''t know, I wanted to pursue that opportunity. We were lucky enough to get an acqui-hire from Razorpay, but we turned that down because it was like one next invested capital for a three-year lock-in. But instead, we rolled up a trust and all of my investors got equity i...'),
(220, 'Web Research:: - From Pilot to Profit: Survey Reveals the Financial Services Industry Is Doubling Down on AI Investment and Open Source Explore NVIDIA’s AI solutions and enterprise-level AI platforms for financial services. NVIDIA and Global Industrial Software Leaders Partner With India’s Largest Manufacturers to Drive AI Boom https://blogs.nvidia.com/blog/ai-in-financial-services-survey-2026/ - AI Goes Vertical in Financial Services - by Singularity AMC This is just one example. Millions of scenarios and insurance offerings, based on their possible outcomes with real-time risk assessment could shape the future of insurance as power of compute continu https://www.singularityone.in/p/ai-goes-vertical-in-financial-services - Top startups in Native AI in Financial Services in India (Dec, 2025) - Tracxn Native AI in Financial Services Sector in India has a total of 81 companies which include top companies like <strong>HyperVerge, Scienaptic and Arya.ai</strong>. https://tracxn.com/d/explore/native-ai-in-financial-services-startups-in-india/__Q1Gma5Dgr6QVb3HupvIku84g3GlxeG-3iONQF1m-lZU/companies - Financial AI: 21 Cases of Artificial Intelligence in Banking • UXDA | Financial UX Design Virtually every major bank has financial AI pilot programs, with common use cases around fraud detection, chatbot customer service and credit risk analysis. The momentum is driven by both competitive https://www.theuxda.com/blog/ai-gold-rush-21-digital-banking-ai-case-studies-cx-transformation - To...'),
(221, '**Background and Role at MPL:**: - Hired during COVID (2019) as Rachit''s replacement in design leadership - Initially hired as AVP of design but needed grooming for the role - Later became head of design after an intermediate hire was let go - Successfully aligned the design team with objective business KPIs - Demonstrated steady leadership during turbulent times, including a 60% team reduction **Key Strengths:** - Meticulous and calm under pressure - Resilient and reliable during challenging periods - Excellent people leader (7-8/10 rating) - Strong at lateral and downward management - Objective in difficult decisions, not letting personal relationships affect judgment - Considered among the top 5 design managers Rachit has worked with **Areas for Development:** - Not strong at upward management - Inverted priority hierarchy: Team > Design > Product > Company (should be reversed) - Rated 5-6/10 as a business leader - Unclear if he would have the foresight to preemptively identify business challenges - Receptive to feedback but had limited progress in business orientation **Recommendations:** - [ ] Consider advising Ketan to find a co-founder who is stronger on business acumen - [ ] Conduct additional reference checks to verify business capabilities - [ ] Assess whether Ketan''s business perspective has evolved since leaving MPL ---
RM Notes: 1. Hired Ketan to replace himself - during COVID | 2019 1. Rachit was going to start another initiative within MPL 1. 2-3 months in real...'),
(222, 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): ')
ON CONFLICT (company_id) DO UPDATE SET content = EXCLUDED.content;
