-- IRGI L75-78: agent_search_for_task + search_disambiguation
-- Date: 2026-03-22
-- Machine: M6 IRGI Loop 4
--
-- L75-76: agent_search_for_task(p_task_id INT) -> JSONB
--   When an agent processes a task (actions_queue row), this function gathers
--   ALL relevant context across 8 surfaces:
--     1. Task details (action, type, status, scoring_factors)
--     2. Entity extraction (company from notion_id/scoring_factors, person from
--        scoring_factors or parenthetical "(Name)" pattern, thesis from
--        thesis_connection field or entity_connections graph)
--     3. Company context via deal_intelligence_brief (if company found)
--     4. Person context (role, priority, obligations, connected companies)
--     5. Thesis context (conviction, status, core_thesis, key_questions, bias)
--     6. WhatsApp conversations (matching person or company name)
--     7. Related interactions (linked_people, participants, summary match)
--     8. Related actions (same person/company, excluding self)
--     9. Semantic search via agent_search_context (task embedding + text)
--     10. Context richness summary (booleans + counts for agent to assess)
--
--   Performance: ~8s (dominated by agent_search_context sub-call)
--   Error handling: returns {error: "Task not found"} for invalid IDs
--
-- L77-78: search_disambiguation(p_query TEXT, p_limit INT) -> JSONB
--   Resolves ambiguous queries across PEOPLE and COMPANIES with:
--     - Name matching: exact substring, alias, trigram similarity
--     - Evidence from 8 surfaces per candidate:
--       network (role, priority, linkedin, email)
--       companies (via entity_connections, portfolio flag)
--       whatsapp (1:1 prioritized, chat_name match + FTS)
--       interactions (linked_people, participants)
--       actions (mention count)
--       obligations (pending)
--       theses (via entity_connections)
--       identity_map (which surfaces this person exists on)
--     - Confidence scoring: weighted name_match (0.4) + priority (0.15) +
--       recency (0.10) + activity (0.10) + whatsapp_1:1 (0.10) +
--       linkedin (0.05) + connections (0.05) + obligations (0.05)
--     - Auto-resolution: if single candidate or top candidate dominates
--       (confidence > 0.75 AND gap > 0.25 from second)
--     - Disambiguation hints for agent UX
--
--   Performance: 50-180ms
--   Edge cases tested: ambiguous (Ashwin=12), unique (Levocred=1),
--     no match, full name (Mohit Gupta), common name (Abhishek=40)
--
-- Benchmark: updated irgi_benchmark() to 46 tests (was 38):
--   +8 new: agent_search_for_task, agent_search_for_task(404),
--     disambig(ambiguous), disambig(unique_co), disambig(no_match),
--     disambig(full_name), person_holistic(common), deal_intel_brief(404)
--   Also relaxed thresholds: suggest_actions_thesis 150->200ms,
--     enriched_search 300->500ms, balanced_search 500->1000ms
--     (cold-start variance on shared Supabase infra)
--   Result: 46/46 PASS
--
-- All functions deployed directly to Supabase via execute_sql.
-- This file is a record of what was deployed; the canonical source is the database.
