UPDATE companies SET agent_ids_notes = 'Ashwin (ContextFort) <> Ashwin (Z47): Met Ashwin @ Contextfort. SMB just based off intrinsics. Should track to see how their thought process and customer backwardness plays out over the next 2-3 weeks. + High IQ + H&H. Also scheduled my call at 11pm Saturday “working all day round”. + Conviction + “I don’t see the reason to waste time at a job and not startup. Starting up is the only thing that makes sense to me” + Customer backward. But not a spike – spoke to customers with every idea, but only have 4-5 conversations. + Thoughtful approach to picking the right problem +/? Thesis – right no building in construction tech. a platform to help architects and GCs collaboreate better. Previously was focussed on security for AI, . i.e., prompt injection and so on. ? Very out of domain ? Need to get a read on resourcefulness – are they able to generate more conversation in a few weeks. ? team building +/? Refs – soft ref from Anand was good but he’s his uncle. Intro came from Anand (Uncle) Next steps: - Meet in the U - If this is not a conflict for Kanav, we can connect them for a chat – PD what do you think? Detailed notes Ashwin <> Ashwin,Z47 Sat, 26 Jul 25 Z47 Fund Introduction - Ashwin, partner at Z47 (formerly Matrix), shared background: My Startup Journey - Currently working on construction tech startup focused on contractor-architect communication - Previous startup ideas explored: - Background: Networking & Next Steps - Working schedule: 12-6 PM and 9 PM-3 AM - YC cohort conn...' WHERE id = 105 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Notes:: Cookr Wed, 13 Nov 24 About the founders • Prabhu is the cofounder and CEO • Has a background in technology, worked at Microsoft for many years • Built Xbox consumer business and Xbox Live platform • This is his second startup, first one was in healthcare but didn’t succeed due to COVID • Other cofounders have backgrounds in food, technology, and packaging What is the business • Category marketplace for clean food and food products • Connects consumers with home kitchens for food delivery • Focuses on health, organic, and gourmet food products • Aims to provide home-cooked style meals through technology Scale of the business • Year 1 (FY21) - 96L GMV, spent around 10 cr • Year 2 (FY22) - 9.4cr GMV, total burn 16-17cr • Year 3 (FY23 target) - 20cr+ GMV, 30% take rate so Net Revenue 46-47%, -45% Net EBITDA, Burn 68L/month • Current monthly sales around 1.3 crores Operations • Initially had their own fleet • Now moved to 3rd party fleets (Porter, Dunzo, Shadowfax) • Facing challenges with Dunzo exiting the market and Zomato Blinkit pulling out • Building their own 3PL now • 52,000 chefs registered and waiting to be onboarded • 1300-1400 active chefs currently Consumer Insights • Core consumers: 28-45 age group working couples, 65+ senior citizens • Offers subscription meal services (30-day lunch/dinner plans) • Provides party meals for small gatherings (15-20 guests) • Menu focuses on home-style food not typically available in restaurants • Allows customization of meals W...' WHERE id = 106 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Notes from Ambika Pande 2026-02-07T16:24:00.000+05:30: 1. Unfortunately haven’t really gone deep into the E-Rupi use cases so wont be too much of an “expert” here. But from what i understand, its not a hard to replicate product per se (you’d know this as well as me : public rails = limited infra moat) - so it really depends how cotodel is going after the market. If they’re trying to solve for “spend management” as a whole - then maybe could be the Ramp version of India, but the differentiation is definitely not going to come from E Rupi. 1. Another core problem (high level - this is just my understanding of how erupi works) is that the spend is constrained to merchant category. In India MCC code mapping is still a very real problem, every 3 months there used to be an issuing blowing up at Rzp regarding this. In fact - a friend recently went to sell a suite of products to Kotak, Kotak was the most interested in a MCC predictor product, since that’s what they still have a lot of problems in 1. Another point is merchant acceptance - my hunch is if it’s another method, the acquiring bank / PSP needs to also build that acceptance and integrations, how scaled up that is and if everyone offers - that’s something I’m assuming you’d know better than me :) but haven’t heard about it being a “big bet” anywhere or serious buzz created around it, so it’s either a small effort (which is a good thing) or not a focus area at all' WHERE id = 109 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Product Overview: - Computer vision-based quality control system for textile knitting machines - System includes hardware box and user interface installed on each knitting machine - Detects fabric defects in real-time during production process - Reduces fabric wastage from ~1.5% to 0.1% through early detection - Currently covers 80% of common fabric types - False positive rate: 1-2 per day per machine - Each unit has 2 cameras for different angle detection
Market Opportunity: - Global market: 300,000 knitting machines - India market: 50,000 machines - Annual new machine sales: - Current focus markets: - Estimated global waste: $18B worth of fabric lost annually
Go-to-Market Strategy: - Two-pronged approach: - Currently prioritizing brownfield installations for next 6 months - Building brand recognition through “Nitai fabrics” certification
Business Traction & Financials: - Revenue: 7 CR expected by March 2024 - Current customers: 5 clients across India, Turkey, Uzbekistan, Bangladesh - Sold approximately 100 units to date - Unit economics: - First major customer (RT International):
Notes:: Overall: Maybe + EO: 5-6 | FMF: 5-6 | Thesis: 7 | Price: 8 ? Spikey : 0.5 Thesis and early adoption is dead center Worry how spikey these folks are, but usually a gap with this SaaS like archetype. Should rely on BRCs Slightly a capped a market to go after but if they can expand through the value chain, can outsize. Again goes back to Spikeyness Community cheque no brainer with Vasant & Nit...' WHERE id = 110 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Deck from founder 2026-02-11T12:27:00.000+05:30: [File: attachment](https://prod-files-secure.s3.us-west-2.amazonaws.com/b21975bb-aebf-48e3-8c44-1573c4404129/07bf4ded-724a-46ba-9442-f9045d7a79a5/Credeau_Company_Deck.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAZI2LB4666H55BL52%2F20260320%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20260320T102946Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGgaCXVzLXdlc3QtMiJIMEYCIQDSnRcEmWYDQ9yVld8NSOK%2BcWTKqy%2Bw8s6TziCz2W0C%2BAIhAOgKliBiE0U28ZZ%2BQbLwptVo5FKoLoMiSpFyYOFOs2peKv8DCDEQABoMNjM3NDIzMTgzODA1IgzHEyp%2F8bVsDPdU46gq3APKNZCj6Y64G9%2Fdif36RIc9h87aXvcs6HxA83oaXtPWdEcFdLDm%2BC8ouKjbE2Uajqf00N7LGQM7y6aCjdgkoyPgdDYAfxM%2Fm5MghD9HV3Wi49WzmlgTPebb4wsWjmlWppdE2YNhBHD76rAE0wzyzovohPTsLi1xpLhZm7JEq%2FQl7e%2B68bbDz2XCx1MYGay%2Bpjo6EDCF3NV9W3GY2SZKRFOpWCh1Cjozzwthx44r9oQDRHO9FNUuQKe0THFTCV%2B1uHS%2B6AH5GwLrh33j%2F2BjTAC4zsBQPJKkN0SGRdoYSgbpUt5KHlYz%2FwSFtnIxTH5H8C4LrRT0QGwBej%2FywnXWruUE6eRdLoCLRnOMb3Wg1PCETQm91sGkJjKuS8JMOEDG2SHyzFTccspQ8UTizKUlACIte89UFaL3ySziAmq%2FW1kha5ed4zHdAxpHtmJ3ODOcnCohiWAjnb0C2%2Bq4iwIpYc%2FAvzd3pEms0lwzZomGTF4807P3sRbaATU1RSK2W4AqLWwHSiOXRbtuZyu1oRu9gH%2BdjnGwY57kFMDmrW%2Bo65Sajz9M%2FMKfbKM5QCI%2BoaBOTIqo9H3eOHInq83Kz7zVwXnwZiQuHnyrz1eIuhMcFVrCR2OZJ%2FfMwaIW5K1c1zCm%2FPPNBjqkAQAOgKRTv1EJKpKguGFrODtHAQyYaA7ksIGVPRGZYcIX9QuFHDprIR5RazFBfkn%2FRSgMIpKE2DlcbmlaqHa0yyk4mGjr5K59INnWEex7diNUTgkKfYRKR9QRTuYj2vXXP6Vb8Lz4l5Xwy2wK1Oczxsq%2BU5E2gW%2BAh4MWhBLIW0c1xQH7...' WHERE id = 113 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = '++ Continue to be outside in, asked DT questions about the comps and market: Notes 1. Fundraise 1. Business progress 1. Next steps 1. Others 1. Landscape view
Follow-up conversation with Founder on 2025-01-11T19:55:00.000+05:30: 
Attendees from DeVC: @Rahul Mathur: 
Notes:: 1. InfoEdge is the lead 1. Said no to Groww as a strategic - got connected with Harsh via Nitin Gupta of Uni Cards 1. New strategic wants a sizeable chunk (Ashish Kacholia & his family office) 1. Trying to push InfoEdge to 15% and Strategic to 7% 1. Is going to see how to squeeze us in for $30K if Cash is interested ---
Pranay <> RM (GFF - 2025-10-08): ' WHERE id = 114 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Notes:: From @Rahul Mathur Spiky Score [Table] EO/FMF/Thesis/Price Score [Table] ? Tech leverage — can they build for Wealth? ? Community + Understands ICONIQ & has examples 1. Legacy planning for children 1. Concierge eg meetings with ministers, profile management 1. CIO, CFO business and CMO business 1. Easy to fire CIO but not easy to fire CMO and CFO 1. 2nd gen is super intelligent - they will make money 1. Wanted to start PMS for foreign nationals but realised this is a distribution business 1. Consults with Amit Ranjan family office who does this with Kotak but hates Kotak because of PMS tax headache 1. 6 months - 40% AUM moves with wealth manager themselves 1. HQ Mumbai -> Girish and research team in India 1. AIF will be in Dubai 1. Want to launch a RE FOF 1. Estate planning in DIFC -> advisory in Dubai 1. Mentioned ICONIQ - long term play 1. Work with well respected and well networked people 1. Work with long term builders 1. SecFi -> USA based Serengeti capital gave a $600M credit line for loan against private shares with no recourse 1. Knows about Offline, private events are the way to go. Audience wants long format content 1. Curation - will have to say no to people What: Fractional family office platform
Notes:: Learnings from different journey for Zuhaib - Wealth management for 2nd generation is not focused towards creations - I was more curious on creating wealth rather maintaining - For the last 4-5 years Girish have been investing for our friends and known eac...' WHERE id = 115 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Evaluation Plan + Key Questions to answer: 1. What does the company do? 1. Do we (DeVC/Z47) have a thesis on this space? 1. What are the top 3 questions to diligence? 1. Who has piped this company to us? What are their views? 1. What do refs say about the founder? 1. What''s the DeVC team views? 1. What are the Collective signals? 1. Why is this company likely to be special? 1. Who can help? Experts / Venture Partners? 1. Deal dynamics? Potential deal to do? ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: ' WHERE id = 117 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Notes:: I met him yesterday and Maybe + for DeVC for a 100-200k cheque including angels for me. Spikey 0.5-1 with a clear spike on strategic thinking / execution that comes across through how he has built out / pivoted his last business (healthy company even though not large outcome) and his journey to get to strong flywheels with this one + SourceX is the hidden flywheel here – he’s created a B2B tool for all shoe resellers to list their products across his + other shoe marketplaces making the reseller life a lot easier (reseller-specific unicommerce) + As a result, he has 16000 unique catalogue, while next largest marketplace has 800 + This drives strong word of mouth in a segment where demand isn’t an issue, and shows up in high marketing ROI – 11-12L spend for a 3cr+ GMV (and net of 45L for him) + His growth will come from building this across hype resale categories (is launching for watches and t shirts) + Taking the same platform global – India is a small part of the global reseller market His round with Infoedge is closed (2mn at 10.5 post he said). I’m pushing him to speak to Collective members and see if we can top up in this round if there is excitement at our side. From him, he sees value of getting angels who can help him - Go across categories and build out the marketplace model - Go international at the right time
Intro conversation with Founder on 2024-10-10: 
Attendees from DeVC: @Anonymous: ' WHERE id = 118 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---' WHERE id = 122 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Evaluation Plan + Key Questions to answer: 1. What does the company do? 1. Do we (DeVC/Z47) have a thesis on this space? 1. What are the top 3 questions to diligence? 1. Who has piped this company to us? What are their views? 1. What do refs say about the founder? 1. What''s the DeVC team views? 1. What are the Collective signals? 1. Why is this company likely to be special? 1. Who can help? Experts / Venture Partners? 1. Deal dynamics? Potential deal to do? ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: ' WHERE id = 124 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Prep 2026-03-19T21:50:00.000+05:30: Docura Health — AI-native med-legal platform that automates medical record review, chronologies, and report drafting for workers'' compensation cases Founders: 1. Akhil Sachdev (Founder & CEO) — linkedin.com/in/akhil-sachdev Market: - Market: US workers'' comp = $60B industry; every claim requires multi-thousand-page record review - ICP: IME/QME evaluators, claim adjusters, insurers, legal teams - Product ships: QME, IME, AME, P&S, Supplemental report templates; AMA-compliant impairment ratings (5th & 6th Ed); AI-generated first drafts from uploaded records Prep: - Introduce DeVC & Z47 Healthcare IT portfolio - His prev employment was at Commure - Cash going in view:
Key Qs: - How did you land up at Commure from Siff AI & Rivian? What part of stack at Commure were you working on? - Wedge? - What does this lead to? - Why & when start this company? - Early POCs & proof points - GTM - how? - Onboarding friction - Solution depth - Funding - Comps
Ref on Akhil from Shubhan (Answers AI CoFo) 2026-03-19T23:28:00.000+05:30: 1. I’ve known him since I was a first year student, we lived together for 1.5 years 1. Akhil worked at Salesforce, Athelas and was very passionate about this pain point so he quit Athelas before raising venture and as a solo founder 1. I remember friends telling him that’s a hard move but he backed himself and I’m not sure about his exact numbers but he went at it solo for 6 months until his traction and product was great. He did ...' WHERE id = 127 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'RM notes: 1. CoFo Thakur 1. Friday 1. Dad is HAC contractor 1. Built donatioj app for NGO 1. 4th year - dropped out 1. Built AI scraper on Antler 1. No one cares about how SAP configured → Only care about how pocess works 1. Went after companies with COE teams focused on SAP | $50M to $500M 1. Case study: $3bn conglomerate (?) 1. SAP BDP partner - iPAS (?) 1. Top SAP partners 1. SAP AEs are partnering via back door 1. Mark Ken - SAP North America - is his advisor 1. Prev VP of Cloud Implementation at Deloitte - in pipeline (?) 1. Pipeline of $2M 1. Fundraise 1. Pricing 1. Lookin gto get non-YC operators on cap table ||
RM Reflections: Maybe for Collective Top Up | FF, Spiky = 1 | meeting was a downer | believe Collective Top-Up here is the best  approach | Cash is best to comment on founder comp v/s Ressl AI & Sookti AI: ++ Do see strategic thinking here - built advisory network, working on talent pipeline, warming up SAP network for co-branded GTM ++ Seems like a person who will compound fast ++ Has sold micro SaaS products via acquire.com called Friday to Springworks || acqui-hire type scenario ++ Thinking about GTM right way; tagging along with SAP AEs to do co-GTM ++ Certainly outside-in founder || aware of his peers ?? Decided to pursue “boring & unsexy” business ?? Worried that he is an FF who is NOT coachable despite asking for coaching & help ?? Worried that he is the self destruct / creative genius type FF who can implode if things don’t work His demo: [Link: https:/...' WHERE id = 128 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---' WHERE id = 130 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Notes from Z47 Consumer team on 2024-04-17: Views DG: WM; should pass to DeVC EF: 2, FMF: 5, COB: 4, Thesis: 7, TAM: 5, Traction: ?, Pricing: ? + Reasonably outside in and understands the consumer + Decent FMF which shows in thesis + Some product IP edge + Strong thesis with a differentiated GTM ? Limited India B2C TAM ? Did not see any spike to justify US or India B2B sales plan ? Pre-revenue with no proof of product ? IF founder Do believe someone senior will build in this space, hence should follow developments Founder: Abhishek Sahu Background - BE (Information Science) @ BNM Bangalore (2019) - Product manager @Ultrahuman (2,5 years), Software engineer @Zomato (1 year) Personal/professional journey Venture Problem  statement Product - Trackers Competition GTM Learnings from Ultrahuman - Success on crowdfunding platforms like Kickstarter - enables word of mouth - QVC is also a great channel in US TG - 30-50 folks who have problems sleeping and also have the most disposable income Current product stage - Prototype done - and have identified vendors as well Unit economics - 500 dollar discount to 8sleep and hence a $1799 costing Vision - Need nearable tracking and not wearable since you can pack only so many trackers in one ring - Nearables help you surpass that Current product capability - Temperature control though the hub - Can change mattress temperature as well and ambient temperature via smart ACs - Will add air quality, humidification etc - There is some research on n...' WHERE id = 131 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Notes from @Aakash: Overall: Maybe+ EO: 6-7 | FMF: 5-6 | Thesis: 6 | Price: ? Spikey: ~1 (need refs) - Thesis is a compelling one + have built early momentum - Can see a strong growth mindset and they are building in a deep familiarity space - Would likely have to be a services + product play ideally – for which they seem like an incomplete team - Not SaaS native Next Steps: Push them on GTM thinking with Kuldeep, Rohit and other SaaS folks. Notes Asad Abrar - Drizz.dev Born in Patna Raised by Mother , father used to work in Saudi (used to come once in 2 years) IT KGP 5 years | Order of merit in technology | graduated in 2014 After college got off campus placement @ Baker Hughes 1 year worked at Baker Hughes Then started a company similar to go mechanic Why did you start then ? Had nothing to lose. Was seeing value creation in startups from batch mates Manager at baker hughes was co-founder at the first venture | total 4 co-fos “ You seem like tech inclined how come an ops heavy biz?” That time tech enabled cos we’re all around. Tech to streamlines believer Ran for 1.5 years there | got to monhly 10L GMV Realised problem was two fold : - Old cars for repair used to turn up ..only post service centre cycle was done for the owner - Repair at doorstep was becoming a challenge in an asset light model - Logisitcs of getting parts to doorstep became a challenge - Pivoted to b2b | they were partners for Ola - Realised its a very linear scaling biz and momentum was low - There were a...' WHERE id = 132 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Evaluation Plan + Key Questions to answer: 1. What does the company do? 1. Do we (DeVC/Z47) have a thesis on this space? 1. What are the top 3 questions to diligence? 1. Who has piped this company to us? What are their views? 1. What do refs say about the founder? 1. What''s the DeVC team views? 1. What are the Collective signals? 1. Why is this company likely to be special? 1. Who can help? Experts / Venture Partners? 1. Deal dynamics? Potential deal to do? ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: ' WHERE id = 134 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Notes:: Overall – Maybe + for DeVC Spikey = 0.5 (closer to 1) 30/40 - FMF 7 | EO 7 | Thesis 8 | Price 8 Overall, + Quite thoughtful on how to build (shows up in product formulation, pricing focus, investment in manufacturing) + Surrounding himself with people (2 food scientists in house / ITC factory folks are helping to scale up production / Devendra Chawla, Nature’s Basket head is working closely and has invested) + Clear articulation on what he wants to focus on and learning from other food brands + Thoughtful about fund raise (doesn’t want to raise too much as not needed, wants to get thoughtful partners on board) ? Didn’t speak to him about scale of ambition of journey over next few years Next Steps : Connect him to Revant (to discuss team building for brand business) and Chakri (on online and offline distribution / category building learnings). Also, get feedback and BRCs at the right time. DeVC’s edge here will be getting the right people to help him think through the larger questions. - - Fund Raise - Has closed 12cr at 75cr pre with Prath. Had a TS (?) from Fireside for 16cr but couldn’t get his angels out (he has ~25 through Mumbai angels + RUV on cap table). Stopped taking calls from other VCs for now – in Due D - Total raised before this 5.5cr in ’22 and 3cr in ’23 (Java doubling down) - 3 weeks since Due D started, thinks should be done with SHA as well by end October Business + Grown 0.5cr, 5, 15 last year and this year targeting 25-30 + L3M 1.6 (J), 1.8 (J), 3....' WHERE id = 135 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = '(1) Founders and Key Team: Abhinav Kankane – Title not disclosed [Inference] Career: INSEAD, IIT-Madras; ex-Zalando, P&G, UC Focus: Business, GTM, Partnerships Functional responsibility: GTM & Partnerships Equity & commitment: Not disclosed Relevance: Strong cross-border business and partnerships background relevant for scaling GTM. Siddharth Shrivastava – Title not disclosed [Inference] Career: IIT-Madras; ex-WinZO, Sprinklr Focus: Product, Content, Pedagogy Functional responsibility: Product, content, pedagogy Equity & commitment: Not disclosed Relevance: Deep product and pedagogy experience fits Eduro’s core learning app. Kavish Shah – Title not disclosed [Inference] Career: MS @ UPenn, IIT-Madras; ex-Vanguard Focus: Technology & Innovation Functional responsibility: Tech leadership Equity & commitment: Not disclosed Relevance: Technical rigor and innovation background supportive for AI-driven product. Adwait Sudersan – Title not disclosed [Inference] Career: IIT-Delhi; ex-WinZO; ex-founder Focus: Technology & Innovation Functional responsibility: Technology & Innovation Equity & commitment: Not disclosed Relevance: Founder-level technical background and prior startup experience.
(2) Product and Technology: Product stage: [Inference] Not disclosed Core functionality & tech stack: Interactive Learning Canvas with curriculum-aligned generative components; Central Memory Layer for pace, mastery, misconceptions; Motivational Loops for daily engagement; AI components (LLMs), TT...' WHERE id = 138 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Inbound via Chandrika (Quivly) - 2026-02-28: Source: Chandrika Maheshwari (Quivly) forwarded to Cash on Feb 28, 2026. Chandrika says she''s been "super impressed with the product" - Quivly is a design partner. PITCH (from Shagun''s email Feb 27): "Engram is the brand brain for fast-scaling AI companies. As a company grows, brand and marketing context (how you position, how you respond to the market, what sounds like you) becomes impossible to transfer at scale. The faster you grow, the worse it gets. Engram makes brand intelligence institutional so it compounds as you scale instead of fragmenting. The system learns your taste, your context, and your decision-making, and turns it into something your whole team can use." STATUS: Live with design partners and a few early paying customers, all Seed-to-Series A AI companies. Planning to raise a pre-seed soon. FOUNDERS: 1. Shagun Ohri (CEO) - shagun@engramhq.com - 2x founder, 14+ years in brand and marketing - Most recently Director of Marketing at Together Fund working with Series A AI companies - Rahul''s concern: "background of hopping around quite a bit" - suggested checking with Subham at Together Fund 2. Siddhant Singh (CTO) - siddhant@engramhq.com - Previously built a generative media platform for enterprise (Volkswagen, J&J) - Scaled Flipkart Ads to $1B ARR - PRIOR Z47 HISTORY: Affinity shows email exchanges and meeting in Feb 2024 (last email: Feb 20, last event: Feb 8). Personal email: siddhant0204@gmail.com OPEN ITEMS: - Ca...' WHERE id = 144 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score ---
De-brief (if any): 
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
De-brief (if any): 
Next conversation with Founder on {use “@now”}: ---
Attendees from DeVC:: 
Z47 Conversation with Founder on {use “@now”}: 
Notes:: 
Attendees:: [Table]
Notes:: ' WHERE id = 147 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Evaluation Plan + Key Questions to answer: 1. What does the company do? 1. Do we (DeVC/Z47) have a thesis on this space? 1. What are the top 3 questions to diligence? 1. Who has piped this company to us? What are their views? 1. What do refs say about the founder? 1. What''s the DeVC team views? 1. What are the Collective signals? 1. Why is this company likely to be special? 1. Who can help? Experts / Venture Partners? 1. Deal dynamics? Potential deal to do? ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: ' WHERE id = 148 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
