UPDATE companies SET agent_ids_notes = 'Boost <> @Aakash / @Sudipto / @Naviya Singh 2025-07-09: Please find below the views and meeting notes from our chat with the Founders of Boost Robotics. Next steps here include making them meet key folks from the DeVC collective, forming a WhatsApp group for the same shortly. Vault links to the following: - Pitch Deck - Research Papers Views Dada (Strong Maybe): Spiky: 1 + Continue to like the founders - spiky, YC archetype. +/? Very early in the product and revenue journey and will have their learning curve on hiring and GTM. + However, spiky enough for us to do a small cheque through DeVC and continue to track Cash (Maybe+): Spiky: 0.5 + Like the guys, good pedigree + Smart GTM strategy: wedge into real-world need (data centers), expand from there. + Will surround them with DeVC collective folks. ? Not in the bay area, going to be hard for them to raise. ? Unsure of how to benchmark and calibrate. NS (Strong Maybe): Spiky: 1 EF/FF: FF Founder Archetype: 8 FMF: 9 Thesis: 8 + Articulate, pedigreed (both founders), clear FMF. + Aligns with internal thesis of robots (non AGVs and AMRs) for specialized use cases. + Already have LOIs and pilot partners. + In the DeVC alley, will help us enter the CMU network. + Met Hans for the first time- liked him, clear tech spike. + Clear articulation of problem and product roadmap. + Both founders are customer backwards- rarity in robotics founders building in the US. Meeting Notes' WHERE id = 67 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Notes:: AS: NS (Strong Maybe) Spiky: 0.5 (Tech spike) EF/FF: FF Founder Archetype: 7 FMF: 8 Thesis: 7 + Strong pedigreed team with domain experience. + Already have ongoing paid pilots with Airbus, Safran, Ministry of Heavy Industries. ? Yash is scientist archetype, not articulate but possesses clear tech spike. ? How big of a market is this? Path to $100 M ARR is unclear. Meeting Notes Team - Abhishek Chopra (CEO and Co-Founder) - Rut Lineswala (Co-founder) - Team size: ~40 people Problem - Current simulation software extremely slow & computationally expensive - Engineers forced to choose between: - Example: Aircraft simulations take 6 months on 250,000 parallel computers - Algorithms haven’t changed since 1970s - GPUs underutilized (only 30-35% capability used in engine simulations) Product - BQFi: Backend engine for simulation software - Uses quantum-inspired algorithms on existing hardware - Key features: - Technical differentiator: Uses stochastic math & quantum-inspired gates - Can find global minima faster than genetic algorithms Go-to-market - Initial focus: Aerospace & Defense sector - GTM Strategy: Conference presentations, keynotes, booth setups - Position as backend engine for existing simulation software - Target customers: Airbus, Israel Aerospace, Air Force Research Lab - Future expansion planned into biotech, pharma, finance Traction - Major pilot with Airbus: - Pipeline includes: Funding - Currently raising seed round: - Series A metrics set:' WHERE id = 68 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Meeting Notes — Feb 20, 2026: 1. Reco product has taken off 2. Do follow up meeting next week 3. Feedback from CD and ID - why are they using it 4. Payment orchestrator isn''t clicking' WHERE id = 70 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Ref from Priyans (CoFo): Context: Priyans was a CoFo of the Breethr founders in their prev company ActiveBuildings Notes: 1. Priyans is also involved in Breethr - more on back office 2. Priyans also runs an EV business - he is more focused there 3. Priyans and Abhinav met on BITS Goa campus in 2010 - filed patents together, research together and both decided to do something in hardware together 4. Pivoted to air quality in 2014 5. ActiveBuilding had a F&F round 6. Manav was hired around COVID (2020) when they were doing a Swiggy project - Manav had an inside sales background and was boots on ground in BLR 7. Abhinav and him are hands on founders 8. Peak was 30 employees in 3 cities 9. Peak revenue was ₹7 crore - ₹1 crore PAT 10. Sensor doesn''t make as much money as solutions 11. Abhinav was great at B2B deals eg Reliance NetMeds 12. NetMeds warehouse - temperature and humidity monitoring 13. Abhinav used to crack deal and then Priyans would do implementation 14. Still has positive relationship with Abhinav 15. Pandemic era - got $50L from DOD for Kavach grant 16. PAPR - Priyans and Abhinav built this solution, but by then PPE was in the vogue, army wanted something more sturdier 17. PAPR journey gave them an idea of how solutions are built 18. Started as distributors of air purifiers 19. Simple product is easy, sexy product needs capex investment 20. Closed a ₹2 crore order during pandemic for MI team (for ActiveBuilding) 21. Call center incident - Disprin stock was still wit...' WHERE id = 71 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Evaluation Plan + Key Questions to answer: 1. What does the company do? 1. Do we (DeVC/Z47) have a thesis on this space? 1. What are the top 3 questions to diligence? 1. Who has piped this company to us? What are their views? 1. What do refs say about the founder? 1. What''s the DeVC team views? 1. What are the Collective signals? 1. Why is this company likely to be special? 1. Who can help? Experts / Venture Partners? 1. Deal dynamics? Potential deal to do? ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: ' WHERE id = 72 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Attendees: Full Z47 team: Briskpe Views RC -Weak Maybe Archetype 3/4 +Liked Indu a little more than Aloke and Sanjay, FMF- Below 5 + More than expected amount of work on regulatory piece and customers. + Ahead in terms of reg thinking and execution compared to others. ? Bold choice on the segment → Feels like they’ve underestimated the challenges of the segment they are going after though. Not sure they’re fully cognizant of digital strengths of the other players / are thinking along those lines. Avi – Very easy pass Low Archetype, IFs + Aloke has some conviction. ? FMF is 0, Not my archetype → Indu is just words not content - Struggling to give a clincher reason why to pass , “there’s a few things such as the teams background that makes you pause they say some of the right things but it never really ties together.” ?Complete IFs stumbling from one insight to another. ? Not sure if the refs on Sanjay are high quality. (Would not give any weight to Gaurav Chopra’s ref either) → Navin might have a positive view but he likes these kind of founding team. ? Sanjay is someone who has never compounded in life, and everything he has done post HDFC (Venture Studio) is scattered → This journey also seems scattered. VV-Weak maybe Insight / spike missing / edge missing. Depth in biz model / product etc Sanjay more thoughtful than I gave him credit for Team, Talent, Cost/frugality, pivot at the right time, bend at the right time 7 days digital journey vs offline; more digital thinking tha...' WHERE id = 73 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'RM notes: Next steps - BRC w/ DoWhile AI CoFo from RM + 2PE with Kinzy & Bunny with RA & Mohit Notes 1. Naman Jain - Elder brother 1. Nishchal Jain - Younger brother 1. Startup journey 1. DoWhile AI 1. Tinkering together post SPC and LossFunk 1. Buny 1. Why pendant? 1. Started to spend too much time on hardware - “juice is in AI” 1. How did walkie talkie come about? 1. Demo video 1. Cash Q: Why not go full fictional characters like EMoMee? 1. Cash Q: Hardware - why not make it a analogue kid mobile? 1. What are you hiring for? 1. Parent mobile 1. Initial market (?) 1. Comps: 1. Can offer personalized learning storybooks | learning activities → personalized 1. Customers 1. Learning from Osmo founder - keep founder healthy & high 1. $150 retail price for hardware 1. Technology
RM Notes: 1. Shubham knows Deepak 1. Knows Aniket Kamte from Nexus VP 1. Left Google because he wanted to take some risk 1. Joined DoWhile AI when it was called Collective AI 1. v/s othr companies 1. Mandalin is his current co 1. Convinction / motivation lacking at the firm - didn’t have as many wins 1. Going to meet them in SF 1. Come a long way - motivated now versus before 1. He feels choice of market isn’t something he would do 1. They need a CTO/ VPEng
Cash reflections -  Weak Maybe. Community cheque at best.: 1. Pure inside out FFs with no clear consumer spike 1. Have built and landed on a much better form factor (hardware and software) in the entire audio ai toy for kids than all other teams we hav...' WHERE id = 75 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'RM reflections - dead center Maybe | 0.5% cheque = $150K IFF we go ahead w/ this: ++ Pedigreed team given 4 YOE @ Loom - worked closely w/ founders on the Loom AI launch ++ Thesis (MUCH more than Cash & KB): For me, this it Limitless 1.0 i.e. agent running in the background learning everything about you ++ Design principle struck a deep chord with me: Voice to be used for editing the “first draft” created by the Caddy Agent ++ Good set of learnings captured by them - Enterprise plan beyond billing consolidation & SSO ++ Do sense they have GTM chops; not just Product builders - but yet to be proven out / demonstrated ?? Worried that they will repeat the same Loom mistakes i.e. build a horizontal OS level product which will struggle to capture Enterprise revenue ?? Worried that their landing wedge is dictation - didn’t hear anything about actions - therefore, Wispr Flow is the competition ?? Underestimating the amount of configuration & customization needed to make even dictation work Mid Feb ‘26 launch Key Qs - business 1. Why choose to go after this problem? 1. Why standalone app & not OS level solution? 1. What do “actions” require v/s Wispr which is transcribing today
RM’s suggestion = 0.5% ownership i.e. $150K cheque 2025-12-12T22:39:00.000+05:30: BRC w/ Joe (Loom CoFo) took me from Maybe to SM - sticking to the 0.5% ownership target i.e. $150K cheque size Why $150K? - Connor (founder we are underwriting) is Spiky = 1 - rapid career trajectory from intern to Eng to PM to G...' WHERE id = 78 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Evaluation Plan + Key Questions to answer: 1. What does the company do? 1. Do we (DeVC/Z47) have a thesis on this space? 1. What are the top 3 questions to diligence? 1. Who has piped this company to us? What are their views? 1. What do refs say about the founder? 1. What''s the DeVC team views? 1. What are the Collective signals? 1. Why is this company likely to be special? 1. Who can help? Experts / Venture Partners? 1. Deal dynamics? Potential deal to do? ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: ' WHERE id = 79 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Evaluation Plan + Key Questions to answer: 1. What does the company do? 1. Do we (DeVC/Z47) have a thesis on this space? 1. What are the top 3 questions to diligence? 1. Who has piped this company to us? What are their views? 1. What do refs say about the founder? 1. What''s the DeVC team views? 1. What are the Collective signals? 1. Why is this company likely to be special? 1. Who can help? Experts / Venture Partners? 1. Deal dynamics? Potential deal to do? ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: ' WHERE id = 81 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Evaluation Plan + Key Questions to answer: 1. What does the company do? 1. Do we (DeVC/Z47) have a thesis on this space? 1. What are the top 3 questions to diligence? 1. Who has piped this company to us? What are their views? 1. What do refs say about the founder? 1. What''s the DeVC team views? 1. What are the Collective signals? 1. Why is this company likely to be special? 1. Who can help? Experts / Venture Partners? 1. Deal dynamics? Potential deal to do? ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: ' WHERE id = 82 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Evaluation Plan + Key Questions to answer: 1. What does the company do? 1. Do we (DeVC/Z47) have a thesis on this space? 1. What are the top 3 questions to diligence? 1. Who has piped this company to us? What are their views? 1. What do refs say about the founder? 1. What''s the DeVC team views? 1. What are the Collective signals? 1. Why is this company likely to be special? 1. Who can help? Experts / Venture Partners? 1. Deal dynamics? Potential deal to do? ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score [Table]
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: ' WHERE id = 84 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
Scoring (can be copied for multiple people): Spiky Score [Table] EO/FMF/Thesis/Price Score ---
De-brief (if any): 
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
De-brief (if any): 
Next conversation with Founder on {use “@now”}: ---
Attendees from DeVC:: 
Z47 Conversation with Founder on {use “@now”}: 
Notes:: 
Attendees:: [Table]
Notes:: ' WHERE id = 87 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Discussion on 20.09.2024: 1. Cash flow position 1. Learnings so far 1. Business right now 1. Discussions with others 1. Next steps 1. RM Reflections
Investor updates (since RM is an Angel): [Page: April 2024 Update] [Page: May 2024 update] [Page: June 2024 update] [Page: July 2024 update] [Page: August 2024 update]' WHERE id = 88 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Z47 meeting 2025-10-23: KK Overall view: WM for DeVC Spikey: 0 to 0.5 ++ resourseful ++ hustler ++ intellectually honest ++ outside in ++ staying right things on thesis ?? numerate not much ?? not commercial ?? no consumer insight TK Overall View: WM to Maybe- for DeVC and WM for Z Spikey: 0 Spike Needed: consumer/product and exec ops ++ hustler and hardworking ++ highly iterative; take  customer feedback and improve ++ Jugaadu types; copy insight from other companies and them execute ++ Dhandha mindset ?? Not brand builder types ?? still have more drop shipping mentality; look at trends and some learnings from Kishore biyani; quickly copy it without thinking much ?? no unique thought process ?? trying to too do many things at the same time ?? no key differentiation Detailed Meeting Notes (23.10.25) Founder Background - Vedang (22), Psychology major; started Clapstore in 2020 during COVID lockdown while in 11th–12th grade - First-time founder from a family of educators (mother: govt college lecturer, father: tuition teacher); driven by desire to be first in family to build a business and have autonomy - Initially aspired to join defense services; COVID shifted focus to entrepreneurship—started with dropshipping via TikTok (US market), scaled to ₹6–7L per month before facing supplier scams - Transitioned from dropshipping to buying from manufacturers and managing own packaging/dispatch; later evolved into designing and manufacturing products after discovering success with non-...' WHERE id = 90 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Ref from Anand (CEO @ MinIO): Got a ref from Anand, CEO @ MinIO; Great kid and sharp, but concerns on 0-1 and will leave this in the pass category for us. - Top 3 engineers for his tenure that AB has seen over the years - Problem solver and will be able to figure out any domain you through at him - Steep learnings curve - Humble, seeks advice, etc - H&H - worked amongst the hardest in his team ? Needs direction for 0-1. someone has to guide him the right direction. Can solve problems, but needs a guiding hand on what problem to focus on; ? Not angel investing because of the domain. AB doesnt get the space and not sure why sid picked it. Detailed notes Anand context - deeply involved in product and engineering side - he was part of our AI team - he was under 2 other AI leads - He started as an intern - he was a fresher but worked at a senior engineer levl - he was part of senior discussions as well - very good problem sovler - he is the perfect kid every parents dreams of - very skilled, hardowrking, no bad habits, sharp - He works really hard; hardest in the team - Skillset wise - fast learner - very sharp learning curve - how you think about rpoblem solving and picking the right approach, he had good clarity - what i dont know enough - his domain in real estate - picked real estate as a market but i cant guage enough on wether its a real problem - realtors are bad customers - dont know how big it is - Relative grading to others - dont like interns - but he was one of the few...' WHERE id = 92 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Ashwin''s Series A Notes - Summary - 2026-01-30: **Founders:** Akash, Neel, Prajwal - All IITM ''22 grads, no prior work experience. **Round:** Series A - $10M raise, wants $80M post. Has offer from US fund at lower valuation. **KP Views:** WMB and pass - also speaking to seed investor for reference. **NOTE FOR V:** FYI in case you''d like to meet them, but Ashwin doesn''t see us doing this round. --- **POSITIVES** **Tech spike:** Strong technical team solving tough challenges. **Founder quality:** "Akash is sharp and spiky on intrinsics. Not overly aggressive, but he''s consistently been at it." **Traction (~$2M ARR):** Added ~$1M ARR in last 6 months. --- **CONCERNS** **Thesis - AI-first Loom:** Shoot explainer/product videos with AI voiceovers, graphics, auto-zoom. "Started with L&D, then moved to sales, then customer success, and now thinking of jumping to marketing. Overall, the approach feels too iterative for my liking - throwing 10 things at a wall to see what sticks." **GTM:** "Growth is good, but there''s still no repeatable GTM motion. It feels sporadic and heavily LinkedIn-driven (founder posts)." **ACVs:** Mostly less than $5K. Largest enterprise customer ~$40K, but most are small teams. **Auto content updating:** Looking to launch feature connecting to video repositories. "Companies like GitHub have dedicated teams for this, so it could be an interesting thesis. But given how much they''ve jumped around historically, I''m not confident this will stick either."' WHERE id = 94 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Marketscan & Breakdown by Trinika 2025-09-12: Hi Team, Adding the breakdown of market landscape and workflow in the excel here Quick summary of key questions below: ![](cid:3199483326*image001.png@01DC22BC.55A4C510) Is the problem big enough? - Yes, because in a content/video production process, three prep tasks - proxy creation, renaming/restructuring, and audio–video sync - together take ~5-7% of the total production budget and ~10-15% of assistant editor time. - Example: a 60-second ad or micro-drama with 4 cameras and separate sound typically needs 20-30hrs from AE before the first cut - iteration speed is higher for microdrama so faster speed req - TAM (for these three steps): Global ~$3B; US ~$1.2B. - SAM (automation wedge): Global ~$1.5B; US ~$0.5B. - At 10% penetration of SAM: ~$150M ARR global; ~$50M ARR US Big gaps in workflow today? - Camera card to storage: For most cameras, copying from card to local drive and cloud is still manual. Only Canon paired with Frame.io (Adobe-owned) auto-copies to both. - Transfer & naming: Cameras save files as C0001 or A002C012; editors need script-friendly names like Scene3_Take5. Renaming remains manual. - Project & bins: Folders nomenclature varies from agencies to agencies – some do it by - day, by actor, or scene. No tool auto-restructures into clean bins/folder by scene/shot/take. - Audio–video sync: Tools handle clear lip-sync, but struggle when lips aren’t visible or timing is creative. Example: a voice-over on a montage, or...' WHERE id = 95 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'AI notes: This transcript captures a reference check call with Rohit about Vishal, a former colleague from LiveSpace, followed by a discussion about Aptile''s upcoming product launch. Reference Check on Vishal Background and Role at LiveSpace - Vishal was among the first four team members at LiveSpace - Worked at LiveSpace for 5-6 years (2015-2021) - Grew from software engineer to director of engineering - Headed the CMS and pricing engine for on-demand construction of home interiors - Managed complex technical systems independently without much support Working Style and Strengths - Described as reliable, dependable, and level-headed - Technically outstanding and thoughtful in decision-making - Calm demeanor, especially during conflicts or heated discussions - More prepared and thoughtful before communicating ideas - Works well with different personalities in cross-functional settings - Considered among the top 5 team members Rohit has worked with Areas for Development - Not naturally charismatic or outspoken in communication - Might face challenges in business model development and identifying margin opportunities - As a technical founder, may need complementary skills for business aspects - Would benefit from hiring team members with complementary business skills Aptile Product Launch Discussion Action Items - [ ] Rohit to prepare and send early access package including: - [ ] Rahul and Mohit to help promote Aptile on LinkedIn (they have 110K and 50-55K followers respectivel...' WHERE id = 96 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Received from Rahul - 2025-11-09: https://www.linkedin.com/in/ashishpratapdoshi/ <- CollektAI in Collections - came up in convo w/ CRED Cash Collections POC who Miten introduced me to Screen | P0 | POC: Rahul Mathur ---' WHERE id = 97 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Received from Rahul - 2026-03-13: Building in Fintech - PFM with a great wedge. This is a short blurb: CA sees taxes, not investments.  Broker sees investments, not liabilities.  Bank sees balances, not goals. India''s 2 crore ₹30L+ income households have three advisors and no one who owns the outcome. Command is that entity. A personal finance agent that unifies accounts, loans, taxes, and investments and converts the full picture into proactive, executable actions. Before you ask. India''s Account Aggregator framework makes unified financial data real. AI makes continuous personalised optimisation possible. The financial rails are live. We''re building above every bank, broker, and insurer in India, the default decision layer for the end customer, the operating system for personal finance. Ankur Garg (Ex- Great Learning, Capital One, Morgan Stanley), Varun Gupta (Ex- Embibe, Ola, Linkedin) ---' WHERE id = 98 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Background & Experience: - Previously at Microsoft in OfficeAI team, led voice experiences (grew to 6M users) - Led product work on Microsoft Designer team (AI-native design engine) - Worked at Prathyush as first PM (10th/11th employee) - Left in December to explore new opportunities
Market Strategy: - Targeting two segments: - Testing with both segments to identify common primitives - Sees opportunity in Canva’s current “bloated” state with AI features
Overall: Weak maybe: EO: 6-7 | Thesis: 5 | FMF: 6-7 | Archetype: 7-8 | Spike: 0.5 ++ Has the product spike but to omuch meandering SPC archetype with little focus on GTM ++ Is thoughtful and assimilates inputs and feedback ?? Wants to build a creation tool for creative agencies ?? Hasn’t spent much time. Thinking and prouct protype that she showed was poorere than first set of control net product workflows seen in AI community ?? Lacks the GTM muscle both for prosumer growth and b2b sales led ?? Wasn’t deeply calibrated on vairous plays beyond krea and more horizontal tools
Current Project Overview: - Building AI-native video editor with custom workflows - Key features: - Started development ~3 weeks ago - Testing with initial partners:
Technical Approach: - Focus on solving iteration challenges in AI generation - Built on open source models - Aims to reduce costs (target: significantly below current $100 cost for multi-tool workflows) - Integrates multiple capabilities:' WHERE id = 101 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Prep 2026-03-19T23:33:00.000+05:30: Confluence Labs (YC W26) | confluence.sh What they do AI research lab building foundation models optimised for learning efficiency in data-sparse domains — drug design, materials science, hardware engineering, physics discovery. Their thesis: modern ML only excels where you can collect massive training data. In domains where data is expensive or slow to generate (physical experiments), current AI fails. Confluence''s approach: combine LLMs with discrete program synthesis to maximise what you can learn from a small number of experiments. Two-track strategy: 1. Hypothesis generation — AI that designs maximally informative experiments so each one teaches you the most 1. Data-efficient modelling — program synthesis + LLMs to make predictions with far fewer data points Technical milestone Came out of stealth with 97.9% on ARC-AGI-2 at $11.77/task — SOTA at launch (Feb 2026). ARC-AGI-2 is considered one of the hardest AI benchmarks in the world (tests novel reasoning from just a few examples). Approaching 100% on what was previously considered unsolvable. Open-sourced the solver. Backed by YC and Paul Graham personally. --- Founders 1. Brent Burdick (Co-Founder) — [LinkedIn not publicly indexed] 1. Niranjan Baskaran (Co-Founder) — linkedin.com/in/niranjan-baskaran-a906a5205 Both are extremely young (combined age ~43), no traditional industry pedigree — pure research talent profile. The Paul Graham backing is notable signal here.' WHERE id = 103 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
