UPDATE companies SET agent_ids_notes = 'Prep 2025-09-03T09:06:00.000+05:30: [File: download](https://prod-files-secure.s3.us-west-2.amazonaws.com/b21975bb-aebf-48e3-8c44-1573c4404129/ac6d370f-0d1d-45ed-b9dc-8d1a76100cfb/Semel_Shah_Haystack_OnePager.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAZI2LB466Z4A6JIV6%2F20260320%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20260320T102927Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGgaCXVzLXdlc3QtMiJGMEQCIGftJyDy4JSgt75dFJdnDE%2F%2BeAC%2FO2wBJkvT%2FQ6cCswPAiBDR2INkZIi1iz744cF3nD7DySgkWgE7mUsaCiMikBjGyr%2FAwgxEAAaDDYzNzQyMzE4MzgwNSIMD9%2BhMHa8F%2Bm7b0L6KtwDb2I0V3HgxiKKwtxYU56TuH2%2BeMlW2Kx58Ull7z5FZom85fLEeVLHba121J0og2No0r3aKZ1MNc23Pyv5%2FGZjX3kBtUx1w9w9pQj6HfHNPvEnN6LmIdbM1fww0paURRv1X9jjVaMR6eW8yNwoamxY9kQ1Zmni3ML6HTZAllI5FAaY4Bz8oiNbd5uMAR8%2F17M1BMcFF2FYTlC3wZ%2Bq0pVESLs1pcq%2BxetJVMlP7IykymIVe3iF6q7m868%2BysLcn40C6o%2BQQZ3BlwWd18xKJ3vT2q%2B555OulXT%2Fh%2BH6ITFKqTNvxRFB4lAEhWJSDDsAHtsGlPFWC3x%2FD3JysKhgVjRQyYnjyVJrSN1QpRG1yOLNUgU01ZQYs3bwKOVSIjuOss2Wg1XbNblmf6GVqkKPA7oJJ2Klfw6GObroRMSOfMa0UPTsWTURcOHuCNWpFdhsuhpU76SooHMyMFfM1TkKoZj6TJiZGz4cAcFahYU9%2F0FH0VksJ%2BGtgA1WuxkQ7UDnUcfvJo5mttw5Vl8sdeM9lw264pIzyfg8O2%2Bavj7%2FxlF4s1RAq%2FpvMcJ0Hl1KckFPSI7SeC0f8kG05ngcXXBluO%2Fm80Xq9hyNuFJl5oK7DcyzAyR%2B8XVIL59dF3BjtoYwpvzzzQY6pgFQpTWUetuyme3z1Y9LOt2uc0swBhdh23zYo%2Bs%2BVbEroz0e7BPm87G500WtzgstmGe%2F6TOLe5BMK9hoVLabv%2FbgGMQLmbQgsGiTWZYYKyMRqEAHM%2Bvye6Z4ghTLXwSGptGogFletfTnEh8fhBTMn7fmvz00TO5UEGjpqRSwv0yx3GHaqW%2B9%...' WHERE id = 190 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'References: - Andy and Sandeep’s investment viewed as positive signal - Mentioned comparable models: - VRBO (US) - Stanza - Quintu - FastFox - [Housing.com/CommonFloor](http://housing.com/CommonFloor) **CV:** WM – non incremental points below. ?? Not compounding – feels very inside out. ?? Cannot sell – and this needs a ton of capital ?? All over the place in a prop that he has designed ?? unsure he will get hands dirty and build it out **TD:** **KK:** **NS:** **Spiky: **0 **EF/FF: **EO (insights of an FF) **Founder Archetype: **6 **FMF: **7 **Thesis: **6 ? No spike, inside out thinking. ? No baseline research from supply or demand side. ? Inarticulate, overcomplicated explanation of a straightforward business model. ? No unique insights being a potential EO. <u>**Meeting Notes**</u> **Team** - [Sahil](https://www.linkedin.com/in/sahilludhani/) (Co-founder) - SRCC grad (2009) - Ex-Zomato: International expansion (launched NZ, Malaysia, Indonesia, Philippines) - Led CloudKitchens & Zomato Gold verticals - Ex-Stanza: Led operations, sales strategy, and supply - [Ashutosh](https://www.linkedin.com/in/ashutosh-tandon/) (Co-founder) - SRCC grad (2012) - Ex-Zomato: Sales & global growth team - Ex-CRED: Built CRED Store - Scaled to 1.5M orders/month - 5-6M monthly users (50% of CRED users) **Problem** - Real estate rental market stuck in “classifieds 1.0” - High friction rental process for both owners & tenants - Large security deposits (4-6 months) blocking access - No standardized...' WHERE id = 192 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Final view 2026-01-09T10:28:00.000+05:30: 1. Trupti is the OG at CRED 1. TD had also emailed about this investment but we are late to it 1. Also, late in DeVC Fund I cycle to consider 1. They are selling to USA and neither is moving to USA 1. Next will be Z47 company 1. From @Aakash 1. Didn''t get over the line given past context of them meandering through multiple thesis areas and co-founder mix. 1. Didnt meet the current (near end of fund cycle) bar on AI bets. 1. Trupthi is a great cred OG crew person, but both seemed non-committal to a full US shift and double down. 1. We should be tracking from Z for sure.' WHERE id = 193 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Current Product: AI Agent for ML Development: - Building “Emily” (MLE) - AI agent that replaces ML developers - Core value prop: One good ML developer + agent = work of 5 developers - Target market: Companies spending $2.5M+ on ML talent (5 developers) - Key differentiator vs AutoML: Can reason through ML problems and generate new strategies, not just hyperparameter search
heads up note 2025-08-29T12:43:00.000+05:30 by @Rahul Mathur: Hi team, Sharing the heads-up note for our investment in [Hexo AI](https://hexo.ai/). This is an AI agent which builds ML pipelines & workflows; it is similar to the coding Devin agent - acts like a member of your ML team DeVC is investing $50K as part of a $3M SAFE round @ $15M post money valuation (standard YC SAFE terms) Note: This is a toe-hold into the company; Cash & I are doing more work (e.g. BRCs, expert chats, network introductions & co-investor connects) & seek to form this round after meeting the founder in SF; we have got positive signal from Soumyadeep (DashReels, Z47 portfolio) and Sudarshan (Smallest AI, DeVC portfolio) **Founders** 1. [Kunal Bhatia](https://www.linkedin.com/in/kunalbhatia91/) - CEO 1. BITS ‘12 - MSc Economics graduate 1. 1.5 YOE as CoFo @ SuperLearn 1. Netflix-like learning platform, 100K users, shut down post-COVID when demand evaporated 1. 4.5 YOE as independent consultant on GovTech projects 1. Built grievance system processing 60M complaints for UP Chief Minister 1. [Vignesh Baskaran](https://www.linkedin.com...' WHERE id = 194 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Dhairen - First Meeting - 2026-02-25: Source: DT via SPC India. Founder is SPC fellow. DT Views: ++ Past track record - 2x founder, Bugle acquired by Acceldata ++ GTM wedge identified through company research platform (Empor) +? Acceldata refs needed to calibrate ?? Urgency and courage of conviction - why not put in own money and hire? ?? Real differentiation ?? Why isn''t SPC leaning in here already --- SHAN''S BACKGROUND - 2x founder with strong technical background - 8 years at Google (Maps search, launched "One Today" product) - Built AI company Bugle (acquired by Acceldata during COVID) - Head of AI/ML at Acceldata for 1+ year post-acquisition PRODUCT EVOLUTION: EMPOR TO HEYFINN Started with Empor (company research website): - Built for personal investing research - 40k organic users, $0 marketing spend - Viral among portfolio managers globally - Compresses initial research time from half-day to 1 hour Discovered real pain point through customer conversations: - Portfolio managers need junior analyst capabilities - Typical junior analyst costs $150k-300k annually - Universe limitation: ~200 stocks vs 10k+ investable globally HEYFINN PRODUCT DETAILS Positioning: AI junior research analyst - 45 days old, 6 professional portfolio managers using it - 5 users outside India, including JP Morgan London manager - $10k annual pricing (customer wants $20k) Core capabilities: - Autonomous monitoring (earnings, management changes, analyst reports) - Adjacent stock investigation based ...' WHERE id = 195 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Ref from [Gaurav Shahlot](https://www.linkedin.com/in/gauravshahlot/) (CPO at Khatabook): <u>Context</u>: Gaurav hired Varun into Khatabook 1. he''s got super strong product chops 1. really good at identifying and breaking down problem statements 1. Was good at talking to users & finding opportunities to move the needle on core metrics. 1. Extremely good at working with engineers and people in general. 1. I would totally trust him to build top notch products. 1. Was one of the stronger PMs in my team. 1. **The only callout from my side would be he gets excited by something new & interesting but could lose interest over time.** ---
Notes:: 1. Journey since last conversation 1. Decided to NOT pursue the BFSI x Indian market 1. Came to SFO 1. Worked on some Enterprise ideas - realized that there is no RTW 1. Now focusing on Consumer AI 1. What in Consumer AI? 1. Companion space 1. Approaching it from a proactive AI lens 1. Context & memory across apps (? how is unclear?) 1. Thinking about the accountability space e.g. go to the gym or do some work 1. Very early thoughts 1. Why come to SF? 1. Felt learnings were saturated 1. All VCs suggested that they move to SFO for learning 1. Fundraise situation 1. Raised ~$10K as an Angel round 1. Would spend ~80% of it over next 2 months 1. Looking to do a small $500K Pre-Seed 1. Action items 1. Get introduced to his father who is GCC head for Exxon Mobil in India 1. Introduce him to Riverline AI to beat some sense into the kids ---' WHERE id = 198 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Meeting Notes (17 Feb - Gurgaon Office) - 2026-02-26: TARUN''S BACKGROUND & POLICY BAZAAR JOURNEY: - 13 years in ecosystem, started with comparison websites and SEO/SEM - Built revenue models through Google AdSense, then booking engines - Set up Affle''s partnership platform in India - worked with 500+ brands creating performance marketing and partnership models POLICY BAZAAR ACHIEVEMENTS: - Term insurance: Increased commissions from Rs 700 to Rs 3,400 per transaction in 1.5 years - Investment products: Built high-IRR products (15-18%) competing with mutual funds - Motor insurance: Created CURE model, became contribution positive - Health insurance: Developed "one crore health person" product with 15% additional premium - Key insight: One RM per customer dramatically improves NPS/CSAT and purchase control - Health persistency increased from 70-72% to current levels through dedicated RM - Cross-sell ratios improved from 1.4-1.5x to 2.6x transactions, 4x revenue HULP''S CORE CONCEPT & TARGET MARKET: - Personal assistance for modern families - "Can we take away all the pain in your life?" - Target: Parents with two kids not living with their own parents (dual-income households with Rs 70L+ income) - Subscription model at Rs 3,000-5,000/month - One PA managing 12 families initially, scaling to 25-27 families by year three - Architecture: PA as front-end with specialized desks (travel, maid coordination, government forms) in backend THREE CORE PRODUCT PILLARS FOR DAILY USAGE: 1. Meal...' WHERE id = 200 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Notes:: Dr Marcus Setup clinic and the firm about 5 years ago. Focus is health span and not life span: life span is for only the top echelon and low accessible to all. Health span is the focus where you create widespread impact/effects - Supplements have low barrier to entry and low regulation - Devices increasingly exploding in terms of market size; but increasingly commoditized - Diagnostics is high capex and continuous iteration - Clinics is also high capex - so didn''t think about opening chain of clinics - Saw opportunity in data - wearables driving + diagnostic/blood based testing on the rise People are creating data but don''t know what to do with it. Device agnostic centralized intelligence is a value prop. Building a purely digital first experience + partnered with 1mg thyrocare etc have integrated all devices: whoop, garmin etc etc Collect data into central system - scrub and process it - then build a clinical dashboard for end user "Man in the middle approach" - doc/expert validates the output of rule engine (intellectually notes "it''s not ML yet broadly a rule engine") Positive surprise on hypothesis: willingness of people to try Sick care network fragility during pandemic has pushed people to try lifestyle first Increased willingness combined with social media has also created confusion Science and authenticity is the key invite driver: people see the difference between nutritionist vs a clinical practice "we are the only company in India (comparable in US peter in...' WHERE id = 201 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): ' WHERE id = 206 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'AI Notes:: This meeting was an investment evaluation call with Nirav, founder of Ignosis, an Account Aggregator (AA) orchestration and analytics platform in India''s fintech sector. Company Background: - Nirav founded Ignosis in January 2022 after running Pyramid FinTech (IT services company) - He''s selling Pyramid (~50 Cr valuation) to focus on Ignosis - Previously spent 12 years in New York working in fintech - Based in Ahmedabad with 30-person team (24 tech, 6 non-tech) - Co-founder Chintan handles tech while Nirav handles business - Hiring strategy: Recruit locally from colleges and groom young talent Product & Technology: - Provides AA orchestration across multiple Account Aggregators - Creates 20% improvement in AA conversion rates through intelligent routing - Core analytics layer categorizes transactions, identifies income, spending patterns - Offers white-labeled Personal Finance Management (PFM) solutions - Integrates deeply with clients'' loan origination systems - Competitive advantage: Real-time categorization engine with continuous improvement Business Model & Traction: - 50+ clients with only one churn - ~15-16 crore annual revenue - Two main revenue streams: - Lending analytics (60% of revenue): ₹4-7 per fetch - PFM solutions (40% of revenue): ~₹1-1.5 per active user monthly - MobiKwik is largest customer (40L active users, ~₹40L monthly revenue) - Transaction-level margins around 70% - Profitable, but raising capital for potential AA license acquisition Competi...' WHERE id = 207 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score** ---
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): 
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
De-brief (if any): 
Next conversation with Founder on {use “@now”}: ---
Attendees from DeVC:: 
Z47 Conversation with Founder on {use “@now”}: 
Notes:: 
Attendees:: 
Notes:: 
De-brief (if any): ' WHERE id = 208 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Received from Rahul - 2026-03-13: [https://www.linkedin.com/in/jagdeep-singh-805b55124?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app](https://www.linkedin.com/in/jagdeep-singh-805b55124?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app) Groww director/business head of broking starting up ---' WHERE id = 216 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Post-Meeting Investor Debrief: The investors expressed skepticism after the meeting. Concerns raised included: - Lack of clear moat despite claims of simple, superior design - Questions about why Xiaomi (known for despeccing products) hasn''t implemented similar design improvements - Uncertainty about learnings from previous startup failure/wind-down - Doubts about founder''s ability to scale in a difficult category The investors agreed to pass on the opportunity. This is all the malls, Phoenix, PurchaseLegal, Nexus, It''s all of the chains, right? McDonald''s, Subway, KFC, a lot of independent types are for $1,000. We''ll start with one. So that was my bread and butter for the longest time. Then in 2021, we decided we wanted to do something else. We no longer wanted to be an app, but we wanted to continue driving to fall to stores. So we came up with what is today the only affiliate program for offline stores, which is like seamless, clean, neat, etc. I ran that for three years until 2024. We raised a lot of money for that business. We were backed by all of the amazing folks, founders of Swiggy, Razorpay, Mama Earth, and so on. I was building a company with my fiancee at the time. We parted ways. And I decided I don''t know, I wanted to pursue that opportunity. We were lucky enough to get an acqui-hire from Razorpay, but we turned that down because it was like one next invested capital for a three-year lock-in. But instead, we rolled up a trust and all of my investors got equity i...' WHERE id = 217 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Web Research:: - From Pilot to Profit: Survey Reveals the Financial Services Industry Is Doubling Down on AI Investment and Open Source Explore NVIDIA’s AI solutions and enterprise-level AI platforms for financial services. NVIDIA and Global Industrial Software Leaders Partner With India’s Largest Manufacturers to Drive AI Boom https://blogs.nvidia.com/blog/ai-in-financial-services-survey-2026/ - AI Goes Vertical in Financial Services - by Singularity AMC This is just one example. Millions of scenarios and insurance offerings, based on their possible outcomes with real-time risk assessment could shape the future of insurance as power of compute continu https://www.singularityone.in/p/ai-goes-vertical-in-financial-services - Top startups in Native AI in Financial Services in India (Dec, 2025) - Tracxn Native AI in Financial Services Sector in India has a total of 81 companies which include top companies like <strong>HyperVerge, Scienaptic and Arya.ai</strong>. https://tracxn.com/d/explore/native-ai-in-financial-services-startups-in-india/__Q1Gma5Dgr6QVb3HupvIku84g3GlxeG-3iONQF1m-lZU/companies - Financial AI: 21 Cases of Artificial Intelligence in Banking • UXDA | Financial UX Design Virtually every major bank has financial AI pilot programs, with common use cases around fraud detection, chatbot customer service and credit risk analysis. The momentum is driven by both competitive https://www.theuxda.com/blog/ai-gold-rush-21-digital-banking-ai-case-studies-cx-transformation - To...' WHERE id = 220 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = '**Background and Role at MPL:**: - Hired during COVID (2019) as Rachit''s replacement in design leadership - Initially hired as AVP of design but needed grooming for the role - Later became head of design after an intermediate hire was let go - Successfully aligned the design team with objective business KPIs - Demonstrated steady leadership during turbulent times, including a 60% team reduction **Key Strengths:** - Meticulous and calm under pressure - Resilient and reliable during challenging periods - Excellent people leader (7-8/10 rating) - Strong at lateral and downward management - Objective in difficult decisions, not letting personal relationships affect judgment - Considered among the top 5 design managers Rachit has worked with **Areas for Development:** - Not strong at upward management - Inverted priority hierarchy: Team > Design > Product > Company (should be reversed) - Rated 5-6/10 as a business leader - Unclear if he would have the foresight to preemptively identify business challenges - Receptive to feedback but had limited progress in business orientation **Recommendations:** - [ ] Consider advising Ketan to find a co-founder who is stronger on business acumen - [ ] Conduct additional reference checks to verify business capabilities - [ ] Assess whether Ketan''s business perspective has evolved since leaving MPL ---
RM Notes: 1. Hired Ketan to replace himself - during COVID | 2019 1. Rachit was going to start another initiative within MPL 1. 2-3 months in real...' WHERE id = 221 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): ' WHERE id = 222 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Heads up note for Kairos 2025-07-03T19:59:00.000+05:30: Hi team, Sharing the heads-up note for our investment in [Kairos Computer](https://www.kairos.computer/). This is a computer use AI agent which is capable of automating any tasks through a simple screen recording. DeVC is investing $30K as part of a wider $300K Pre-Seed round as a Community Top-Up to Prateek Sharma (GP @ Ahead VC) and Venky Karnam (GP @ Shift Left Ventures) For context: Cash met Venky in the USA - he owns 1% of Groww & sold his Meesho position for $15M. Prateek co-hosted the IIT Tribes event on 14th May 2025 with DeVC in SFBA. **Founders** 1. [Samarth P](https://www.linkedin.com/in/samarthap/) - CTO | Univ of Toronto grad 1. 6 months @ [Delphi](/22329bccb6fc80c298dbe87f87c0a923) (Sequoia US funded co) 1. 1.5 yrs @ Google as SDE-1 1. [Manas Bam](https://www.linkedin.com/in/manasbam/) - CEO | Stanford grad 1. 3 months @ Delphi 1. 3 months internship @ Sarvam AI **Investing Process** 1. This opportunity was sourced by Aakash during his SF trip in May 2025 1. The founders are part of the Afore VC FIR (Founder In Residence) program 1. Afore VC’s cohort is known to be a great mining ground for tech founders 1. Cash did a 1PE and spent an evening with the founders developing use-cases which generated pull to allow DeVC to participate in an already filled round on same terms as existing investors 1. Founders also attended the IIT Tribes event hosted by Aakash on 17th May 2025 1. Decided to write a Community Top ...' WHERE id = 223 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): ' WHERE id = 224 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Market & Competition Discussion: - Competing with established players like Cursor, WinSurf - Potential challenges with market entry timing - Competition moving in similar direction (e.g., Cursor’s future roadmap) - Discussion around differentiation strategy and market positioning
Background: - Kashif is currently at Rattle (engineering team) - Has been at Rattle for 2 years, 8 months - Previous experience: - Small Case (2 years, initial team member) - StockX (e-commerce platform for sneakers) - Last day at Rattle: May 30th
Startup Context & Problem Space: - Building “Next Crew” - an AI worker system for engineering teams - Key problems being addressed: - Limited engineering bandwidth despite AI coding tools - Need for expertise in prompt engineering to effectively use AI tools - Current MVP features: - Full stack engineering capabilities - Code writing and review - Jira ticket integration - Team collaboration via GitHub, Jira, and Slack
Current Traction & Status: - Basic MVP is live - 2 active users providing feedback - Main blocker: SOC2 compliance needed for deployment to engineering teams - Currently working on expanding tool integrations
Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1....' WHERE id = 225 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Heads up Note by Cash 2025-11-25: Sharing a brief note for our $20K investment in Two Four Lab’s pre-seed round, amounting to ~0.1% ownership Total Round size - $3.5 million (3m by lightspeed, 400k 3one4) Post Money Valuation - $22.22 Million The founding team has strong FMF and knows the consumer tech growth playbook well. They are building multiple AI companions with personalities and with live ops first approach like gaming <u>**Product**</u> Kavana is a new kind of consumer app, where people discover and chat with delightful AI humans. [https://heykavana.com/](https://heykavana.com/) <u>**Founding Team**</u> 1. [Kunal Joshi](https://www.linkedin.com/in/kunaljijoshi/) - Was early growth lead at Kuku FM from earliest days and scaled the platform to ~60M ARR - IIT Mandi 2016 grad 1. [Shubham Ratrey](https://www.linkedin.com/in/shubhamratrey/) - Founding engineer at Kuku FM Founder BRCs: The founders had strong soft refs from Kuku FM. Kunal has been key to driving growth at Kuku “Star of Kuku” - Lal Bisu (co-founder Kuku) <u>**investment Considerations**</u> - Experience operators with strong FMF and past experience of building and scaling consumer tech product - Unique differentiated arpproach to build for a large TAM <u>**Risks**</u> - Product risk : they have to build the growth loop and drive retention with AI character bot approach. - Pre-monetisation + many funded comps doing the same thing with limited to none real differentiated strategy' WHERE id = 226 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): ' WHERE id = 228 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
