UPDATE companies SET agent_ids_notes = 'Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---' WHERE id = 268 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Financial Update — Mar 2026 (Audit): - Last Fiscal Revenue: $0 - Current Monthly Revenue: $0 - Jan 2026 Cash Balance: $760,000 - Jan 2026 Monthly Net Burn: $19,000' WHERE id = 269 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Notes:: 1. Thesis 1. OYO for Pharma, software for pharma & clinics 1. Transition from local chemist to modern medicine affilate store 1. B2b pharma shop digitization 1. Won''t charge for the software -> SaaS doesn''t work in India, we are a service provider 1. Quick Comm using local chemist inventory 1. He believes that acute is the only demand source (?) 1. Also was getting stock up orders 1. Customer has high WTP for acute (₹200) 1. Chronic is subscription or bulk buying 1. His journey 1. 2018 -> clinic, private clinic, preference given by front office staff. Thought of solving via software 1. Cold DM to Subhash to get an internship at Dukaan 1. Felt Dukaan is the right place to build a business or product 1. Pawan from OnArrival offered a paid sabbatical to try building 1. Got 20 orders posting stories on IG 1. Thought demand was only in Tier 1 cities 1. Market learnings 1. Chief Of Staff at Blinkit said they are struggling 1. Blinkit will try to onboard a partner for pharma 1. PharmEasy and 1mg doing 80% prescription meds via channel 1. i.e. local chemists are anyways getting bulk of the acute use-case volume 1. Apollo 24x7 is also doing prescription meds delivery 1. Schedule X or Schedule N medicines have strict regulations 1. Swiggy only focused on OTC meds and not prescription meds 1. Story 1. Business 1. Supply side 1. Young owner < 50 yrs works, QR placed at the store, 1. Channi Hittmat in Jammu, 3 partner stores amongst 13 stores in the area 1. 5 weeks of pilot 1. ₹20...' WHERE id = 270 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = '**TK - Overall View: WM**: **Spikey: 1 (for Ajit); 0.5 (Akshay)** Spike Needed for the biz: consumer/product + High IQ + Both are good combo of right and left brain thinker + customer backward > citing example like building cities for people + Positive BRCs on both ?? Not up to date on numbers – rough calculating it; if running so many experiments numbers should be on top of mind to know which one is working ?? Slow on iteration and shipping – no increase in DAU/MAU over the last 3 months ?? Running too many experiments too early on small base ?? Lack of depth – Akshay asking random ques on AI hardware? <u>**Next Steps**</u> - Closely Track the team and metrics (DAU/MAU/engagement/retention) - No significant change as of now over the last three months. <u>**Detailed Meeting Notes (16.10.25)**</u> **Founder Background** - **Ajit Pol** - Grew up in an Air Force family in Pune; now married into a Marwari family. - Worked at Flipkart – across search and Insuretech biz (2018-21) - Moved to Leap, a full-stack edtech startup enabling students to study abroad - handling exam prep, university partnerships, visa, and financial assistance. - Was first PM at Leap, scaling the counselling business that contributed ~70 % of total revenue, with ARPU of ~$2,500 per student and company-level revenue of ₹300–400 Cr across India, the U.S., and the U.K. - Joined Buystar (founded by ex-manager Sriram) as Head of Product – Majority of rev from cricket but it’s highly seasonal so built Cricket Trum...' WHERE id = 271 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): ' WHERE id = 275 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): ' WHERE id = 277 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Next Steps: - [ ] @Krish Bajaj to try the product and provide feedback - [ ] @Rahul Mathur to conduct reference checks on the founder - [ ] If progressing, arrange meeting with another partner at DVC - [ ] @Rahul Mathur to potentially connect founder with additional potential users Notes 1. Dr Winson Park - Korean researcher - 1. Hybrid job based in Dubai 1. Founder of Xpay recommended him 1. Product #1 - sentiment analysis for brands 1. $20 per month 1. Product #2 - receptionist for dentists 1. $500 per month from clinics 1. Was selling from India to USA 1. Discontinued 1. WhatsApp 1. Doing via Linked Devices 1. Indian user willing to pay $50 per month 1. US user willing to pay $80 per month 1. They want Slack integration 1. Shipped for Rishabh Dodo Payments 1. Smart / inherent virality via “@loop” 1. Users: 1. CA or Doctor for Qs 1. Founders to monitor senitments from 1. Students / others use it to listen to WA groups Sir, can I get one green tea please? Okay sir. Thank you. Hey Amon, how are you doing? Hey man, very nice background. Where are you calling from today? I''m in Bangalore. Thanks sir, it''s a fake background. No, I''ll go in. I''m in Bangalore. Residency has a global network, so I''m part of Bangalore right now. But yeah, I''ll go in Jan. For like 3 months. Where are you right now? I was in Bangalore. He is in HSR. Currently, I am in Badubhishnadi. Residency is a very good thing. I recently was in SF, I met Abhinav from Breather and he speaks very highly of the resid...' WHERE id = 279 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Deck: [File: download](https://prod-files-secure.s3.us-west-2.amazonaws.com/b21975bb-aebf-48e3-8c44-1573c4404129/c03c41e0-d2d8-4543-b15d-a8d53a028d10/1._Modus_AI--Fundraising.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAZI2LB4666H7XLVMC%2F20260320%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20260320T105658Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGgaCXVzLXdlc3QtMiJHMEUCIQD%2FGwFQao5dI0GDb0x7cTeid9oZgJvyW3cDhABH3pf1DQIgC7f3rxd8uGiKg5KHV2Qm%2FpWbTb2nxymg0%2FiQ7Y9vpNQq%2FwMIMRAAGgw2Mzc0MjMxODM4MDUiDBytoewTaYvbMdVlwircA9RuoshDLpVmLUs5HzjvLIafs%2F8vodmSo2haKbTwYaNq7QsDD1%2F60JZdzJoJ1MuXmiMSTVfhi1%2BRmjYWfpx8DkTLVV2D476v21rBhx5MhjJFnwDWLDb9Vt422VEniywh2u0MkWmkQNVJUKBibTKixMDJ11zET1udRjc5rMrCqktenqwwLJApNTstRRY2yOqj05VVl7ZBSGKyHtAtmYaOX1y7DaYD542MYsIzax84lcuDaRqyaEYQHJzmGNk58ll0CPrHE7Dn4W%2FJytkBTf7%2F5vRnqnQKjo1h3RD3Ly77ym%2BuwaCXgf89w8bKXPngKJT%2BKDFGrVitPB7%2B9n7EOt3q695JXKLe6x03OZFdDBGfrbzfBdidKjG%2FQV8XxbLcOmae6L%2FtLW%2FXT4FowuNryQ9P1dRoQL78baiqkfZ5v6CHq0C1djUH4Uc5wGbcx04soPh5OUbyrqlA9foKr1ftn1ihzs0j33zoLfrXYgRjMOZ8PXE3NL6EqymbDWQukJ721H62fntScwONK5iw0OsrXMX%2Bfj5N7BOGkyN2bnWLcCaNem8idcqs6B34vJoi0aorH%2Fe0PAD%2F0YgV1UsVQhPorYXkNEmzHJt5EMTlRvXld8xr7yeWLKcw%2BqhG%2BK5sjqWDMJv8880GOqUB58NbLqpzQXZeLn6vIAMKvgYBzbTVKS43VBnwTQnawerr9deqPDSGyhVCsuTEjxw7pLu4xI2%2BPKdrwcPz6eMZgJbvLnc1BrgR9HU2BYwXMpTVG25glDq5DeTPFaQE9VzJnr9ULlwdGml%2FIC%2BAdxlrEiGDLC2VNDiC4ZT7r88CALFKhbuve2UJjT5SMvJeEeytgkwdGuwQMXq3X1PY%2BmtYjiUgxd%2Fv&X-...' WHERE id = 283 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Notes:: 1. **Childhood** 1. Full Hindi guy 1. From small town in Bihar 1. Not strong financial background 1. 23 years old 1. **Rewards / gaming business** 1. First business he built at 17 1. Built an app on no-code platform 1. Got 1L+ installs 1. Was making $4K per month || scaled to 500K installs 1. Google killed the business by changing ads policy 1. **2nd business** 1. 1M installs 1. WhatsApp related business 1. Each QA update killed the release 1. BLR - Jain Univ — just before COVID - left 1. **Food delivery business in his local city** 1. Started before Swiggy & Zomato post COVID 1. Swiggy & Zomato entered which killed the business 1. Sold the software & logistics to a restaurant business locally 1. **Kutumb** 1. Approached Abhishek with an earlier idea 1. Abhishek told him to come to Kutumb & test 1. Wanted to find the next $1bn idea 1. Ran thousands of ads 1. Spoke to customers across T1 and T2 1. Explored a lot of T1/T2 cities 1. Tried multiple D2C products 1. Problem in D2C → frequency 1. **His learnings** 1. Snacks → high frequency category 1. Companies are making guilt free western snacks 1. Why not make traditional snacks guilt free 1. Ran 50 ads variants — found 50 SKUs 1. Saw QC tailwind 1. Mom is the culinary expert 1. He figured out something about the form factor (I can’t understand Hindi) 1. **MIS** 1. No QC | no 3P market 1. October - ₹3L in Sales | 70% pre-paid | CAC 1. **What would change if he had capital** 1. 3 years — ₹100 crore 1. **Kitchen** 1. Start...' WHERE id = 284 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Investor Feedback & Decision: - **Z47''s assessment**: - Very high bar for QSR investments - Founders "not bad but nothing exceptional" - Category not sufficiently differentiated (every market has street food) - Prefer non-linear business models over linear store-by-store expansion - 10% EBITDA at ₹20 lakh stores "not great" - economics typically degrade as businesses scale - First few outlets often have better economics that aren''t replicable at scale - Network-wide EBITDA likely to settle at 8-10% - **Key investor concerns**: - Things get difficult at 10-20 outlet scale due to competition, food consistency issues, or location choices - 15% monthly attrition means 150 people leaving monthly at 100-store scale - Important metrics to track: customer feedback, NPS, repeat rates, same-store sales growth - **Investment decision**: Pass from Z47, but Titan Fund is leading the round And both moving and targeting the new target with the update in Bangalore for the Ramadhin survey for today. We all built that up for the update in Bangalore now. Then we also started downloads to operate your veg pan to find out Yes, so about me, I am a commerce graduate turned chef. Before I met Tanay at Mesa, I spent roughly two and a half years working in the kitchen. I started my culinary training in France and then ended up spending two years working in Sweden in a Michelin star restaurant and also in the south of France. So I worked across different formats, Michelin star hotels. In the meanwhile,...' WHERE id = 289 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Action Items: - [ ] Circle back regarding next steps - [ ] Follow up on establishing team in Bay Area Now within a pre-construction, the task can be looked into four different phases. The first one is feasibility, second scoping and costing, third scheduling and procurement and finally construction readiness. After construction readiness, it goes into the project manager who does the execution through the handover. But a project manager usually deals with one project at any point in time. Now compared to that, a pre-con manager... It is not an execution, they deal with multiple projects. Now, the idea for the preform manager, as I was saying, they have to bring in more business. So, the more the number of projects they are able to deal with in parallel, the better it is for them. So, that''s where their North Star metric lies. Now, they had all of these four phases. We land in scoping and costing, that''s the second phase. It will expand to others, but the buyer is the same for all of the phases, because it is the pre-con manager. Now in scoping and costing, primarily what a pre-con manager does is scope sheets, bid levelling and price benchmarking. While I am saying this, I am talking from the perspective of a general contractor, all of it. Pre-con teams exist with owners, developers, subcontractors across the ecosystem, but we work with only general contractors to begin with. Now, when the general contractor receives or the pre-con manager receives all the bid packages from t...' WHERE id = 290 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'AS: Weak Maybe: + In domain founders, good pedigree  – GE + Rolls Royce + Technically strong + Arjun and Rohit seem to have a good leader -follower dynamics ? Founder archetype is  not Matrix ZOB – didn’t see any H&H or ambition to make It very big ? Moat in technology – gas turbines well researched and in commercial use already ? Limited TAM and team also unclear on end market – speaking of multiple use cases but no real pipeline ? Prototype still under development, leveraging IISC facilities ? Thesis – need to understand space better **Meeting Notes:** [Rohit Chouhan](https://www.linkedin.com/in/rohit-chouhan-842b063a/?originalSubdomain=in) - Masters from IIT Delhi - Joined DRDO as Scientist in GTRE - Developing gas turbine engine for Tejas - Developed for 4 years: Kaveri engine - Worked on hot end, development on supply chain – foreign vendors etc - Worked on small gas turbine also – on cruise missile - Joined GE - Known for execution excellence - Started gas turbine team from scratch – became global tech leader for 40-140 mw power gen machine - Designed 3-4 new products, and new tech development - Has more than 50 US granted patents: 20 is on new gas turbine, 30 on new tech within turbine components for efficiency - End use case of their turbines - Aviation – powering aircraft engine - Same tech also used in power generation – electricity - Fundamental diff: in power gen weight is not a constraint, in aviation need lighter variant - Their first product is more suited to A...' WHERE id = 291 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Deck 2026-03-10T11:26:00.000+05:30: [File: download](https://prod-files-secure.s3.us-west-2.amazonaws.com/b21975bb-aebf-48e3-8c44-1573c4404129/57a143dc-6603-4927-94a5-bf5bc6271f9a/2026_03_10_Nama_Stay.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAZI2LB466TDK7S7WY%2F20260320%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20260320T110025Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGgaCXVzLXdlc3QtMiJGMEQCIDG%2F40sSul6%2BZ9DMQ8TseacEBaKWicSR2lh6n2Ng%2BFAxAiBlxv1qSNj99GnVXHn0gUWDTNE5Fibo%2B3K9DyvkRmMjRSr%2FAwgxEAAaDDYzNzQyMzE4MzgwNSIMB%2B99qIcvDGn7aZnxKtwDJ3qvQPncQdIe5lLYLyeV1Je%2FlJ4GSUB7STdaeCsp8htO9VQ765yrtFNF4LcmTG8deJAiSbcbIYTR2HExJVeUKzUhsWhOxT8EF6zlfsnIYvciQBYtU0hON9fTE76BdpQZKbjdWDnNUkW7BnpJbP1vZOyK%2FnMb6S7IzSu%2FRl5ON0IBj0cpihp9hyvmHzHj%2FJaXm%2Fr5f0uDhPne7XR6xJ50Jn4jv1TkPBUuBz37Yfc8wnWOSvGVwzwnwdTzsAu8cMatz8Q6tB%2ByGJOgQnKQItYmyM4iu4b9jtOMnO6V2Op6NR3cgEmCkT5ZdWolluXyqd2nZyZCq5WIidEIqdA97ID71oYHvZYCej2qagBhhNa1VrjWzCY8QWK7DaEBWeCuL35A2nvIMuInedSz6dKKCwaRR%2F3cOY01xJz7g3oMWTvDt1KWF17im3OyyMqTjYX0jA8MfNAMMEgqhyGn6nvxevExN436uuwD23DML3vXR0KfylQ8rh7ciJFCIUJ7o%2BXmdfnfegeulSAGQQQi4m9UAlPzO24zTXmFHHpdwSRNeYH1%2FAVflWmwKUiiJjmmp750HAhFw6MM1KYzpsh6Hg45NQ%2Fm6PmSwUvSocBMGWPxZ5QC4pdqVQ5C6Q44f4J6wb4wuP3zzQY6pgFlZONdrk%2B41qzVSC7OA2QlU%2FAVe8NoMGcogjFqgntJFNJDguXp%2BS4bunnmVIe6LW0yGVSz7aVzk42KrvAJm1aQFlUz8QNFnuvvj7S67BjuMLkRgQJB%2BIBomabx7d0auHEedIrwWuEre21eBv%2BMGzmjJ%2BnLI9CFk8dsLzutfhcEM8hmWFtJw9%2BV1yVXPPFCQD0pwpwcYpdVz...' WHERE id = 292 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): ' WHERE id = 293 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Notes:: Surfacing [Navanc](https://www.navanc.com/about-us), they''re building a tool for property evaluation which is used by lenders in collateral assessment for secured loans. Essentially replacing the local valuer model which has issues such as opacity, TAT, fraud, etc. Founder is an EO with extensive experience in the space. Early traction is also decent - ~30 lakhs MRR, cracked mid-sized NBFCs and in final stages of cracking large NBFCs. The company is raising $2-3 mn. currently. Please find [vault](https://deltazen47.sharepoint.com/:f:/s/TheVault/EoVazkQZAohMugwEJVG_hCUBzM4qFPjTsHBLgOKa2tFOEg?e=czvCd3) link, customer refs + our eval views below - <u>**Eval Views**</u> **Taha - Maybe** + EO building in domain with significant hours in the space, good set of initial clients as well- IRMA + ICICI+ NBFC (pattern match) + Depth in the space --- had clear answers on property diligence(state level), valuation ? Unsure on what this product is — BRE, AI assisted workflow, services with a CRM ? End Scale outcome-- can he expand into legal workflows as well **Dhairen – Maybe** + Domain native + Addressing a major pain point for lenders, can see a play here - need to do ref on delta in efficiency + pricing + Interesting traction - Billing 7-10 lakhs p.m. to mid scale lenders quickly ? Product v/s company? Ability to expand into adjacencies? ? There''s a large services angle at play so will need understand if there''s potential for a business with quality rev. or is it just an aggrega...' WHERE id = 294 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): ' WHERE id = 295 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Draft: Hi team, Sharing the heads-up note for our investment in [Neuralzome Cybernetics](/11f29bccb6fc8040a51cf08cae0cb796). This is a Quickly Teachable Agent platform — allowing users to train equipment or machinery to perform actions or exhibit behaviors. The initial use-case is precision agriculture in the USA. Neuralzome Cybernetics is a spin-out of the AI & Robotics team plus IP from [Flo Mobility](https://flomobility.com/) (a Blume Founder’s Fund portfolio company) DeVC is investing $100K/₹86L as part of a wider ₹12 crore round led by 8X Ventures This is a Venture Partner cheque (via Ashwini) which also meets the DeVC Community Top Up criteria **Founders** 1. [Mohan Shivam](https://www.linkedin.com/in/mohansivam/) — CEO 1. ex CoFo at CTO at Flo Mobility (3 YOE) 1. Ex CoFo at GAMASOME (8.5 YOE) 1. [Aditya Shriwastava](https://www.linkedin.com/in/adish-ai/) — CTO 1. ex head of robotics at Flo Mobility (2 YOE) 1. ex engineer at iFuture Robitics (1.5 YOE) 1. BITS Mera graduate **Investing Process** 1. This was sourced by the DeVC Collective via Soumitra Sharma 1. Cash did the 1PE followed by expert chat (with Peepul Agri founder) 1. From expert chat —  *“Neural is a top notch team | polymath robotics is also doing similar in US, but likely going to be multiple expensive. cost is key here.” * 1. Mohit & DC did a 2PE 1. Per Mohit — *“Spikey 1 with a spike in product and hustle, and resilience.”* 1. Details were surfaced to the full DeVC Collective 1. Ashwini: *“Positives: Fou...' WHERE id = 297 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Evaluation Plan + Key Questions to answer: 1. **What does the company do?** 1. 1. **Do we (DeVC/Z47) have a thesis on this space?** 1. 1. **What are the top 3 questions to diligence?** 1. 1. **Who has piped this company to us? What are their views?** 1. 1. **What do refs say about the founder?** 1. 1. **What''s the DeVC team views?** 1. 1. **What are the Collective signals?** 1. 1. **Why is this company likely to be special?** 1. 1. **Who can help? Experts / Venture Partners?** 1. 1. **Deal dynamics? Potential deal to do?** 1. ---
Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Deck insights from Notion AI on {use “@now”}: ---
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Z47 Conversation with Founder on {use “@now”}: 
Attendees:: 
Notes:: 
De-brief (if any): ' WHERE id = 301 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Heads up note 2025-10-18T16:29:00.000+05:30 from @Rahul Mathur: Hi team, Sharing the heads-up note for our investment in [Nimo Planet](https://www.nimoplanet.com/). The company is shipping/fielding spatial computing for work (Core + OS + glasses) Their proposed solution layer is “Nimo Infinity: Personal AI Workspace” — a canvas with “prompt-to-mini-AI apps,” browser agents for legacy apps, sandboxed memory/context, and an MCP app store. DeVC is investing $50K as part of a 700K round @ $5M post money valuation led by [Mucker Capital](https://mucker.com/) Note: Since this is a community top-up to Anand Lalwani; we will be doing deeper work during our November 25 trip to SF where we will spend time with the founder **Founders** 1. [Rohildev Nattukallingal](https://www.linkedin.com/in/rohildev/) 1. 8.5 YOE @ previous startup 1. Had raised ~$3.2M in VC funding (led by Kalaari India) 1. Launch world''s first gesture based wireless smart ring called Neyya 1. [Suneesh Thuluthiyil](/1c829bccb6fc803f8c38fbaa5ef0617f) 1. 8.5 YOE @ previous startup (together) **Investing Process** 1. We were introduced to Rohildev by Anand Lalwani (CoFo @ Cardinal Robotics) who had already committed to invest $50K into the company and is now adding a further $50K 1. Cash did a 1PE - Weak Maybe for Core Cheque 1. *?? Purely technology out and just doesnt seem like a marketable product builder* 1. *?? Not a first principles CX thinker* 1. *?? Lacks growth chops and past history is un-inspiring. Tinkerer sci...' WHERE id = 302 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Scoring (can be copied for multiple people): **Spiky Score** **EO/FMF/Thesis/Price Score**
Intro conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Follow-up conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---
Next conversation with Founder on {use “@now”}: 
Attendees from DeVC:: 
Notes:: 
De-brief (if any): ---' WHERE id = 303 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Action Items: - [ ] Z47/DVC to consult with Confido about their experience with Nixo - [ ] Z47/DVC to provide investment decision within 48-72 hours - [ ] Akash to introduce Sidhu/Chetan to Priya - [ ] Priya to connect with investors via WhatsApp A good evening. How should we do the intro folks? There are three of us today. Should I just introduce the fund and then everyone give one two lines about themselves? This one is also end of call commit or we have time? Don''t have time but not necessarily end of call. Okay. Because given Anand is deeply plugged in so we can be patient. Okay. No, not yet. No, no, I''m just checking. Oh. Hello Priya. Hi. Hi, very nice to meet you guys. Nice to meet you. Is Preeti also joining? No, she unfortunately can''t make it. She has some other important work to attend to, but I''ll be here. Got it, got it. No, so quick context setting here. Akash Rajat Rao will quickly share a bit about us. We are Z47 and DVC, earlier we were known as Matrix Partners India. We invest out of two funds, one is a venture fund, which is more post-seed-seed to Series B. And DVC is a pre-seed-seed fund, where we partner with founders super early in their journey. Pertaining to what you are building, this is a space we''re pretty deeply calibrated in. At one end for customer success and CESPM, we have a company called Rocket Lane, which we had seeded and then let the A and the B in, which was together with ABC. That was from the venture fund. And outside of that in the depl...' WHERE id = 304 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
UPDATE companies SET agent_ids_notes = 'Next Steps from Rahul: - Introductions to consumer brand founders (Mohit Sadani and others) who successfully used mom influencer GTM channel - Market work and customer chats over next 48 hours - Follow-up discussion with Rajat to determine what''s needed for next meeting - Overall positive reaction: found the concept "refreshingly unique" compared to typical consumer brand pitches He was my junior at IIT Gansur. So that''s when I got in touch with him, met Raghav, Atulia and have been at Judo for the last 5 years. So you know about that part of me. Right. So now, sort of decided to move on. Yeah. Because Preksha has been at this Nomado for I think close to six, eight months now and we did some pilot and there was some conviction to sort of start this up. Yeah. But maybe, Priyaksha, you can talk about your background. So now a very similar profile on paper, very different skills. in practice but yes Engineering background, then worked at CS for a couple of years, then IMB, MBA in ''17. Then I joined McKinsey. I was with McKinsey for about a couple of years And then I, after that I also wanted to at that point I joined OYO. They had launched Mountania for upscale hotels and they wanted somebody to create a full operations team for that and how would everything look like. I joined work with Vivek Sinha for a brief period in India and then moved to a role in UK because Rishabh had decided to shift to UK so I also decided to shift along with him. And so they created a role for me whe...' WHERE id = 305 AND (agent_ids_notes IS NULL OR agent_ids_notes = '');
